import type { StandardWorkBalanceResult, StandardWorkOperatorBalance } from '../../services/standardWork/StandardWorkBalanceService';
export type StandardWorkYamazumiCategory = 'manual' | 'walking' | 'waiting' | 'dependencyIdle';
export interface StandardWorkYamazumiSegment { readonly category: StandardWorkYamazumiCategory; readonly seconds: number; readonly stackStartSeconds: number; readonly stackEndSeconds: number; }
export interface StandardWorkYamazumiBar { readonly operatorId: string; readonly name: string; readonly role: string; readonly active: boolean; readonly segments: readonly StandardWorkYamazumiSegment[]; readonly occupiedSeconds: number; readonly productiveSeconds: number; readonly dependencyIdleSeconds: number; readonly sequenceEndSeconds: number; readonly workloadPercent: number | null; readonly spareTimeSeconds: number | null; readonly overloadSeconds: number | null; readonly entryCount: number; readonly automaticLaunchedSeconds: number; }
export interface StandardWorkYamazumiModel { readonly bars: readonly StandardWorkYamazumiBar[]; readonly taktTimeSeconds: number | null; readonly maximumSeconds: number; }
export function createStandardWorkYamazumiModel(balance: StandardWorkBalanceResult, taktTimeSeconds: number | null, showDependencyIdle: boolean): StandardWorkYamazumiModel {
  const bars = balance.operators.map((row: StandardWorkOperatorBalance) => { let cursor = 0; const segment = (category: StandardWorkYamazumiCategory, seconds: number): StandardWorkYamazumiSegment => { const value = { category, seconds, stackStartSeconds: cursor, stackEndSeconds: cursor + seconds }; cursor += seconds; return value; }; const segments = [segment('manual', row.manualSeconds), segment('walking', row.walkingSeconds), segment('waiting', row.waitingSeconds)]; if (showDependencyIdle) segments.push(segment('dependencyIdle', row.dependencyIdleSeconds)); return { operatorId: row.operatorId, name: row.name, role: row.role, active: row.active, segments, occupiedSeconds: row.occupiedSeconds, productiveSeconds: row.productiveSeconds, dependencyIdleSeconds: row.dependencyIdleSeconds, sequenceEndSeconds: row.endSeconds, workloadPercent: row.workloadPercent, spareTimeSeconds: row.spareTimeSeconds, overloadSeconds: row.overloadSeconds, entryCount: row.entryCount, automaticLaunchedSeconds: row.automaticLaunchedSeconds }; });
  return { bars, taktTimeSeconds, maximumSeconds: Math.max(taktTimeSeconds ?? 0, ...bars.map((bar) => Math.max(bar.sequenceEndSeconds, ...bar.segments.map((segment) => segment.stackEndSeconds))), 1) };
}
