import type { OperationStore } from '../../../services/OperationStore';
import type { ResourceStore } from '../../../services/ResourceStore';
import { actionButton, element } from '../../../ui/dom';
import type { CommandFactory } from '../../../services/history/CommandFactory';
import type { FactoryRouteStore } from '../../../services/FactoryRouteStore';

export interface ResourceDeletionDialogController { readonly element: HTMLDialogElement; request(resourceId: string): void; dispose(): void; }
export function createResourceDeletionDialog(resources: ResourceStore, operations: OperationStore, routes: FactoryRouteStore, commands: CommandFactory, onStatus: (message: string) => void): ResourceDeletionDialogController {
  const dialog = element('dialog', 'confirmation-dialog'); const title = element('h3', '', 'Delete physical resource?'); title.id = 'resource-delete-title'; dialog.setAttribute('aria-labelledby', title.id); const message = element('p'); const actions = element('div', 'confirmation-dialog__actions'); const cancel = actionButton('Cancel'); const confirm = actionButton('Delete and Unassign', 'command-button command-button--primary'); actions.append(cancel, confirm); dialog.append(title, message, actions); let pendingId: string | null = null;
  cancel.addEventListener('click', () => dialog.close()); confirm.addEventListener('click', () => { if (!pendingId) return; const resource = resources.getResource(pendingId); if (!resource) { dialog.close(); return; } const affected = operations.getAssignmentCount(resource.id); const attachedRoutes = routes.getRoutesForResource(resource.id).length; const result = commands.deleteResource(resource.id); if (result === 'deleted') onStatus(`Resource deleted; ${affected} operation${affected === 1 ? '' : 's'} unassigned and ${attachedRoutes} route${attachedRoutes === 1 ? '' : 's'} removed`); else onStatus(result === 'locked' ? 'Resource is locked' : 'Resource not found'); pendingId = null; dialog.close(); });
  return { element: dialog, request: (resourceId) => { const resource = resources.getResource(resourceId); if (!resource) return; if (resource.locked) { onStatus('Resource is locked'); return; } pendingId = resourceId; const affected = operations.getAssignmentCount(resourceId); const attachedRoutes = routes.getRoutesForResource(resourceId).length; message.textContent = `${resource.id} — ${resource.name} is assigned to ${affected} operation${affected === 1 ? '' : 's'} and is an endpoint of ${attachedRoutes} factory route${attachedRoutes === 1 ? '' : 's'}. Deleting it will unassign affected operations and remove attached routes.`; dialog.showModal(); }, dispose: () => dialog.remove() };
}
