import type { StandardWorkStore } from '../../../services/StandardWorkStore';
import type { OperationStore } from '../../../services/OperationStore';
import type { ResourceStore } from '../../../services/ResourceStore';
import type { ProjectSessionService } from '../../../services/project/ProjectSessionService';
import type { StandardWorkOperatorStore } from '../../../services/standardWork/StandardWorkOperatorStore';
import type { StandardWorkHandoverStore } from '../../../services/standardWork/StandardWorkHandoverStore';
import type { StandardWorkSelectionStore } from '../../../services/standardWork/StandardWorkSelectionStore';
import type { StandardWorkPlanningCommandFactory } from '../../../services/history/StandardWorkPlanningCommandFactory';
import type { CommandFactory } from '../../../services/history/CommandFactory';
import { StandardWorkChartScheduler } from '../../../services/standardWork/StandardWorkChartScheduler';
import { calculateStandardWorkTakt } from '../../../services/standardWork/StandardWorkTaktService';
import { calculateStandardWorkCapacity } from '../../../services/standardWork/StandardWorkCapacityService';
import { calculateStandardWorkBalance } from '../../../services/standardWork/StandardWorkBalanceService';
import { createStandardWorkYamazumiModel } from '../../../models/standardWork/StandardWorkYamazumiModels';
import { validateStandardWorkAnalysis } from '../../../services/standardWork/StandardWorkAnalysisValidation';
import type { StandardWorkChartSettings } from '../../../models/standardWork/StandardWorkChartSettings';
import { calculateStandardWorkTakt as calculateTakt } from '../../../services/standardWork/StandardWorkTaktService';
import { formatDuration } from '../../../services/standardWork/DurationFormatter';
import { actionButton, element } from '../../../ui/dom';

export interface StandardWorkWorkBalanceController { readonly element: HTMLElement; render(studyId: string | null): void; fit(): void; openPlanning(studyId: string | null): void; dispose(): void; }

export function createStandardWorkWorkBalance(store: StandardWorkStore, operators: StandardWorkOperatorStore, handovers: StandardWorkHandoverStore, operations: OperationStore, resources: ResourceStore, selection: StandardWorkSelectionStore, planningCommands: StandardWorkPlanningCommandFactory, projectCommands: CommandFactory, project: ProjectSessionService, report: (message: string) => void): StandardWorkWorkBalanceController {
  const root = element('section', 'standard-work-balance'); root.tabIndex = 0; root.setAttribute('aria-label', 'Standard Work Work Balance');
  const toolbar = element('div', 'standard-work-chart-toolbar'); const planningButton = actionButton('Planning Settings'); planningButton.title = 'Edit production-period inputs used to derive takt'; const toggleAnalysis = actionButton('Enable Analysis'); const fitButton = actionButton('Fit Work Balance'); const modeLabel = element('label', 'standard-work-balance-mode'); modeLabel.append(document.createTextNode('Display ')); const modeSelect = element('select'); modeSelect.setAttribute('aria-label', 'Work Balance display mode'); [['categoryStack', 'Category Stack'], ['occupied', 'Occupied Work'], ['productive', 'Productive Work']].forEach(([value, label]) => { const option = element('option', undefined, label); option.value = value; modeSelect.append(option); }); modeLabel.append(modeSelect); const dependencyButton = actionButton('Dependency Idle'); const valuesButton = actionButton('Values'); const percentagesButton = actionButton('Percentages'); const capacityButton = actionButton('Capacity Summary'); toolbar.append(planningButton, toggleAnalysis, fitButton, modeLabel, dependencyButton, valuesButton, percentagesButton, capacityButton);
  const summary = element('div', 'standard-work-chart-summary standard-work-balance-summary'); const chartScroll = element('div', 'standard-work-balance-scroll'); chartScroll.tabIndex = 0; chartScroll.setAttribute('aria-label', 'Scrollable Yamazumi operator workload chart'); const chart = element('div', 'standard-work-yamazumi'); chartScroll.append(chart); const tableScroll = element('div', 'standard-work-balance-table-scroll'); const table = element('table', 'standard-work-balance-table'); tableScroll.append(table); const diagnostics = element('div', 'standard-work-chart-diagnostics'); root.append(toolbar, summary, chartScroll, tableScroll, diagnostics);
  const dialog = element('dialog', 'standard-work-chart-settings standard-work-planning-dialog'); const form = element('form'); form.method = 'dialog'; dialog.append(form); root.append(dialog);
  const scheduler = new StandardWorkChartScheduler(operations, resources, operators, handovers); let activeStudyId: string | null = null; let disposed = false;
  const settings = (): StandardWorkChartSettings => project.getSettings().standardWork.chart;
  const persistChart = (patch: Partial<StandardWorkChartSettings>, description: string): void => { const standardWork = project.getSettings().standardWork; if (projectCommands.updateProjectSettings({ standardWork: { ...standardWork, chart: { ...standardWork.chart, ...patch } } })) report(description); };
  const fit = (): void => { chartScroll.scrollLeft = 0; report('Work Balance fitted'); };
  const openPlanning = (studyId: string | null): void => {
    const planning = studyId ? project.standardWorkPlanning.get(studyId) : undefined; if (!planning) { report('Select a Standard Work study first'); return; }
    form.replaceChildren(element('h2', undefined, 'Standard Work Planning Settings'), element('p', 'standard-work-help', 'Takt time is the available production time divided by required output for the selected planning period.'));
    const controls = new Map<string, HTMLInputElement | HTMLTextAreaElement>();
    const field = (key: string, labelText: string, value: string, type = 'number'): void => { const label = element('label', 'standard-work-field'); label.append(element('span', undefined, labelText)); const input = type === 'textarea' ? element('textarea') : element('input'); if (input instanceof HTMLInputElement) { input.type = type; if (type === 'number') { input.min = '0'; input.step = 'any'; } } input.value = value; controls.set(key, input); label.append(input); form.append(label); };
    const activeLabel = element('label', 'standard-work-check'); const active = element('input'); active.type = 'checkbox'; active.checked = planning.active; activeLabel.append(active, document.createTextNode(' Enable takt and work-balance analysis')); form.append(activeLabel);
    field('periodName', 'Planning period name', planning.periodName, 'text'); field('scheduledProductionTimeSeconds', 'Scheduled production time (seconds)', String(planning.scheduledProductionTimeSeconds)); field('plannedBreakTimeSeconds', 'Planned break time (seconds)', String(planning.plannedBreakTimeSeconds)); field('plannedDowntimeSeconds', 'Planned downtime (seconds)', String(planning.plannedDowntimeSeconds)); field('requiredOutputUnits', 'Required output (units)', String(planning.requiredOutputUnits)); field('notes', 'Planning notes', planning.notes, 'textarea');
    const takt = calculateTakt(planning); form.append(element('p', undefined, `Net available production time: ${takt.netAvailableProductionSeconds ?? 'Not available'} seconds`), element('p', undefined, `Takt time: ${takt.taktTimeSeconds ?? 'Not available'} seconds`));
    const actions = element('div', 'standard-work-chart-settings-actions'); const cancel = actionButton('Cancel'); cancel.addEventListener('click', () => dialog.close()); const apply = actionButton('Apply Planning Settings'); apply.addEventListener('click', (event) => { event.preventDefault(); const next = { active: active.checked, periodName: controls.get('periodName')!.value, scheduledProductionTimeSeconds: Number(controls.get('scheduledProductionTimeSeconds')!.value), plannedBreakTimeSeconds: Number(controls.get('plannedBreakTimeSeconds')!.value), plannedDowntimeSeconds: Number(controls.get('plannedDowntimeSeconds')!.value), requiredOutputUnits: Number(controls.get('requiredOutputUnits')!.value), notes: controls.get('notes')!.value }; if (planningCommands.update(planning.studyId, next, `Update takt planning for ${planning.studyId}`)) { report('Planning settings updated'); dialog.close(); } else report('Planning settings are invalid; no values were changed'); }); actions.append(cancel, apply); form.append(actions); dialog.showModal();
  };
  const render = (studyId: string | null): void => {
    if (disposed) return; activeStudyId = studyId; summary.replaceChildren(); chart.replaceChildren(); table.replaceChildren(); diagnostics.replaceChildren(); const study = studyId ? store.getStudy(studyId) : undefined; const planning = studyId ? project.standardWorkPlanning.get(studyId) : undefined;
    planningButton.disabled = !planning; toggleAnalysis.disabled = !planning; fitButton.disabled = !study; dependencyButton.disabled = !study; valuesButton.disabled = !study; percentagesButton.disabled = !study; capacityButton.disabled = !study;
    if (!study || !planning) { chart.append(element('p', undefined, 'Select a Standard Work study to analyse operator work balance.')); return; }
    const schedule = scheduler.calculate(study, store.getEntries(study.id)); const takt = calculateStandardWorkTakt(planning); const activeTaktTimeSeconds = planning.active && takt.valid ? takt.taktTimeSeconds : null; const balance = calculateStandardWorkBalance(schedule, operators.getOperators(study.id), activeTaktTimeSeconds); const capacity = calculateStandardWorkCapacity({ ...takt, active: planning.active }, schedule.chartCycleSpanSeconds, planning.requiredOutputUnits); const model = createStandardWorkYamazumiModel(balance, activeTaktTimeSeconds, settings().showDependencyIdle); const issues = validateStandardWorkAnalysis(planning, takt, schedule, balance, capacity); const timeFormat = project.getSettings().standardWork.timeFormat;
    const metric = (name: string, value: string): void => { const card = element('div', 'standard-work-chart-metric'); card.append(element('small', undefined, name), element('strong', undefined, value)); summary.append(card); };
    metric('Planning period', planning.periodName || 'Not available');
    metric('Scheduled time', formatDuration(planning.scheduledProductionTimeSeconds, timeFormat));
    metric('Planned breaks', formatDuration(planning.plannedBreakTimeSeconds, timeFormat));
    metric('Planned downtime', formatDuration(planning.plannedDowntimeSeconds, timeFormat));
    metric('Net available', takt.netAvailableProductionSeconds === null ? 'Not available' : formatDuration(takt.netAvailableProductionSeconds, timeFormat));
    metric('Required output', `${planning.requiredOutputUnits} units`);
    metric('Takt time', activeTaktTimeSeconds === null ? planning.active ? 'Invalid' : 'Inactive' : formatDuration(activeTaktTimeSeconds, timeFormat));
    metric('Chart cycle span', formatDuration(schedule.chartCycleSpanSeconds, timeFormat));
    metric('Chart span delta', capacity.cycleSpanDeltaSeconds === null ? 'Not available' : `${capacity.cycleSpanDeltaSeconds >= 0 ? '+' : '-'}${formatDuration(Math.abs(capacity.cycleSpanDeltaSeconds), timeFormat)}`);
    if (settings().showCapacitySummary) {
      metric('Chart-based nominal capacity', capacity.nominalUnitsPerPeriod === null ? 'Not available' : `${capacity.nominalUnitsPerPeriod.toFixed(3)} units`);
      metric('Whole nominal units', capacity.wholeNominalUnitsPerPeriod === null ? 'Not available' : String(capacity.wholeNominalUnitsPerPeriod));
      metric('Capacity surplus or shortfall', capacity.capacityDeltaUnits === null ? 'Not available' : `${capacity.capacityDeltaUnits >= 0 ? 'Surplus' : 'Shortfall'} ${Math.abs(capacity.capacityDeltaUnits).toFixed(3)} units`);
    }
    metric('Included operators', String(balance.includedOperatorCount));
    metric('Theoretical minimum operators by occupied work content', balance.theoreticalMinimumOperators === null ? 'Not available' : String(balance.theoreticalMinimumOperators));
    metric('Actual versus theoretical', balance.operatorCountDifference === null ? 'Not available' : `${balance.operatorCountDifference >= 0 ? '+' : ''}${balance.operatorCountDifference}`);
    metric('Total occupied work', formatDuration(balance.totalOperatorOccupiedSeconds, timeFormat));
    metric('Available operator capacity at takt', balance.availableOperatorCapacitySeconds === null ? 'Not available' : formatDuration(balance.availableOperatorCapacitySeconds, timeFormat));
    metric('Work-balance efficiency against takt', balance.balanceEfficiencyPercent === null ? 'Not available' : `${balance.balanceEfficiencyPercent.toFixed(3)}%`);
    metric(balance.balanceEfficiencyPercent !== null && balance.balanceEfficiencyPercent > 100 ? 'Work-balance overload' : 'Balance loss', balance.balanceEfficiencyPercent === null ? 'Not available' : balance.balanceEfficiencyPercent > 100 ? `${(balance.balanceEfficiencyPercent - 100).toFixed(3)}%` : `${(balance.balanceLossPercent ?? 0).toFixed(3)}%`);
    metric('Workload spread', formatDuration(balance.workloadSpreadSeconds, timeFormat));
    metric('Minimum workload', formatDuration(balance.minimumWorkloadSeconds, timeFormat));
    metric('Maximum workload', formatDuration(balance.maximumWorkloadSeconds, timeFormat));
    metric('Mean workload', formatDuration(balance.meanWorkloadSeconds, timeFormat));
    metric('Median workload', formatDuration(balance.medianWorkloadSeconds, timeFormat));
    metric('Workload standard deviation', formatDuration(balance.standardDeviationSeconds, timeFormat));
    const highest = balance.highestAssignedWorkload; metric('Highest assigned operator workload', highest ? `${highest.name} · ${formatDuration(highest.occupiedSeconds, timeFormat)} · ${highest.workloadPercent?.toFixed(1) ?? 'N/A'}%` : 'Not available');
    chart.dataset.density = settings().workBalanceDensity; chart.dataset.mode = settings().workBalanceViewMode; chart.style.setProperty('--yamazumi-max', String(model.maximumSeconds));
    for (const bar of model.bars) { const wrapper = actionButton('', `standard-work-yamazumi-bar${selection.get().kind === 'standardWorkOperator' && selection.get().id === bar.operatorId ? ' standard-work-yamazumi-bar--selected' : ''}`); wrapper.dataset.operatorId = bar.operatorId; wrapper.setAttribute('aria-label', `${bar.name}; Manual ${bar.segments[0]?.seconds ?? 0}; Walking ${bar.segments[1]?.seconds ?? 0}; Waiting ${bar.segments[2]?.seconds ?? 0}; occupied ${bar.occupiedSeconds}; dependency idle ${bar.dependencyIdleSeconds}; workload ${bar.workloadPercent?.toFixed(1) ?? 'not available'} percent`); wrapper.title = `${bar.operatorId} — ${bar.name}\nManual ${bar.segments[0]?.seconds ?? 0}s · Walking ${bar.segments[1]?.seconds ?? 0}s · Waiting ${bar.segments[2]?.seconds ?? 0}s\nOccupied ${bar.occupiedSeconds}s · Productive ${bar.productiveSeconds}s · Dependency idle ${bar.dependencyIdleSeconds}s\nLane end ${bar.sequenceEndSeconds}s · Takt ${model.taktTimeSeconds ?? 'N/A'}s · ${bar.overloadSeconds ? `Overload ${bar.overloadSeconds}s` : `Spare ${bar.spareTimeSeconds ?? 'N/A'}s`}\nEntries ${bar.entryCount} · Automatic launched ${bar.automaticLaunchedSeconds}s`;
      const stack = element('div', 'standard-work-yamazumi-stack'); const mode = settings().workBalanceViewMode; const occupiedSegments = bar.segments.filter((segment) => segment.category !== 'dependencyIdle'); const visualSegments: Array<{ category: string; seconds: number }> = mode === 'categoryStack' ? occupiedSegments : [{ category: mode, seconds: mode === 'occupied' ? bar.occupiedSeconds : bar.productiveSeconds }]; const dependencyIdle = bar.segments.find((segment) => segment.category === 'dependencyIdle'); if (dependencyIdle) visualSegments.push(dependencyIdle); for (const segment of visualSegments) { if (!segment.seconds) continue; const part = element('div', `standard-work-yamazumi-segment standard-work-yamazumi-segment--${segment.category}`); part.style.height = `${segment.seconds / model.maximumSeconds * 100}%`; if (settings().showWorkBalanceValues) part.append(element('span', undefined, `${segment.seconds.toFixed(1)}s`)); stack.append(part); } if (model.taktTimeSeconds !== null && settings().showTaktLine) { const line = element('div', 'standard-work-yamazumi-takt'); line.style.bottom = `${model.taktTimeSeconds / model.maximumSeconds * 100}%`; line.title = `Takt time ${model.taktTimeSeconds} seconds`; stack.append(line); } wrapper.append(stack, element('strong', undefined, bar.name), element('small', undefined, settings().showWorkBalancePercentages && bar.workloadPercent !== null ? `${bar.workloadPercent.toFixed(1)}%` : formatDuration(bar.occupiedSeconds, timeFormat))); wrapper.addEventListener('click', () => selection.select({ kind: 'standardWorkOperator', id: bar.operatorId })); chart.append(wrapper); }
    const headers = ['Operator', 'Active', 'Manual', 'Walking', 'Waiting', 'Occupied', 'Productive', 'Dependency Idle', 'Lane End', 'Takt', 'Workload %', 'Spare or Overload', 'Entry Count', 'Status']; const head = element('thead'); const headRow = element('tr'); headers.forEach((header) => headRow.append(element('th', undefined, header))); head.append(headRow); const body = element('tbody'); for (const row of balance.operators) { const tr = element('tr'); tr.tabIndex = 0; tr.classList.toggle('standard-work-balance-row--selected', selection.get().kind === 'standardWorkOperator' && selection.get().id === row.operatorId); const status = row.overloadSeconds ? `Over takt by ${formatDuration(row.overloadSeconds, timeFormat)}` : row.spareTimeSeconds === null ? 'Analysis unavailable' : `${formatDuration(row.spareTimeSeconds, timeFormat)} spare`; [row.name, row.active ? 'Active' : 'Inactive', row.manualSeconds, row.walkingSeconds, row.waitingSeconds, row.occupiedSeconds, row.productiveSeconds, row.dependencyIdleSeconds, row.endSeconds, activeTaktTimeSeconds ?? 'Not available', row.workloadPercent === null ? 'Not available' : `${row.workloadPercent.toFixed(2)}%`, status, row.entryCount, status].forEach((value) => tr.append(element('td', undefined, String(value)))); tr.addEventListener('click', () => selection.select({ kind: 'standardWorkOperator', id: row.operatorId })); tr.addEventListener('focus', () => selection.select({ kind: 'standardWorkOperator', id: row.operatorId })); body.append(tr); } table.append(head, body);
    diagnostics.append(element('h3', undefined, `Analysis diagnostics · ${issues.filter((item) => item.severity === 'error').length} errors · ${issues.filter((item) => item.severity === 'warning').length} warnings`)); issues.slice(0, 20).forEach((issue) => diagnostics.append(element('p', `standard-work-issue standard-work-issue--${issue.severity}`, `${issue.severity.toUpperCase()}: ${issue.message}`))); if (settings().showCapacitySummary) diagnostics.append(element('p', 'standard-work-capacity-disclaimer', 'Chart-based nominal capacity uses the current Standard Work chart cycle span and does not include variability, downtime beyond the entered planning allowance, queueing, simulation effects, or authoritative physical-resource capacity.'));
    toggleAnalysis.textContent = planning.active ? 'Disable Analysis' : 'Enable Analysis'; toggleAnalysis.setAttribute('aria-label', planning.active ? 'Disable Analysis' : 'Enable Analysis'); toggleAnalysis.setAttribute('aria-pressed', String(planning.active)); modeSelect.value = settings().workBalanceViewMode; dependencyButton.setAttribute('aria-pressed', String(settings().showDependencyIdle)); valuesButton.setAttribute('aria-pressed', String(settings().showWorkBalanceValues)); percentagesButton.setAttribute('aria-pressed', String(settings().showWorkBalancePercentages)); capacityButton.setAttribute('aria-pressed', String(settings().showCapacitySummary));
  };
  planningButton.addEventListener('click', () => openPlanning(activeStudyId)); toggleAnalysis.addEventListener('click', () => { const planning = activeStudyId ? project.standardWorkPlanning.get(activeStudyId) : undefined; if (planning && planningCommands.update(planning.studyId, { active: !planning.active }, `${planning.active ? 'Disable' : 'Enable'} takt analysis for ${planning.studyId}`)) report(planning.active ? 'Takt analysis disabled' : 'Takt analysis enabled'); }); fitButton.addEventListener('click', fit); modeSelect.addEventListener('change', () => persistChart({ workBalanceViewMode: modeSelect.value as StandardWorkChartSettings['workBalanceViewMode'] }, `Work Balance display changed to ${modeSelect.selectedOptions[0]?.textContent}`)); dependencyButton.addEventListener('click', () => persistChart({ showDependencyIdle: !settings().showDependencyIdle }, 'Dependency idle display toggled')); valuesButton.addEventListener('click', () => persistChart({ showWorkBalanceValues: !settings().showWorkBalanceValues }, 'Work Balance values toggled')); percentagesButton.addEventListener('click', () => persistChart({ showWorkBalancePercentages: !settings().showWorkBalancePercentages }, 'Work Balance percentages toggled')); capacityButton.addEventListener('click', () => persistChart({ showCapacitySummary: !settings().showCapacitySummary }, 'Capacity summary toggled'));
  root.addEventListener('keydown', (event) => { if (event.key === 'Home') chartScroll.scrollLeft = 0; else if (event.key === 'End') chartScroll.scrollLeft = chartScroll.scrollWidth; });
  return { element: root, render, fit, openPlanning, dispose: () => { disposed = true; dialog.close(); } };
}
