import type { StandardWorkStore } from '../../../services/StandardWorkStore';
import type { StandardWorkCommandFactory } from '../../../services/history/StandardWorkCommandFactory';
import type { StandardWorkSelectionStore } from '../../../services/standardWork/StandardWorkSelectionStore';
import type { StandardWorkOperationResolver } from '../../../services/standardWork/StandardWorkOperationResolver';
import { calculateStandardWorkSummary } from '../../../services/standardWork/StandardWorkCalculationService';
import { validateStandardWork } from '../../../services/standardWork/StandardWorkValidationService';
import type { OperationStore } from '../../../services/OperationStore';
import type { ResourceStore } from '../../../services/ResourceStore';
import type { StandardWorkOperatorStore } from '../../../services/standardWork/StandardWorkOperatorStore';
import type { StandardWorkHandoverStore } from '../../../services/standardWork/StandardWorkHandoverStore';
import type { StandardWorkOperatorCommandFactory } from '../../../services/history/StandardWorkOperatorCommandFactory';
import type { StandardWorkHandoverCommandFactory } from '../../../services/history/StandardWorkHandoverCommandFactory';
import type { StandardWorkTimeFormat } from '../../../models/standardWork/StandardWork';
import { formatDuration } from '../../../services/standardWork/DurationFormatter';
import { actionButton, element } from '../../../ui/dom';

export interface StandardWorkPropertiesController { readonly element: HTMLElement; render(format: StandardWorkTimeFormat): void; }

export function createStandardWorkProperties(store: StandardWorkStore, operators: StandardWorkOperatorStore, handovers: StandardWorkHandoverStore, resources: ResourceStore, operations: OperationStore, resolver: StandardWorkOperationResolver, selection: StandardWorkSelectionStore, commands: StandardWorkCommandFactory, operatorCommands: StandardWorkOperatorCommandFactory, handoverCommands: StandardWorkHandoverCommandFactory, locateOperation: (id: string) => void, locateResource: (id: string) => void, report: (message: string) => void): StandardWorkPropertiesController {
  const panel = element('aside', 'standard-work-properties'); panel.setAttribute('aria-label', 'Standard Work properties and timing summary');
  const field = (label: string, value: string, change?: (value: string) => void, multiline = false): HTMLElement => { const wrapper = element('label', 'standard-work-field'); wrapper.append(element('span', undefined, label)); const input = multiline ? element('textarea') : element('input'); input.value = value; if (!change) input.readOnly = true; else input.addEventListener('change', () => change(input.value)); wrapper.append(input); return wrapper; };
  const render = (format: StandardWorkTimeFormat): void => {
    panel.replaceChildren(element('h2', undefined, 'Properties')); const selected = selection.get();
    if (selected.kind === 'standardWorkOperator') {
      const operator = operators.getOperator(selected.id); if (!operator) { panel.append(element('p', undefined, 'Operator no longer exists.')); return; }
      panel.append(field('Operator ID', operator.id), field('Name', operator.name, (name) => operatorCommands.update(operator.id, { name }, `Rename operator ${operator.id}`)), field('Role', operator.role, (role) => operatorCommands.update(operator.id, { role })), field('Display order', String(operator.displayOrder)), field('Notes', operator.notes, (notes) => operatorCommands.update(operator.id, { notes }), true));
      const active = element('label', 'standard-work-check'); const activeBox = element('input'); activeBox.type = 'checkbox'; activeBox.checked = operator.active; activeBox.addEventListener('change', () => operatorCommands.update(operator.id, { active: activeBox.checked }, `${activeBox.checked ? 'Activate' : 'Deactivate'} ${operator.id}`)); active.append(activeBox, document.createTextNode(' Active operator')); panel.append(active);
      const resourceLabel = element('label', 'standard-work-field'); resourceLabel.append(element('span', undefined, 'Linked physical resource')); const resourceSelect = element('select'); const none = element('option', undefined, 'None'); none.value = ''; resourceSelect.append(none); for (const resource of resources.getPlacedResources()) { const option = element('option', undefined, `${resource.name} (${resource.id})`); option.value = resource.id; resourceSelect.append(option); } resourceSelect.value = operator.linkedResourceId ?? ''; resourceSelect.addEventListener('change', () => operatorCommands.update(operator.id, { linkedResourceId: resourceSelect.value || null }, `Link ${operator.id} to resource`)); resourceLabel.append(resourceSelect); panel.append(resourceLabel); if (operator.linkedResourceId) { const locate = actionButton('Locate Linked Resource'); locate.addEventListener('click', () => locateResource(operator.linkedResourceId!)); panel.append(locate); } return;
    }
    if (selected.kind === 'standardWorkHandover') {
      const handover = handovers.getHandover(selected.id); if (!handover) { panel.append(element('p', undefined, 'Handover no longer exists.')); return; }
      const from = store.getEntry(handover.fromEntryId); const to = store.getEntry(handover.toEntryId); panel.append(field('Handover ID', handover.id), field('Study ID', handover.studyId), field('From entry', `${handover.fromEntryId}${from ? ` (${from.operationId})` : ''}`), field('To entry', `${handover.toEntryId}${to ? ` (${to.operationId})` : ''}`), field('Note', handover.note, (note) => handoverCommands.update(handover.id, { note }), true)); const enabled = element('label', 'standard-work-check'); const box = element('input'); box.type = 'checkbox'; box.checked = handover.enabled; box.addEventListener('change', () => handoverCommands.update(handover.id, { enabled: box.checked }, `${box.checked ? 'Enable' : 'Disable'} ${handover.id}`)); enabled.append(box, document.createTextNode(' Enabled handover')); const remove = actionButton('Delete Handover'); remove.addEventListener('click', () => handoverCommands.delete(handover.id)); panel.append(enabled, remove); return;
    }
    if (selected.kind === 'standardWorkEntry') {
      const entry = store.getEntry(selected.id); if (!entry) { panel.append(element('p', undefined, 'Entry no longer exists.')); return; } const value = resolver.resolve(entry);
      panel.append(field('Entry ID', entry.id), field('Study ID', entry.studyId), field('Operation ID', entry.operationId), field('Operation name', value.operationName), field('Timing category', value.timingCategory ?? 'Invalid'), field('Base cycle time', value.baseCycleTimeSeconds === null ? 'Invalid' : formatDuration(value.baseCycleTimeSeconds, format)));
      const operatorLabel = element('label', 'standard-work-field'); operatorLabel.append(element('span', undefined, 'Assigned operator')); const operatorSelect = element('select'); for (const operator of operators.getOperators(entry.studyId)) { const option = element('option', undefined, `${operator.name} (${operator.id})${operator.active ? '' : ' — inactive'}`); option.value = operator.id; operatorSelect.append(option); } operatorSelect.value = entry.assignedOperatorId; operatorSelect.addEventListener('change', () => operatorCommands.assignEntry(entry.id, operatorSelect.value)); operatorLabel.append(operatorSelect); panel.append(operatorLabel);
      const occurrences = field('Occurrences', String(entry.occurrences), (raw) => { const next = Number(raw); report(Number.isInteger(next) && commands.updateEntry(entry.id, { occurrences: next }, `Change occurrences for ${entry.id}`) ? `Occurrences changed to ${next}` : 'Occurrences must be a positive integer'); });
      const occurrenceInput = occurrences.querySelector('input'); if (occurrenceInput) { occurrenceInput.type = 'number'; occurrenceInput.min = '1'; occurrenceInput.max = '1000000'; occurrenceInput.step = '1'; }
      const enabled = element('label', 'standard-work-check'); const box = element('input'); box.type = 'checkbox'; box.checked = entry.enabled; box.addEventListener('change', () => { commands.updateEntry(entry.id, { enabled: box.checked }, `${box.checked ? 'Enable' : 'Disable'} ${entry.id}`); report(`${entry.id} ${box.checked ? 'enabled' : 'disabled'}`); }); enabled.append(box, document.createTextNode(' Enabled'));
      panel.append(occurrences, field('Effective duration', value.effectiveDurationSeconds === null ? 'Invalid' : formatDuration(value.effectiveDurationSeconds, format)), field('Order', String(entry.order)), field('Assigned resource', value.assignedResource), field('Entry notes', entry.notes, (notes) => commands.updateEntry(entry.id, { notes }, `Edit notes for ${entry.id}`), true), enabled);
      const locate = actionButton('Locate Operation in Process Flow'); locate.disabled = !value.operation; locate.addEventListener('click', () => value.operation && locateOperation(value.operation.id)); const up = actionButton('Move Up'); up.addEventListener('click', () => commands.moveUp(entry.id)); const down = actionButton('Move Down'); down.addEventListener('click', () => commands.moveDown(entry.id)); const remove = actionButton('Remove from Study'); remove.addEventListener('click', () => { if (commands.removeEntry(entry.id)) report(`Removed ${entry.operationId} from study`); }); panel.append(locate, up, down, remove); return;
    }
    const study = selected.kind === 'standardWorkStudy' ? store.getStudy(selected.id) : store.getStudies()[0]; if (!study) { panel.append(element('p', undefined, 'Create or select a Standard Work study.')); return; }
    const entries = store.getEntries(study.id); const summary = calculateStandardWorkSummary(entries, resolver); const validation = validateStandardWork([study], entries, operations, operators.getOperators(study.id), handovers.getHandovers(study.id), resources);
    panel.append(field('Study ID', study.id), field('Name', study.name, (name) => commands.updateStudy(study.id, { name }, `Rename Standard Work study ${study.id}`)), field('Description', study.description, (description) => commands.updateStudy(study.id, { description }), true), field('Product or process', study.productOrProcessName, (productOrProcessName) => commands.updateStudy(study.id, { productOrProcessName })), field('Revision', study.revision, (revision) => commands.updateStudy(study.id, { revision })), field('Notes', study.notes, (notes) => commands.updateStudy(study.id, { notes }), true));
    const active = element('label', 'standard-work-check'); const box = element('input'); box.type = 'checkbox'; box.checked = study.active; box.addEventListener('change', () => commands.updateStudy(study.id, { active: box.checked }, `${box.checked ? 'Activate' : 'Deactivate'} ${study.id}`)); active.append(box, document.createTextNode(' Active study')); panel.append(active, field('Created UTC', study.createdUtc), field('Modified UTC', study.modifiedUtc));
    const cards = element('div', 'standard-work-summary-cards'); for (const category of summary.categories) { const card = element('section', `standard-work-summary-card standard-work-summary-card--${category.category}`); card.setAttribute('aria-label', `${category.category}: ${formatDuration(category.seconds, format)}, ${category.percentage.toFixed(1)} percent, ${category.entryCount} entries`); card.append(element('strong', undefined, category.category[0].toUpperCase() + category.category.slice(1)), element('span', undefined, formatDuration(category.seconds, format)), element('small', undefined, `${category.percentage.toFixed(1)}% · ${category.entryCount} entries`)); cards.append(card); }
    panel.append(element('h3', undefined, 'Timing summary'), cards, element('p', undefined, `Sum of included operation durations: ${formatDuration(summary.sumOfIncludedDurations, format)}`), element('p', undefined, `${summary.enabledEntryCount}/${summary.entryCount} entries enabled · ${summary.totalOccurrences} occurrences`), element('h3', undefined, 'Validation'), element('p', undefined, `${validation.errors} errors · ${validation.warnings} warnings`)); for (const issue of validation.issues.slice(0, 8)) panel.append(element('p', `standard-work-issue standard-work-issue--${issue.severity}`, `${issue.severity.toUpperCase()}: ${issue.message}`));
  };
  return { element: panel, render };
}
