import type { StandardWorkChartSchedule } from '../../../models/standardWork/StandardWorkChartModels';
import { STANDARD_WORK_CHART_INTERVAL_MODES, STANDARD_WORK_CHART_LANE_DENSITIES, type StandardWorkChartSettings } from '../../../models/standardWork/StandardWorkChartSettings';
import type { OperationStore } from '../../../services/OperationStore';
import type { ResourceStore } from '../../../services/ResourceStore';
import type { ProjectSessionService } from '../../../services/project/ProjectSessionService';
import type { CommandFactory } from '../../../services/history/CommandFactory';
import type { StandardWorkCommandFactory } from '../../../services/history/StandardWorkCommandFactory';
import type { StandardWorkSelectionStore } from '../../../services/standardWork/StandardWorkSelectionStore';
import { StandardWorkChartScheduler } from '../../../services/standardWork/StandardWorkChartScheduler';
import { fitStandardWorkPixelsPerSecond } from '../../../services/standardWork/StandardWorkChartScale';
import type { StandardWorkStore } from '../../../services/StandardWorkStore';
import { formatDuration } from '../../../services/standardWork/DurationFormatter';
import { actionButton, element } from '../../../ui/dom';
import { renderStandardWorkChart } from './StandardWorkChartRenderer';

export interface StandardWorkChartController { readonly element: HTMLElement; render(studyId: string | null): void; fit(): void; zoomIn(): void; zoomOut(): void; reveal(entryId: string): void; getSchedule(): StandardWorkChartSchedule | null; dispose(): void; }

export function createStandardWorkChart(store: StandardWorkStore, operations: OperationStore, resources: ResourceStore, selection: StandardWorkSelectionStore, commands: StandardWorkCommandFactory, projectCommands: CommandFactory, project: ProjectSessionService, locateOperation: (id: string) => void, locateResource: (id: string) => void, report: (message: string) => void): StandardWorkChartController {
  const root = element('section', 'standard-work-chart'); root.tabIndex = 0; root.setAttribute('aria-label', 'Standard Work Combination Chart');
  const toolbar = element('div', 'standard-work-chart-toolbar'); const fitButton = actionButton('Fit Chart'); const zoomOutButton = actionButton('Zoom Out'); const zoomInButton = actionButton('Zoom In'); const resetButton = actionButton('Reset Zoom'); const autoButton = actionButton('Automatic Lanes'); const disabledButton = actionButton('Disabled Entries'); const labelsButton = actionButton('Block Labels'); const settingsButton = actionButton('Chart Settings'); toolbar.append(fitButton, zoomOutButton, zoomInButton, resetButton, autoButton, disabledButton, labelsButton, settingsButton);
  const summary = element('div', 'standard-work-chart-summary'); const chartGrid = element('div', 'standard-work-chart-grid'); const empty = element('div', 'standard-work-chart-empty', 'Select a Standard Work study to calculate its Combination Chart.'); const labelsHost = element('div', 'standard-work-chart-label-host'); const scroller = element('div', 'standard-work-chart-scroll'); scroller.tabIndex = 0; scroller.setAttribute('aria-label', 'Scrollable Standard Work chart region'); chartGrid.append(labelsHost, scroller); const diagnostics = element('div', 'standard-work-chart-diagnostics'); const details = element('aside', 'standard-work-chart-details'); root.append(toolbar, summary, empty, chartGrid, diagnostics, details);
  const menu = element('div', 'resource-context-menu'); menu.hidden = true; menu.setAttribute('role', 'menu'); root.append(menu);
  const settingsDialog = element('dialog', 'standard-work-chart-settings'); const settingsForm = element('form'); settingsForm.method = 'dialog'; settingsForm.append(element('h2', undefined, 'Chart Settings')); settingsDialog.append(settingsForm); root.append(settingsDialog);
  const scheduler = new StandardWorkChartScheduler(operations, resources); const resetPixelsPerSecond = 10; let activeStudyId: string | null = null; let schedule: StandardWorkChartSchedule | null = null; let pixelsPerSecond = resetPixelsPerSecond; let userZoomed = false; let disposed = false; let selectedElement: SVGGElement | null = null;
  const currentSettings = (): StandardWorkChartSettings => project.getSettings().standardWork.chart;
  const persistSettings = (patch: Partial<StandardWorkChartSettings>, description: string): void => { const standardWork = project.getSettings().standardWork; const chart = { ...standardWork.chart, ...patch }; if (projectCommands.updateProjectSettings({ standardWork: { ...standardWork, chart } })) report(description); };
  const setZoom = (next: number, message = true): void => { pixelsPerSecond = Math.min(resetPixelsPerSecond * 8, Math.max(resetPixelsPerSecond * .25, next)); userZoomed = true; render(activeStudyId); if (message) report(`Chart zoom: ${Math.round(pixelsPerSecond / resetPixelsPerSecond * 100)}%`); };
  const fit = (): void => { if (!schedule) return; pixelsPerSecond = fitStandardWorkPixelsPerSecond(schedule.chartCycleSpanSeconds, Math.max(320, scroller.clientWidth)); userZoomed = false; scroller.scrollLeft = 0; render(activeStudyId); report('Chart fitted to study'); };
  const reveal = (entryId: string): void => { requestAnimationFrame(() => { const target = scroller.querySelector<SVGGElement>(`[data-entry-id="${CSS.escape(entryId)}"]`); if (!target) return; const rect = target.getBoundingClientRect(); const view = scroller.getBoundingClientRect(); if (rect.left < view.left || rect.right > view.right) target.scrollIntoView({ inline: 'center', block: 'nearest' }); }); };
  const selectEntry = (entryId: string): void => { selection.select({ kind: 'standardWorkEntry', id: entryId }); const block = schedule ? [...schedule.operatorBlocks, ...schedule.automaticBlocks].find((item) => item.entryId === entryId) : undefined; if (block) report(`Selected ${block.operationId} from ${formatDuration(block.startSeconds, project.getSettings().standardWork.timeFormat)} to ${formatDuration(block.endSeconds, project.getSettings().standardWork.timeFormat)}`); };
  const closeMenu = (): void => { menu.hidden = true; menu.replaceChildren(); };
  const showMenu = (event: MouseEvent, entryId: string): void => { event.preventDefault(); event.stopPropagation(); const entry = store.getEntry(entryId); if (!entry) return; selectEntry(entryId); closeMenu(); const add = (label: string, action: () => void, disabled = false): void => { const button = actionButton(label, 'resource-context-menu__item'); button.disabled = disabled; button.setAttribute('role', 'menuitem'); button.addEventListener('click', () => { action(); closeMenu(); }); menu.append(button); }; const operation = operations.getOperation(entry.operationId); add('Locate Entry in Table', () => reveal(entryId)); add('Locate Operation in Process Flow', () => locateOperation(entry.operationId), !operation); add('Edit Operation Properties', () => locateOperation(entry.operationId), !operation); add(entry.enabled ? 'Disable Entry' : 'Enable Entry', () => commands.updateEntry(entry.id, { enabled: !entry.enabled }, `${entry.enabled ? 'Disable' : 'Enable'} ${entry.id}`)); add('Move Entry Up', () => commands.moveUp(entry.id)); add('Move Entry Down', () => commands.moveDown(entry.id)); add('Remove from Study', () => commands.removeEntry(entry.id)); if (operation?.timingCategory === 'automatic') add('Locate Assigned Resource in Factory Layout', () => operation.assignedResourceId && locateResource(operation.assignedResourceId), !operation.assignedResourceId); add('Properties', () => selection.select({ kind: 'standardWorkEntry', id: entry.id })); const bounds = root.getBoundingClientRect(); menu.style.left = `${Math.min(event.clientX - bounds.left, root.clientWidth - 230)}px`; menu.style.top = `${Math.min(event.clientY - bounds.top, root.clientHeight - 280)}px`; menu.hidden = false; };
  const renderSummary = (): void => { summary.replaceChildren(); diagnostics.replaceChildren(); details.replaceChildren(); if (!schedule) return; const value = schedule.summary; const format = project.getSettings().standardWork.timeFormat; const items = [['Entries', String(value.enabledEntryCount)], ['Manual', formatDuration(value.manualSeconds, format)], ['Walking', formatDuration(value.walkingSeconds, format)], ['Waiting', formatDuration(value.waitingSeconds, format)], ['Automatic total', formatDuration(value.automaticSeconds, format)], ['Operator occupied', formatDuration(value.operatorOccupiedSeconds, format)], ['Operator sequence end', formatDuration(value.operatorEndSeconds, format)], ['Latest automatic', formatDuration(value.latestAutomaticEndSeconds, format)], ['Automatic overrun', formatDuration(value.automaticOverrunSeconds, format)], ['Chart cycle span', formatDuration(value.chartCycleSpanSeconds, format)]]; for (const [name, result] of items) { const card = element('div', 'standard-work-chart-metric'); card.append(element('small', undefined, name), element('strong', undefined, result)); summary.append(card); } summary.title = 'Automatic total is the sum of Automatic block durations. It is not added to operator occupied time and may differ from chart cycle span.';
    if (schedule.diagnostics.length) { diagnostics.append(element('h3', undefined, `Chart diagnostics · ${value.errorCount} errors · ${value.warningCount} warnings`)); for (const issue of schedule.diagnostics.slice(0, 12)) diagnostics.append(element('p', `standard-work-issue standard-work-issue--${issue.severity === 'error' ? 'error' : issue.severity === 'warning' ? 'warning' : 'information'}`, `${issue.severity.toUpperCase()}: ${issue.message}`)); if (value.potentialOverlapCount) diagnostics.append(element('p', 'standard-work-capacity-disclaimer', 'Potential overlap based on the current Standard Work chart. Full resource capacity and double-booking validation is planned for Sprint 3.6.')); }
    const selected = selection.get(); if (selected.kind === 'standardWorkEntry') { const block = [...schedule.operatorBlocks, ...schedule.automaticBlocks].find((item) => item.entryId === selected.id); const entry = store.getEntry(selected.id); const operation = entry ? operations.getOperation(entry.operationId) : undefined; if (block && entry) { details.append(element('h3', undefined, 'Chart Timing Details')); for (const [name, result] of [['Entry', block.entryId], ['Operation', `${block.operationId} — ${operation?.name ?? 'Missing'}`], ['Category', block.timingCategory], ['Study order', String(block.order)], ['Start', formatDuration(block.startSeconds, format)], ['End', formatDuration(block.endSeconds, format)], ['Duration', formatDuration(block.durationSeconds, format)], ['Occurrences', String(block.occurrences)], ['Lane', block.laneId], ['Assigned resource', block.assignedResourceId ?? 'Unassigned'], ['Same-resource overlap', block.overlapsSameResource ? 'Potential overlap' : 'No overlap detected']]) details.append(element('p', undefined, `${name}: ${result}`)); } }
  };
  const render = (studyId: string | null): void => { if (disposed) return; activeStudyId = studyId; const study = studyId ? store.getStudy(studyId) : undefined; schedule = study ? scheduler.calculate(study, store.getEntries(study.id)) : null; empty.hidden = Boolean(schedule); chartGrid.hidden = !schedule; fitButton.disabled = !schedule || schedule.chartCycleSpanSeconds <= 0; zoomInButton.disabled = !schedule; zoomOutButton.disabled = !schedule; resetButton.disabled = !schedule; if (!schedule) { labelsHost.replaceChildren(); scroller.replaceChildren(); renderSummary(); return; } if (!userZoomed && pixelsPerSecond === 10 && schedule.chartCycleSpanSeconds > 0 && scroller.clientWidth > 0) pixelsPerSecond = fitStandardWorkPixelsPerSecond(schedule.chartCycleSpanSeconds, scroller.clientWidth); const selected = selection.get(); const rendered = renderStandardWorkChart({ schedule, operations, settings: currentSettings(), timeFormat: project.getSettings().standardWork.timeFormat, pixelsPerSecond, selectedEntryId: selected.kind === 'standardWorkEntry' ? selected.id : null, viewportWidth: Math.max(360, scroller.clientWidth), onSelect: selectEntry, onContextMenu: showMenu }); labelsHost.replaceChildren(rendered.labels); scroller.replaceChildren(rendered.drawing); selectedElement = selected.kind === 'standardWorkEntry' ? rendered.blockElements.get(selected.id) ?? null : null; renderSummary(); autoButton.setAttribute('aria-pressed', String(currentSettings().showAutomaticLanes)); disabledButton.setAttribute('aria-pressed', String(currentSettings().showDisabledEntries)); labelsButton.setAttribute('aria-pressed', String(currentSettings().showOperationNames || currentSettings().showOperationIds || currentSettings().showDurations)); if (selected.kind === 'standardWorkEntry') reveal(selected.id); };
  const openSettings = (): void => { const settings = currentSettings(); settingsForm.replaceChildren(element('h2', undefined, 'Chart Settings')); const controls: Array<[keyof StandardWorkChartSettings, string, 'checkbox' | 'number' | 'select']> = [['intervalMode', 'Time-axis interval mode', 'select'], ['fixedMajorIntervalSeconds', 'Fixed major interval (seconds)', 'number'], ['minorSubdivisions', 'Minor subdivisions', 'number'], ['showMinorGrid', 'Show minor grid', 'checkbox'], ['showOperationIds', 'Show operation IDs', 'checkbox'], ['showOperationNames', 'Show operation names', 'checkbox'], ['showDurations', 'Show durations', 'checkbox'], ['showStartEndValues', 'Show start and end values', 'checkbox'], ['showAutomaticLaunchMarkers', 'Show automatic launch markers', 'checkbox'], ['showLaneIds', 'Show lane IDs', 'checkbox'], ['showAutomaticLanes', 'Show automatic lanes', 'checkbox'], ['showDisabledEntries', 'Show disabled entries', 'checkbox'], ['laneDensity', 'Lane density', 'select']]; const inputs = new Map<keyof StandardWorkChartSettings, HTMLInputElement | HTMLSelectElement>(); for (const [key, labelText, kind] of controls) { const label = element('label', 'standard-work-field'); label.append(element('span', undefined, labelText)); let input: HTMLInputElement | HTMLSelectElement; if (kind === 'select') { input = element('select'); const values = key === 'intervalMode' ? STANDARD_WORK_CHART_INTERVAL_MODES : STANDARD_WORK_CHART_LANE_DENSITIES; for (const value of values) { const option = element('option', undefined, value[0].toUpperCase() + value.slice(1)); option.value = value; input.append(option); } input.value = String(settings[key]); } else { input = element('input'); input.type = kind; if (kind === 'checkbox') input.checked = Boolean(settings[key]); else { input.value = String(settings[key]); input.min = key === 'minorSubdivisions' ? '1' : '0.001'; input.max = key === 'minorSubdivisions' ? '10' : '1000000'; } } inputs.set(key, input); label.append(input); settingsForm.append(label); } const actions = element('div', 'standard-work-chart-settings-actions'); const cancel = actionButton('Cancel'); cancel.value = 'cancel'; cancel.addEventListener('click', () => settingsDialog.close()); const apply = actionButton('Apply Chart Settings'); apply.addEventListener('click', () => { const next = { ...settings }; for (const [key, input] of inputs) { const current = next[key]; (next as unknown as Record<string, unknown>)[key] = input instanceof HTMLInputElement && input.type === 'checkbox' ? input.checked : typeof current === 'number' ? Number(input.value) : input.value; } persistSettings(next, 'Standard Work chart settings changed'); settingsDialog.close(); }); actions.append(cancel, apply); settingsForm.append(actions); settingsDialog.showModal(); };
  fitButton.addEventListener('click', fit); zoomInButton.addEventListener('click', () => setZoom(pixelsPerSecond * 1.25)); zoomOutButton.addEventListener('click', () => setZoom(pixelsPerSecond / 1.25)); resetButton.addEventListener('click', () => setZoom(resetPixelsPerSecond)); autoButton.addEventListener('click', () => persistSettings({ showAutomaticLanes: !currentSettings().showAutomaticLanes }, 'Automatic lanes toggled')); disabledButton.addEventListener('click', () => persistSettings({ showDisabledEntries: !currentSettings().showDisabledEntries }, 'Disabled-entry display toggled')); labelsButton.addEventListener('click', () => { const show = !(currentSettings().showOperationIds || currentSettings().showOperationNames || currentSettings().showDurations); persistSettings({ showOperationIds: show, showOperationNames: show, showDurations: show }, 'Chart block labels toggled'); }); settingsButton.addEventListener('click', openSettings);
  scroller.addEventListener('wheel', (event) => { if (event.ctrlKey || event.metaKey) { event.preventDefault(); setZoom(pixelsPerSecond * (event.deltaY < 0 ? 1.1 : 1 / 1.1), false); } else if (event.shiftKey) { event.preventDefault(); scroller.scrollLeft += event.deltaY; } }, { passive: false });
  scroller.addEventListener('scroll', () => { labelsHost.scrollTop = scroller.scrollTop; });
  root.addEventListener('keydown', (event) => { if (event.target instanceof HTMLElement && event.target.closest('input,textarea,select,[contenteditable="true"]')) return; const blocks = schedule ? [...schedule.operatorBlocks, ...schedule.automaticBlocks].sort((a, b) => a.startSeconds - b.startSeconds || a.entryId.localeCompare(b.entryId)) : []; const selected = selection.get(); const index = selected.kind === 'standardWorkEntry' ? blocks.findIndex((block) => block.entryId === selected.id) : -1; if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') { event.preventDefault(); const next = blocks[Math.min(blocks.length - 1, Math.max(0, index + (event.key === 'ArrowLeft' ? -1 : 1)))]; if (next) selectEntry(next.entryId); } else if (event.key === 'Home') { event.preventDefault(); scroller.scrollLeft = 0; } else if (event.key === 'End') { event.preventDefault(); scroller.scrollLeft = scroller.scrollWidth; } else if (event.key === '+' || event.key === '=') { event.preventDefault(); setZoom(pixelsPerSecond * 1.25); } else if (event.key === '-') { event.preventDefault(); setZoom(pixelsPerSecond / 1.25); } else if (event.key === '0') { event.preventDefault(); fit(); } else if (event.key === 'Enter' && selectedElement) { event.preventDefault(); selectedElement.focus(); } });
  const outside = (event: PointerEvent): void => { if (!menu.hidden && event.target instanceof Node && !menu.contains(event.target)) closeMenu(); }; document.addEventListener('pointerdown', outside, true);
  return { element: root, render, fit, zoomIn: () => setZoom(pixelsPerSecond * 1.25), zoomOut: () => setZoom(pixelsPerSecond / 1.25), reveal, getSchedule: () => schedule, dispose: () => { disposed = true; document.removeEventListener('pointerdown', outside, true); closeMenu(); settingsDialog.close(); } };
}
