import { revealOperation } from '../../../core/events/operationEvents';
import { revealResource } from '../../../core/events/resourceEvents';
import { STANDARD_WORK_ADD_OPERATION_EVENT, STANDARD_WORK_REVEAL_EVENT, STANDARD_WORK_SHOW_OPERATION_EVENT } from '../../../core/events/standardWorkEvents';
import { reportStatus } from '../../../core/events/uiEvents';
import { STANDARD_WORK_TIME_FORMATS, type StandardWorkTimeFormat } from '../../../models/standardWork/StandardWork';
import type { SelectionController } from '../../../models/selection/Selection';
import type { OperationStore } from '../../../services/OperationStore';
import type { ResourceStore } from '../../../services/ResourceStore';
import type { ProjectSessionService } from '../../../services/project/ProjectSessionService';
import type { StandardWorkStore } from '../../../services/StandardWorkStore';
import type { WorkspaceStore } from '../../../services/WorkspaceStore';
import type { CommandFactory } from '../../../services/history/CommandFactory';
import type { StandardWorkCommandFactory } from '../../../services/history/StandardWorkCommandFactory';
import type { StandardWorkOperationResolver } from '../../../services/standardWork/StandardWorkOperationResolver';
import type { StandardWorkSelectionStore } from '../../../services/standardWork/StandardWorkSelectionStore';
import { actionButton, element } from '../../../ui/dom';
import { createStandardWorkProperties } from './StandardWorkProperties';
import { createStandardWorkTable } from './StandardWorkTable';
import { createStandardWorkChart } from './StandardWorkChart';

export interface StandardWorkWorkspaceController { readonly element: HTMLElement; focus(): void; dispose(): void; }

export function createStandardWorkWorkspace(store: StandardWorkStore, operations: OperationStore, resources: ResourceStore, resolver: StandardWorkOperationResolver, selection: StandardWorkSelectionStore, commands: StandardWorkCommandFactory, projectCommands: CommandFactory, project: ProjectSessionService, workspaces: WorkspaceStore, canvasSelection: SelectionController): StandardWorkWorkspaceController {
  const root = element('section', 'standard-work-workspace'); root.tabIndex = 0; root.setAttribute('aria-label', 'Standard Work engineering workspace');
  const left = element('aside', 'standard-work-navigator'); const studies = element('div', 'standard-work-study-list'); studies.setAttribute('role', 'listbox'); studies.setAttribute('aria-label', 'Standard Work studies'); const available = element('div', 'standard-work-operation-list'); available.setAttribute('role', 'listbox'); available.setAttribute('aria-label', 'Available Process Flow operations');
  const topCommands = element('div', 'standard-work-command-row'); const newStudy = actionButton('New Study'); const duplicate = actionButton('Duplicate Study'); const deleteStudy = actionButton('Delete Study'); const populate = actionButton('Populate from Process Flow'); const add = actionButton('Add Operation'); topCommands.append(newStudy, duplicate, deleteStudy, populate, add);
  const formatLabel = element('label', 'standard-work-format'); formatLabel.append(document.createTextNode('Time display ')); const format = element('select'); for (const value of STANDARD_WORK_TIME_FORMATS) { const choice = element('option', undefined, value === 'seconds' ? 'Seconds' : value === 'minutesSeconds' ? 'mm:ss' : 'hh:mm:ss'); choice.value = value; format.append(choice); } formatLabel.append(format);
  left.append(element('h2', undefined, 'Studies'), topCommands, studies, element('h2', undefined, 'Available Process Flow operations'), available, formatLabel);
  let availableOperationId: string | null = null;
  const activeStudyId = (): string | null => { const current = selection.get(); if (current.kind === 'standardWorkStudy') return store.getStudy(current.id)?.id ?? null; if (current.kind === 'standardWorkEntry') return store.getEntry(current.id)?.studyId ?? null; return store.getStudies()[0]?.id ?? null; };
  const table = createStandardWorkTable(resolver, selection, (id, beforeId) => { if (commands.moveBefore(id, beforeId)) reportStatus('Reordered Standard Work entry'); });
  const locate = (id: string): void => { workspaces.activate('processFlow'); canvasSelection.select({ kind: 'operation', id }); revealOperation(id); reportStatus(`Located ${id} in Process Flow`); };
  const locateResource = (id: string): void => { workspaces.activate('factoryLayout'); canvasSelection.select({ kind: 'resource', id }); revealResource(id); reportStatus(`Located ${id} in Factory Layout`); };
  const properties = createStandardWorkProperties(store, operations, resolver, selection, commands, locate, reportStatus);
  const chart = createStandardWorkChart(store, operations, resources, selection, commands, projectCommands, project, locate, locateResource, reportStatus);
  type StandardWorkView = 'table' | 'chart' | 'split'; let activeView: StandardWorkView = 'split'; let chartHasSized = false;
  const centre = element('div', 'standard-work-centre'); const viewCommands = element('div', 'standard-work-view-commands'); const tableView = actionButton('Entry Table'); const chartView = actionButton('Combination Chart'); const splitView = actionButton('Split View'); viewCommands.append(tableView, chartView, splitView); const views = element('div', 'standard-work-views'); views.append(table.element, chart.element); centre.append(viewCommands, views);
  const fitChartOnce = (): void => { if (!chartHasSized && chart.getSchedule()) { chart.fit(); chartHasSized = true; } };
  const setView = (view: StandardWorkView): void => { activeView = view; views.dataset.view = view; table.element.hidden = view === 'chart'; chart.element.hidden = view === 'table'; tableView.setAttribute('aria-pressed', String(view === 'table')); chartView.setAttribute('aria-pressed', String(view === 'chart')); splitView.setAttribute('aria-pressed', String(view === 'split')); if (view !== 'table') requestAnimationFrame(fitChartOnce); reportStatus(view === 'table' ? 'Entry Table view' : view === 'chart' ? 'Combination Chart view' : 'Split View'); };
  tableView.addEventListener('click', () => setView('table')); chartView.addEventListener('click', () => setView('chart')); splitView.addEventListener('click', () => setView('split'));
  const menu = element('div', 'resource-context-menu'); menu.hidden = true; menu.setAttribute('role', 'menu'); root.append(left, centre, properties.element, menu);
  const addSelected = (): void => { const studyId = activeStudyId(); if (!studyId) { reportStatus('Create or select a Standard Work study first'); return; } if (!availableOperationId) { reportStatus('Select an available Process Flow operation'); return; } const result = commands.addOperation(studyId, availableOperationId); reportStatus(result.kind === 'added' ? `Added ${availableOperationId} to ${studyId}` : result.kind === 'duplicate' ? `${availableOperationId} is already in this study` : 'Operation could not be added'); };
  newStudy.addEventListener('click', () => { const study = commands.createStudy(); if (study) reportStatus(`Standard Work Study created: ${study.id}`); });
  duplicate.addEventListener('click', () => { const id = activeStudyId(); const result = id ? commands.duplicateStudy(id) : null; reportStatus(result ? `Study duplicated: ${result.id}` : 'Select a study to duplicate'); });
  deleteStudy.addEventListener('click', () => { const id = activeStudyId(); if (!id) return; const count = store.getEntries(id).length; if (count && !window.confirm(`Delete ${id} and its ${count} Standard Work entries?`)) return; if (commands.deleteStudy(id)) reportStatus(`Deleted Standard Work study ${id}`); });
  populate.addEventListener('click', () => { const id = activeStudyId(); if (!id) { reportStatus('Select a study to populate'); return; } const created = commands.populate(id); reportStatus(created.length ? `Added ${created.length} operations from Process Flow` : 'Study already contains every Process Flow operation'); }); add.addEventListener('click', addSelected);
  format.addEventListener('change', () => { const value = format.value as StandardWorkTimeFormat; if (projectCommands.updateProjectSettings({ standardWork: { ...project.getSettings().standardWork, timeFormat: value } })) reportStatus(`Standard Work time display changed to ${format.selectedOptions[0]?.textContent}`); });
  const render = (): void => {
    const selected = selection.get(); const studyId = activeStudyId(); studies.replaceChildren();
    for (const study of store.getStudies()) { const entries = store.getEntries(study.id); const button = actionButton(`${study.id} — ${study.name} · ${entries.length} entries${study.active ? '' : ' · Inactive'}`, `standard-work-list-button${study.active ? '' : ' standard-work-list-button--inactive'}`); button.dataset.studyId = study.id; button.setAttribute('role', 'option'); button.setAttribute('aria-selected', String(selected.kind === 'standardWorkStudy' && selected.id === study.id)); button.addEventListener('click', () => selection.select({ kind: 'standardWorkStudy', id: study.id })); studies.append(button); }
    if (!store.getStudies().length) studies.append(element('p', undefined, 'No Standard Work studies'));
    available.replaceChildren(); for (const operation of operations.sortedOperations()) { const button = actionButton(`OP ${operation.sequence} — ${operation.name} · ${operation.timingCategory} · ${operation.cycleTimeSeconds}s`, `standard-work-list-button${availableOperationId === operation.id ? ' standard-work-list-button--selected' : ''}`); button.setAttribute('role', 'option'); button.setAttribute('aria-selected', String(availableOperationId === operation.id)); button.addEventListener('click', () => { availableOperationId = operation.id; render(); }); button.addEventListener('dblclick', addSelected); available.append(button); }
    if (!operations.getOperationCount()) available.append(element('p', undefined, 'No Process Flow operations'));
    const timeFormat = project.getSettings().standardWork.timeFormat; format.value = timeFormat; const entries = studyId ? store.getEntries(studyId) : []; table.render(entries, timeFormat); chart.render(studyId); properties.render(timeFormat); duplicate.disabled = !studyId; deleteStudy.disabled = !studyId; populate.disabled = !studyId; add.disabled = !studyId || !availableOperationId;
    if (selected.kind === 'standardWorkEntry') requestAnimationFrame(() => { table.reveal(selected.id); chart.reveal(selected.id); });
  };
  const editable = (target: EventTarget | null): boolean => target instanceof HTMLElement && Boolean(target.closest('input, textarea, select, [contenteditable="true"]'));
  const keydown = (event: KeyboardEvent): void => { if (workspaces.getActive() !== 'standardWork' || editable(event.target)) return; const current = selection.get(); if (event.key === 'Insert') { event.preventDefault(); addSelected(); } else if (event.key === 'Escape') { selection.clear(); reportStatus('Standard Work selection cleared'); } else if (current.kind === 'standardWorkEntry' && event.altKey && event.key === 'ArrowUp') { event.preventDefault(); commands.moveUp(current.id); } else if (current.kind === 'standardWorkEntry' && event.altKey && event.key === 'ArrowDown') { event.preventDefault(); commands.moveDown(current.id); } else if (current.kind === 'standardWorkEntry' && (event.ctrlKey || event.metaKey) && event.key === 'Home') { event.preventDefault(); commands.moveToTop(current.id); } else if (current.kind === 'standardWorkEntry' && (event.ctrlKey || event.metaKey) && event.key === 'End') { event.preventDefault(); commands.moveToBottom(current.id); } else if (event.key === 'Delete' && current.kind === 'standardWorkEntry') { event.preventDefault(); commands.removeEntry(current.id); } else if (event.key === 'Delete' && current.kind === 'standardWorkStudy') { event.preventDefault(); const count = store.getEntries(current.id).length; if (!count || window.confirm(`Delete ${current.id} and its ${count} entries?`)) commands.deleteStudy(current.id); } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'd' && current.kind === 'standardWorkStudy') { event.preventDefault(); commands.duplicateStudy(current.id); } };
  const reveal = (event: Event): void => { const detail = (event as CustomEvent<{ kind: 'standardWorkStudy' | 'standardWorkEntry'; id: string }>).detail; workspaces.activate('standardWork'); selection.select(detail); if (activeView === 'table') setView('split'); requestAnimationFrame(() => { if (detail.kind === 'standardWorkEntry') { table.reveal(detail.id); chart.reveal(detail.id); } }); };
  const addRequested = (event: Event): void => { const operationId = (event as CustomEvent<string>).detail; const studyId = activeStudyId(); if (!studyId) { reportStatus('Create or select a Standard Work study first'); return; } const result = commands.addOperation(studyId, operationId); reportStatus(result.kind === 'added' ? `Added ${operationId} to ${studyId}` : result.kind === 'duplicate' ? `${operationId} is already in this study` : 'Operation could not be added'); };
  const showRequested = (event: Event): void => { const operationId = (event as CustomEvent<string>).detail; const entry = store.getEntriesForOperation(operationId)[0]; if (!entry) { reportStatus(`${operationId} is not used by any Standard Work study`); return; } workspaces.activate('standardWork'); selection.select({ kind: 'standardWorkEntry', id: entry.id }); reportStatus(`Showing ${operationId} in ${entry.studyId}`); };
  const closeMenu = (): void => { menu.hidden = true; menu.replaceChildren(); };
  const contextMenu = (event: MouseEvent): void => { const target = event.target instanceof Element ? event.target : null; const entryId = target?.closest<HTMLElement>('[data-entry-id]')?.dataset.entryId; const studyId = target?.closest<HTMLElement>('[data-study-id]')?.dataset.studyId; if (!entryId && !studyId) return; event.preventDefault(); closeMenu(); const addItem = (label: string, action: () => void, disabled = false): void => { const button = actionButton(label, 'resource-context-menu__item'); button.disabled = disabled; button.setAttribute('role', 'menuitem'); button.addEventListener('click', () => { action(); closeMenu(); }); menu.append(button); };
    if (entryId) { const entry = store.getEntry(entryId); if (!entry) return; selection.select({ kind: 'standardWorkEntry', id: entryId }); addItem('Locate Operation in Process Flow', () => locate(entry.operationId)); addItem(entry.enabled ? 'Disable' : 'Enable', () => commands.updateEntry(entryId, { enabled: !entry.enabled }, `${entry.enabled ? 'Disable' : 'Enable'} ${entryId}`)); addItem('Move Up', () => commands.moveUp(entryId)); addItem('Move Down', () => commands.moveDown(entryId)); addItem('Move to Top', () => commands.moveToTop(entryId)); addItem('Move to Bottom', () => commands.moveToBottom(entryId)); addItem('Remove from Study', () => commands.removeEntry(entryId)); addItem('Properties', () => selection.select({ kind: 'standardWorkEntry', id: entryId })); }
    if (studyId) { const study = store.getStudy(studyId); if (!study) return; selection.select({ kind: 'standardWorkStudy', id: studyId }); addItem('Rename', () => { const name = window.prompt('Study name', study.name); if (name !== null) commands.updateStudy(studyId, { name }, `Rename Standard Work study ${studyId}`); }); addItem('Populate from Process Flow', () => commands.populate(studyId)); addItem('Duplicate', () => { commands.duplicateStudy(studyId); }); addItem(study.active ? 'Deactivate' : 'Activate', () => commands.updateStudy(studyId, { active: !study.active }, `${study.active ? 'Deactivate' : 'Activate'} ${studyId}`)); addItem('Delete', () => { const count = store.getEntries(studyId).length; if (!count || window.confirm(`Delete ${studyId} and its ${count} entries?`)) commands.deleteStudy(studyId); }); addItem('Properties', () => selection.select({ kind: 'standardWorkStudy', id: studyId })); }
    const bounds = root.getBoundingClientRect(); menu.style.left = `${Math.min(event.clientX - bounds.left, Math.max(0, root.clientWidth - 210))}px`; menu.style.top = `${Math.min(event.clientY - bounds.top, Math.max(0, root.clientHeight - 300))}px`; menu.hidden = false; };
  const outsideMenu = (event: PointerEvent): void => { if (!menu.hidden && event.target instanceof Node && !menu.contains(event.target)) closeMenu(); };
  document.addEventListener('keydown', keydown); document.addEventListener(STANDARD_WORK_REVEAL_EVENT, reveal); document.addEventListener(STANDARD_WORK_ADD_OPERATION_EVENT, addRequested); document.addEventListener(STANDARD_WORK_SHOW_OPERATION_EVENT, showRequested); document.addEventListener('pointerdown', outsideMenu, true); root.addEventListener('contextmenu', contextMenu); const unsubscribers = [store.subscribe((change) => { if (change.kind === 'reset') chartHasSized = false; render(); }), operations.subscribe(render), resources.subscribe(render), selection.subscribe(render), project.subscribe(render), workspaces.subscribe((active) => { if (active === 'standardWork' && activeView !== 'table') requestAnimationFrame(fitChartOnce); })]; setView(activeView); render();
  return { element: root, focus: () => root.focus({ preventScroll: true }), dispose: () => { unsubscribers.forEach((unsubscribe) => unsubscribe()); document.removeEventListener('keydown', keydown); document.removeEventListener(STANDARD_WORK_REVEAL_EVENT, reveal); document.removeEventListener(STANDARD_WORK_ADD_OPERATION_EVENT, addRequested); document.removeEventListener(STANDARD_WORK_SHOW_OPERATION_EVENT, showRequested); document.removeEventListener('pointerdown', outsideMenu, true); root.removeEventListener('contextmenu', contextMenu); table.dispose(); chart.dispose(); } };
}
