import { cloneFactoryRoute, type FactoryRoute, type FactoryRouteEndpoint } from '../../../models/factory/FactoryRoute';
import type { SelectionController } from '../../../models/selection/Selection';
import type { ApplicationClipboardService } from '../../../services/editing/ApplicationClipboardService';
import type { FactoryRouteStore } from '../../../services/FactoryRouteStore';
import type { FactoryStructureStore } from '../../../services/FactoryStructureStore';
import type { ResourceStore } from '../../../services/ResourceStore';
import { nearestRectangleAnchor } from '../../../services/factoryRoutes/FactoryRouteEndpointResolver';
import { resolveFactoryRoutePolyline } from '../../../services/geometry/FactoryRouteGeometry';
import type { GeometryPoint } from '../../../services/geometry/FactoryFootprintGeometry';
import type { FactoryRouteCommandFactory } from '../../../services/history/FactoryRouteCommandFactory';
import type { SnapService } from '../../../services/SnapService';
import type { CanvasState } from '../../../models/canvas/CanvasState';
import { screenToWorld } from '../canvas/ViewportTransform';

const SVG_NAMESPACE = 'http://www.w3.org/2000/svg';
const svg = <K extends keyof SVGElementTagNameMap>(tag: K): SVGElementTagNameMap[K] => document.createElementNS(SVG_NAMESPACE, tag);

type RouteHandle = { readonly kind: 'source' } | { readonly kind: 'target' } | { readonly kind: 'waypoint'; readonly index: number };
interface ActiveEdit { readonly pointerId: number; readonly routeId: string; readonly handle: RouteHandle; readonly original: FactoryRoute; final: FactoryRoute; }

export class FactoryRouteEditController {
  private active: ActiveEdit | null = null;
  private selectedWaypointIndex: number | null = null;
  private readonly menu = document.createElement('div');
  private readonly unsubscribers: (() => void)[];

  public constructor(private readonly viewport: HTMLElement, private readonly state: CanvasState, private readonly snap: SnapService, private readonly routes: FactoryRouteStore, private readonly resources: ResourceStore, private readonly structure: FactoryStructureStore, private readonly selection: SelectionController, private readonly commands: FactoryRouteCommandFactory, private readonly editing: ApplicationClipboardService, private readonly layer: SVGGElement, private readonly onStatus: (message: string) => void) {
    this.menu.className = 'resource-context-menu'; this.menu.setAttribute('role', 'menu'); this.menu.hidden = true; viewport.append(this.menu);
    viewport.addEventListener('pointerdown', this.pointerDown, true); viewport.addEventListener('pointermove', this.pointerMove, true); viewport.addEventListener('pointerup', this.pointerUp, true); viewport.addEventListener('pointercancel', this.pointerCancel, true); viewport.addEventListener('contextmenu', this.contextMenu); document.addEventListener('keydown', this.keyDown); document.addEventListener('pointerdown', this.outsideMenu, true);
    this.unsubscribers = [routes.subscribe(this.render), resources.subscribe(this.render), structure.subscribe(this.render), selection.subscribe(this.render)]; this.render();
  }

  public cancel(report = false): void { if (this.active) { this.routes.updateRoute(this.active.routeId, this.active.original); if (this.viewport.hasPointerCapture(this.active.pointerId)) this.viewport.releasePointerCapture(this.active.pointerId); this.active = null; if (report) this.onStatus('Route edit cancelled'); } this.render(); }
  public viewportChanged(): void { this.render(); }
  public reverseSelected(): boolean { const route = this.selectedRoute(); if (!route) { this.onStatus('Select one route to reverse'); return false; } if (route.locked) { this.onStatus('Route is locked'); return false; } const ok = this.commands.reverseRoute(route.id); this.onStatus(ok ? `Route reversed: ${route.id}` : 'Route could not be reversed'); return ok; }
  public insertWaypoint(): boolean {
    const route = this.selectedRoute(); if (!route || route.locked) { this.onStatus(route?.locked ? 'Route is locked' : 'Select one route to insert a waypoint'); return false; }
    const resolved = this.resolve(route); if (resolved.length < 2) return false; let index = 1; let longest = -1; for (let current = 1; current < resolved.length; current += 1) { const length = Math.abs(resolved[current].x - resolved[current - 1].x) + Math.abs(resolved[current].y - resolved[current - 1].y); if (length > longest) { longest = length; index = current; } }
    const start = resolved[index - 1]; const end = resolved[index]; const offset = this.snap.interval; const detour = start.y === end.y ? [{ x: (start.x + end.x) / 2, y: start.y }, { x: (start.x + end.x) / 2, y: start.y + offset }, { x: end.x, y: start.y + offset }] : [{ x: start.x, y: (start.y + end.y) / 2 }, { x: start.x + offset, y: (start.y + end.y) / 2 }, { x: start.x + offset, y: end.y }];
    const waypoints = [...resolved.slice(1, index), ...detour, ...resolved.slice(index, -1)]; const ok = this.commands.updateRoute(route.id, { waypoints }, `Insert waypoint in ${route.id}`); this.onStatus(ok ? `Waypoint inserted in ${route.id}` : 'Waypoint could not be inserted'); return ok;
  }
  public deleteWaypoint(): boolean { const route = this.selectedRoute(); if (!route || route.locked || !route.waypoints.length) { this.onStatus(route?.locked ? 'Route is locked' : 'Select a route waypoint to delete'); return false; } const index = Math.max(0, Math.min(route.waypoints.length - 1, this.selectedWaypointIndex ?? route.waypoints.length - 1)); const waypoints = route.waypoints.filter((_, candidate) => candidate !== index); const ok = this.commands.updateRoute(route.id, { waypoints }, `Delete waypoint from ${route.id}`); this.selectedWaypointIndex = null; this.onStatus(ok ? `Waypoint deleted from ${route.id}` : 'Waypoint could not be deleted'); return ok; }
  public dispose(): void { this.cancel(false); this.unsubscribers.forEach((unsubscribe) => unsubscribe()); this.viewport.removeEventListener('pointerdown', this.pointerDown, true); this.viewport.removeEventListener('pointermove', this.pointerMove, true); this.viewport.removeEventListener('pointerup', this.pointerUp, true); this.viewport.removeEventListener('pointercancel', this.pointerCancel, true); this.viewport.removeEventListener('contextmenu', this.contextMenu); document.removeEventListener('keydown', this.keyDown); document.removeEventListener('pointerdown', this.outsideMenu, true); this.menu.remove(); }

  private readonly pointerDown = (event: PointerEvent): void => { if (this.state.tool !== 'select' || event.button !== 0) return; const handleNode = (event.target as Element | null)?.closest<SVGElement>('[data-route-handle]'); if (!handleNode) return; const route = this.selectedRoute(); if (!route) return; event.preventDefault(); event.stopImmediatePropagation(); if (route.locked) { this.onStatus('Route is locked'); return; } const value = handleNode.dataset.routeHandle!; const handle: RouteHandle = value.startsWith('waypoint:') ? { kind: 'waypoint', index: Number(value.split(':')[1]) } : { kind: value as 'source' | 'target' }; if (handle.kind === 'waypoint') this.selectedWaypointIndex = handle.index; this.active = { pointerId: event.pointerId, routeId: route.id, handle, original: cloneFactoryRoute(route), final: cloneFactoryRoute(route) }; this.viewport.setPointerCapture(event.pointerId); };
  private readonly pointerMove = (event: PointerEvent): void => { if (!this.active || event.pointerId !== this.active.pointerId) return; event.preventDefault(); event.stopImmediatePropagation(); const world = this.world(event); const point = event.altKey ? world : this.snap.snapPoint(world); const patch = this.editPatch(this.active.final, this.active.handle, point); if (this.routes.updateRoute(this.active.routeId, patch)) this.active.final = cloneFactoryRoute(this.routes.getRoute(this.active.routeId)!); };
  private readonly pointerUp = (event: PointerEvent): void => { if (!this.active || event.pointerId !== this.active.pointerId) return; event.preventDefault(); event.stopImmediatePropagation(); const active = this.active; const final = cloneFactoryRoute(active.final); const endpoint = active.handle.kind === 'source' || active.handle.kind === 'target' ? this.nearAnchor(this.world(event)) : null; if (endpoint) { const patch = active.handle.kind === 'source' ? { source: endpoint } : { target: endpoint }; this.routes.updateRoute(active.routeId, patch); Object.assign(final, cloneFactoryRoute(this.routes.getRoute(active.routeId)!)); } this.routes.updateRoute(active.routeId, active.original); this.active = null; if (this.viewport.hasPointerCapture(event.pointerId)) this.viewport.releasePointerCapture(event.pointerId); const ok = this.commands.updateRoute(active.routeId, final, `Edit route ${active.routeId}`); this.onStatus(ok ? `Route updated: ${active.routeId}` : 'Route geometry unchanged'); this.render(); };
  private readonly pointerCancel = (event: PointerEvent): void => { if (this.active?.pointerId === event.pointerId) this.cancel(true); };
  private readonly keyDown = (event: KeyboardEvent): void => { if (event.key === 'Escape' && this.active) { event.preventDefault(); this.cancel(true); } };

  private editPatch(route: FactoryRoute, handle: RouteHandle, point: GeometryPoint): Partial<FactoryRoute> {
    if (handle.kind === 'source') return { source: { kind: 'free', point } };
    if (handle.kind === 'target') return { target: { kind: 'free', point } };
    const waypoints = route.waypoints.map((item) => ({ ...item })); const current = waypoints[handle.index]; if (!current) return {};
    const previous = handle.index > 0 ? waypoints[handle.index - 1] : this.resolve(route)[0]; const next = handle.index < waypoints.length - 1 ? waypoints[handle.index + 1] : this.resolve(route).at(-1)!;
    const incomingVertical = previous.x === current.x; const outgoingVertical = current.x === next.x; const dx = Math.abs(point.x - current.x); const dy = Math.abs(point.y - current.y);
    if (incomingVertical !== outgoingVertical) {
      if (dx >= dy) { current.x = point.x; if (incomingVertical && handle.index > 0) waypoints[handle.index - 1].x = point.x; if (outgoingVertical && handle.index < waypoints.length - 1) waypoints[handle.index + 1].x = point.x; }
      else { current.y = point.y; if (!incomingVertical && handle.index > 0) waypoints[handle.index - 1].y = point.y; if (!outgoingVertical && handle.index < waypoints.length - 1) waypoints[handle.index + 1].y = point.y; }
    }
    return { waypoints };
  }

  private selectedRoute(): FactoryRoute | null { const selected = this.selection.getSelection(); return selected.kind === 'factoryRoute' ? this.routes.getRoute(selected.id) ?? null : null; }
  private resolve(route: FactoryRoute): GeometryPoint[] { return resolveFactoryRoutePolyline(route, { getResource: (id) => this.resources.getResource(id), getArea: (id) => this.structure.getArea(id) }); }
  private world(event: PointerEvent): GeometryPoint { const bounds = this.viewport.getBoundingClientRect(); return screenToWorld({ x: event.clientX - bounds.left, y: event.clientY - bounds.top }, this.state); }
  private nearAnchor(point: GeometryPoint): FactoryRouteEndpoint | null { let best: { endpoint: FactoryRouteEndpoint; distance: number } | null = null; for (const resource of this.resources.getPlacedResources().filter((item) => item.visible)) { const anchor = nearestRectangleAnchor(point, { x: resource.worldX, y: resource.worldY }, resource.width, resource.depth, resource.rotationDegrees); const distance = Math.hypot(point.x - anchor.point.x, point.y - anchor.point.y); if (distance <= 12 / this.state.zoom && (!best || distance < best.distance)) best = { endpoint: { kind: 'resource', resourceId: resource.id, anchorSide: anchor.side, anchorOffset: anchor.offset }, distance }; } for (const area of this.structure.getAreas().filter((item) => item.visible)) { const anchor = nearestRectangleAnchor(point, { x: area.worldX, y: area.worldY }, area.width, area.depth, area.rotationDegrees); const distance = Math.hypot(point.x - anchor.point.x, point.y - anchor.point.y); if (distance <= 12 / this.state.zoom && (!best || distance < best.distance)) best = { endpoint: { kind: 'area', areaId: area.id, anchorSide: anchor.side, anchorOffset: anchor.offset }, distance }; } return best?.endpoint ?? null; }

  private readonly render = (): void => { this.layer.replaceChildren(); const route = this.selectedRoute(); if (!route || !route.visible || route.locked || this.state.tool !== 'select') return; const resolved = this.resolve(route); if (resolved.length < 2) return; const add = (point: GeometryPoint, value: string, className: string): void => { const handle = svg('circle'); handle.classList.add('factory-route-edit-handle', className); handle.setAttribute('cx', String(point.x)); handle.setAttribute('cy', String(point.y)); handle.setAttribute('r', String(7 / this.state.zoom)); handle.dataset.routeHandle = value; handle.setAttribute('role', 'button'); handle.setAttribute('tabindex', '0'); handle.setAttribute('aria-label', `${value.replace(':', ' ')} handle for ${route.id}`); this.layer.append(handle); }; add(resolved[0], 'source', 'factory-route-edit-handle--endpoint'); route.waypoints.forEach((point, index) => add(point, `waypoint:${index}`, 'factory-route-edit-handle--waypoint')); add(resolved.at(-1)!, 'target', 'factory-route-edit-handle--endpoint'); };

  private readonly contextMenu = (event: MouseEvent): void => { const routeId = (event.target as Element | null)?.closest<SVGGElement>('[data-factory-route-id]')?.dataset.factoryRouteId; if (!routeId) return; event.preventDefault(); if (!this.selection.contains({ kind: 'factoryRoute', id: routeId })) this.selection.select({ kind: 'factoryRoute', id: routeId }); const route = this.routes.getRoute(routeId)!; this.menu.replaceChildren(); const add = (label: string, run: () => void, disabled = false): void => { const button = document.createElement('button'); button.type = 'button'; button.className = 'resource-context-menu__item'; button.setAttribute('role', 'menuitem'); button.textContent = label; button.disabled = disabled; button.addEventListener('click', () => { run(); this.closeMenu(); }); this.menu.append(button); }; add('Reverse Route', () => { this.reverseSelected(); }, route.locked); add('Insert Waypoint', () => { this.insertWaypoint(); }, route.locked); add('Delete Selected Waypoint', () => { this.deleteWaypoint(); }, route.locked || !route.waypoints.length); add('Copy', () => this.onStatus(this.editing.copy().message)); add('Cut', () => this.onStatus(this.editing.cut((message) => window.confirm(message)).message), route.locked); add('Duplicate', () => this.onStatus(this.editing.duplicate().message)); add('Delete', () => this.onStatus(this.editing.deleteSelection((message) => window.confirm(message)).message), route.locked); add(route.locked ? 'Unlock' : 'Lock', () => { this.commands.updateRoute(route.id, { locked: !route.locked }, `${route.locked ? 'Unlock' : 'Lock'} route ${route.id}`); }); add(route.visible ? 'Hide' : 'Show', () => { this.commands.updateRoute(route.id, { visible: !route.visible }, `${route.visible ? 'Hide' : 'Show'} route ${route.id}`); }, route.locked); add('Properties', () => this.onStatus(`Properties open for ${route.id}`)); this.menu.hidden = false; const bounds = this.viewport.getBoundingClientRect(); this.menu.style.left = `${Math.min(event.clientX - bounds.left, bounds.width - 190)}px`; this.menu.style.top = `${Math.min(event.clientY - bounds.top, bounds.height - 360)}px`; this.menu.querySelector<HTMLButtonElement>('button')?.focus(); };
  private readonly outsideMenu = (event: PointerEvent): void => { if (!this.menu.hidden && event.target instanceof Node && !this.menu.contains(event.target)) this.closeMenu(); };
  private closeMenu(): void { this.menu.hidden = true; this.menu.replaceChildren(); }
}
