import { aggregateBounds, boundsOf, geometryValue, sameGeometry, type GeometryChange, type GeometrySnapshot, type GeometryValue } from './GeometryBounds';

export type AlignmentCommand = 'align-left' | 'align-centre-x' | 'align-right' | 'align-top' | 'align-centre-y' | 'align-bottom';
export type DistributionCommand = 'distribute-x' | 'distribute-y' | 'equal-gaps-x' | 'equal-gaps-y';
export type SizingCommand = 'match-width' | 'match-height' | 'match-size';
export type ArrangementCommand = AlignmentCommand | DistributionCommand | SizingCommand;
export interface ArrangementCalculation { readonly changes: readonly GeometryChange[]; readonly error?: 'insufficient' | 'negative-space' | 'missing-primary'; }

const changesFrom = (nodes: readonly GeometrySnapshot[], values: ReadonlyMap<string, GeometryValue>): GeometryChange[] => nodes.map((node) => ({ id: node.id, kind: node.kind, before: geometryValue(node), after: values.get(node.id) ?? geometryValue(node) })).filter((item) => !sameGeometry(item.before, item.after));

export function calculateArrangement(command: ArrangementCommand, nodes: readonly GeometrySnapshot[], primary: GeometrySnapshot | null): ArrangementCalculation {
  const minimum = command.startsWith('distribute') || command.startsWith('equal-gaps') ? 3 : 2; if (nodes.length < minimum) return { changes: [], error: 'insufficient' };
  const values = new Map(nodes.map((node) => [node.id, geometryValue(node)])); const selectionBounds = aggregateBounds(nodes)!;
  if (command.startsWith('align-')) for (const node of nodes) { const value = values.get(node.id)!; if (command === 'align-left') values.set(node.id, { ...value, x: selectionBounds.left + node.width / 2 }); else if (command === 'align-centre-x') values.set(node.id, { ...value, x: selectionBounds.centreX }); else if (command === 'align-right') values.set(node.id, { ...value, x: selectionBounds.right - node.width / 2 }); else if (command === 'align-top') values.set(node.id, { ...value, y: selectionBounds.top + node.height / 2 }); else if (command === 'align-centre-y') values.set(node.id, { ...value, y: selectionBounds.centreY }); else if (command === 'align-bottom') values.set(node.id, { ...value, y: selectionBounds.bottom - node.height / 2 }); }
  else if (command === 'distribute-x' || command === 'distribute-y') { const horizontal = command === 'distribute-x'; const sorted = [...nodes].sort((a, b) => (horizontal ? a.x - b.x : a.y - b.y) || a.id.localeCompare(b.id)); const first = horizontal ? sorted[0].x : sorted[0].y; const last = horizontal ? sorted.at(-1)!.x : sorted.at(-1)!.y; const interval = (last - first) / (sorted.length - 1); sorted.slice(1, -1).forEach((node, index) => { const value = values.get(node.id)!; values.set(node.id, horizontal ? { ...value, x: first + interval * (index + 1) } : { ...value, y: first + interval * (index + 1) }); }); }
  else if (command === 'equal-gaps-x' || command === 'equal-gaps-y') { const horizontal = command === 'equal-gaps-x'; const sorted = [...nodes].sort((a, b) => { const aa = boundsOf(a); const bb = boundsOf(b); return (horizontal ? aa.left - bb.left : aa.top - bb.top) || a.id.localeCompare(b.id); }); const firstBounds = boundsOf(sorted[0]); const lastBounds = boundsOf(sorted.at(-1)!); const span = horizontal ? lastBounds.right - firstBounds.left : lastBounds.bottom - firstBounds.top; const totalSize = sorted.reduce((sum, node) => sum + (horizontal ? node.width : node.height), 0); const gap = (span - totalSize) / (sorted.length - 1); if (gap < 0) return { changes: [], error: 'negative-space' }; let cursor = horizontal ? firstBounds.left : firstBounds.top; sorted.forEach((node, index) => { if (index > 0) cursor += gap; const value = values.get(node.id)!; values.set(node.id, horizontal ? { ...value, x: cursor + node.width / 2 } : { ...value, y: cursor + node.height / 2 }); cursor += horizontal ? node.width : node.height; }); }
  else { if (!primary) return { changes: [], error: 'missing-primary' }; for (const node of nodes) { if (node.id === primary.id) continue; const value = values.get(node.id)!; values.set(node.id, { ...value, width: command === 'match-height' ? value.width : primary.width, height: command === 'match-width' ? value.height : primary.height }); } }
  return { changes: changesFrom(nodes, values) };
}
