import type { ResourceTemplate } from '../../models/resources/ResourceTemplate';

export const RESOURCE_TEMPLATES: readonly ResourceTemplate[] = [
  { id: 'TPL-CNC-001', name: 'CNC Machining Centre', description: 'Automated multi-axis machining equipment.', category: 'Machines', resourceType: 'CNC Machine', icon: 'cnc', defaultWidth: 140, defaultHeight: 90, tags: ['cnc', 'machine', 'automatic'], isFavourite: true },
  { id: 'TPL-CNC-002', name: 'CNC Turning Centre', description: 'Automated lathe and turning resource.', category: 'Machines', resourceType: 'CNC Machine', icon: 'cnc', defaultWidth: 130, defaultHeight: 84, tags: ['lathe', 'turning', 'machine'], isFavourite: false },
  { id: 'TPL-MAN-001', name: 'Assembly Workstation', description: 'Manual assembly and fitting station.', category: 'Manual Process', resourceType: 'Manual Workstation', icon: 'workstation', defaultWidth: 120, defaultHeight: 75, tags: ['assembly', 'manual', 'bench'], isFavourite: true },
  { id: 'TPL-MAN-002', name: 'Packing Station', description: 'Manual packing and dispatch preparation.', category: 'Manual Process', resourceType: 'Manual Workstation', icon: 'workstation', defaultWidth: 110, defaultHeight: 70, tags: ['packing', 'manual', 'dispatch'], isFavourite: false },
  { id: 'TPL-QUA-001', name: 'Inspection Bench', description: 'Dimensional and visual inspection point.', category: 'Quality', resourceType: 'Inspection', icon: 'inspection', defaultWidth: 110, defaultHeight: 70, tags: ['quality', 'inspection', 'measurement'], isFavourite: true },
  { id: 'TPL-QUA-002', name: 'CMM Inspection', description: 'Coordinate measuring machine station.', category: 'Quality', resourceType: 'Inspection', icon: 'inspection', defaultWidth: 120, defaultHeight: 100, tags: ['cmm', 'quality', 'metrology'], isFavourite: false },
  { id: 'TPL-HAN-001', name: 'Load / Unload Point', description: 'Material loading and unloading location.', category: 'Material Handling', resourceType: 'Load / Unload', icon: 'handling', defaultWidth: 90, defaultHeight: 65, tags: ['load', 'unload', 'handling'], isFavourite: false },
  { id: 'TPL-HAN-002', name: 'Material Buffer', description: 'Controlled work-in-progress staging buffer.', category: 'Material Handling', resourceType: 'Material Buffer', icon: 'buffer', defaultWidth: 100, defaultHeight: 75, tags: ['buffer', 'wip', 'material'], isFavourite: true },
  { id: 'TPL-PEO-001', name: 'Operator', description: 'Production operator allocation.', category: 'People', resourceType: 'Operator', icon: 'operator', defaultWidth: 70, defaultHeight: 70, tags: ['person', 'operator', 'labour'], isFavourite: false },
  { id: 'TPL-PEO-002', name: 'Walking Route', description: 'Operator walking or travel reference.', category: 'People', resourceType: 'Walking', icon: 'walking', defaultWidth: 100, defaultHeight: 50, tags: ['walking', 'travel', 'movement'], isFavourite: false },
  { id: 'TPL-TOL-001', name: 'Tooling Station', description: 'Tool storage and presetting location.', category: 'General', resourceType: 'Tooling', icon: 'tooling', defaultWidth: 90, defaultHeight: 70, tags: ['tooling', 'storage', 'preset'], isFavourite: false },
  { id: 'TPL-DOC-001', name: 'Work Instruction', description: 'Controlled manufacturing document reference.', category: 'Documentation', resourceType: 'Document', icon: 'document', defaultWidth: 85, defaultHeight: 65, tags: ['document', 'instruction', 'standard'], isFavourite: false },
  { id: 'TPL-GEN-001', name: 'Generic Equipment', description: 'Unclassified manufacturing equipment.', category: 'General', resourceType: 'Generic Equipment', icon: 'equipment', defaultWidth: 110, defaultHeight: 80, tags: ['equipment', 'generic'], isFavourite: false },
];
