import { isValidStandardWorkEntry, isValidStandardWorkStudy, type StandardWorkEntry, type StandardWorkStudy } from '../../models/standardWork/StandardWork';
import { isValidStandardWorkOperator, type StandardWorkOperator } from '../../models/standardWork/StandardWorkOperator';
import { isValidStandardWorkHandover, type StandardWorkHandover } from '../../models/standardWork/StandardWorkHandover';
import type { OperationStore } from '../OperationStore';
import type { ResourceStore } from '../ResourceStore';
import { validateHandoverGraph } from './StandardWorkDependencyGraph';

export interface StandardWorkIssue { readonly severity: 'error' | 'warning'; readonly code: string; readonly message: string; readonly studyId?: string; readonly entryId?: string; readonly operationId?: string; readonly operatorId?: string; readonly handoverId?: string; }
export interface StandardWorkValidation { readonly errors: number; readonly warnings: number; readonly issues: readonly StandardWorkIssue[]; }

export function validateStandardWork(studies: readonly StandardWorkStudy[], entries: readonly StandardWorkEntry[], operations: OperationStore, operators: readonly StandardWorkOperator[] = [], handovers: readonly StandardWorkHandover[] = [], resources?: Pick<ResourceStore, 'getResource'>): StandardWorkValidation {
  const issues: StandardWorkIssue[] = []; const studyIds = new Set<string>(); const entryIds = new Set<string>(); const operatorIds = new Set<string>(); const handoverIds = new Set<string>(); const pairs = new Set<string>();
  const entryById = new Map(entries.map((entry) => [entry.id, entry])); const operatorById = new Map(operators.map((operator) => [operator.id, operator])); const entryCountByStudy = new Map<string, number>(); const operatorCountByStudy = new Map<string, number>();
  for (const entry of entries) entryCountByStudy.set(entry.studyId, (entryCountByStudy.get(entry.studyId) ?? 0) + 1); for (const operator of operators) operatorCountByStudy.set(operator.studyId, (operatorCountByStudy.get(operator.studyId) ?? 0) + 1);
  for (const study of studies) { if (studyIds.has(study.id)) issues.push({ severity: 'error', code: 'duplicate-study-id', studyId: study.id, message: `Standard Work study ID ${study.id} is duplicated.` }); studyIds.add(study.id); if (!isValidStandardWorkStudy(study)) issues.push({ severity: 'error', code: 'invalid-study', studyId: study.id, message: `Standard Work study ${study.id} has invalid metadata.` }); if (!(entryCountByStudy.get(study.id) ?? 0)) issues.push({ severity: 'warning', code: 'empty-study', studyId: study.id, message: `Standard Work study ${study.id} is empty.` }); if (!(operatorCountByStudy.get(study.id) ?? 0)) issues.push({ severity: 'error', code: 'missing-study-operator', studyId: study.id, message: `Standard Work study ${study.id} must have at least one operator.` }); }
  for (const operator of operators) { if (operatorIds.has(operator.id)) issues.push({ severity: 'error', code: 'duplicate-operator-id', studyId: operator.studyId, operatorId: operator.id, message: `Operator ID ${operator.id} is duplicated.` }); operatorIds.add(operator.id); if (!isValidStandardWorkOperator(operator)) issues.push({ severity: 'error', code: 'invalid-operator', studyId: operator.studyId, operatorId: operator.id, message: `Operator ${operator.id} has invalid metadata.` }); if (!studyIds.has(operator.studyId)) issues.push({ severity: 'error', code: 'operator-missing-study', studyId: operator.studyId, operatorId: operator.id, message: `Operator ${operator.id} references missing study ${operator.studyId}.` }); if (operator.linkedResourceId && resources && !resources.getResource(operator.linkedResourceId)) issues.push({ severity: 'error', code: 'operator-missing-resource', studyId: operator.studyId, operatorId: operator.id, message: `Operator ${operator.id} references missing resource ${operator.linkedResourceId}.` }); }
  for (const entry of entries) {
    if (entryIds.has(entry.id)) issues.push({ severity: 'error', code: 'duplicate-entry-id', entryId: entry.id, message: `Standard Work entry ID ${entry.id} is duplicated.` }); entryIds.add(entry.id);
    if (!isValidStandardWorkEntry(entry)) issues.push({ severity: 'error', code: 'invalid-entry', studyId: entry.studyId, entryId: entry.id, operationId: entry.operationId, message: `Standard Work entry ${entry.id} has invalid order, occurrences, operator assignment, or notes.` });
    if (!studyIds.has(entry.studyId)) issues.push({ severity: 'error', code: 'missing-study', studyId: entry.studyId, entryId: entry.id, message: `Standard Work entry ${entry.id} references missing study ${entry.studyId}.` });
    const operator = operatorById.get(entry.assignedOperatorId); if (!operator) issues.push({ severity: 'error', code: 'missing-operator', studyId: entry.studyId, entryId: entry.id, operatorId: entry.assignedOperatorId, message: `${entry.id} references missing operator ${entry.assignedOperatorId}.` }); else { if (operator.studyId !== entry.studyId) issues.push({ severity: 'error', code: 'cross-study-operator', studyId: entry.studyId, entryId: entry.id, operatorId: operator.id, message: `${entry.id} and operator ${operator.id} belong to different studies.` }); if (!operator.active) issues.push({ severity: 'warning', code: 'inactive-operator', studyId: entry.studyId, entryId: entry.id, operatorId: operator.id, message: `${entry.id} is assigned to inactive operator ${operator.id}.` }); }
    const operation = operations.getOperation(entry.operationId); if (!operation) issues.push({ severity: 'error', code: 'missing-operation', studyId: entry.studyId, entryId: entry.id, operationId: entry.operationId, message: `Standard Work entry ${entry.id} references missing operation ${entry.operationId}.` }); else { if (!Number.isFinite(operation.cycleTimeSeconds) || operation.cycleTimeSeconds < 0) issues.push({ severity: 'error', code: 'invalid-cycle-time', studyId: entry.studyId, entryId: entry.id, operationId: entry.operationId, message: `${entry.operationId} has an invalid cycle time.` }); else if (operation.cycleTimeSeconds === 0) issues.push({ severity: 'warning', code: 'zero-cycle-time', studyId: entry.studyId, entryId: entry.id, operationId: entry.operationId, message: `${entry.operationId} has zero cycle time.` }); if (!operation.assignedResourceId) issues.push({ severity: 'warning', code: 'unassigned-operation', studyId: entry.studyId, entryId: entry.id, operationId: entry.operationId, message: `${entry.operationId} is unassigned.` }); }
    const pair = `${entry.studyId}\0${entry.operationId}`; if (pairs.has(pair)) issues.push({ severity: 'error', code: 'duplicate-operation', studyId: entry.studyId, entryId: entry.id, operationId: entry.operationId, message: `${entry.operationId} appears more than once in ${entry.studyId}. Use occurrences instead.` }); pairs.add(pair); if (!entry.enabled) issues.push({ severity: 'warning', code: 'disabled-entry', studyId: entry.studyId, entryId: entry.id, operationId: entry.operationId, message: `${entry.id} is disabled and excluded from totals.` });
  }
  for (const handover of handovers) { if (handoverIds.has(handover.id)) issues.push({ severity: 'error', code: 'duplicate-handover-id', studyId: handover.studyId, handoverId: handover.id, message: `Handover ID ${handover.id} is duplicated.` }); handoverIds.add(handover.id); if (!isValidStandardWorkHandover(handover)) issues.push({ severity: 'error', code: 'invalid-handover', studyId: handover.studyId, handoverId: handover.id, message: `Handover ${handover.id} has invalid metadata.` }); const from = entryById.get(handover.fromEntryId); const to = entryById.get(handover.toEntryId); if (from && to && from.assignedOperatorId === to.assignedOperatorId) issues.push({ severity: 'warning', code: 'same-operator-handover', studyId: handover.studyId, handoverId: handover.id, operatorId: from.assignedOperatorId, message: `${handover.id} connects entries assigned to the same operator.` }); }
  for (const study of studies) for (const problem of validateHandoverGraph(entries.filter((entry) => entry.studyId === study.id), handovers.filter((handover) => handover.studyId === study.id))) issues.push({ severity: 'error', code: problem.code, studyId: study.id, handoverId: problem.handoverId, message: problem.message });
  return { errors: issues.filter((issue) => issue.severity === 'error').length, warnings: issues.filter((issue) => issue.severity === 'warning').length, issues };
}
