import type { CanvasState } from '../../../models/canvas/CanvasState';
import type { AnnotationAnchor, CoordinateAnnotation, FactoryAnnotation, LeaderAnnotation, LinearDimensionAnnotation, LinearDimensionKind, TextAnnotation } from '../../../models/factory/FactoryAnnotation';
import { DEFAULT_FACTORY_LAYOUT_ID } from '../../../models/workspace/Workspace';
import type { FactoryAnnotationStore } from '../../../services/FactoryAnnotationStore';
import type { ProjectSessionService } from '../../../services/project/ProjectSessionService';
import type { FactoryAnnotationCommandFactory } from '../../../services/history/FactoryAnnotationCommandFactory';
import type { AnnotationSnapService } from '../../../services/annotations/AnnotationSnapService';
import { dimensionValue, linearDimensionGeometry } from '../../../services/annotations/LinearDimensionGeometry';
import { screenToWorld, type Point } from '../canvas/ViewportTransform';

const NS = 'http://www.w3.org/2000/svg'; const svg = <K extends keyof SVGElementTagNameMap>(tag: K): SVGElementTagNameMap[K] => document.createElementNS(NS, tag);
type SnapPoint = { readonly point: Point; readonly anchor: AnnotationAnchor };
export class FactoryAnnotationDrawController {
  private points: SnapPoint[] = []; private elbows: Point[] = []; private pointer: Point | null = null;
  public constructor(private readonly viewport: HTMLElement, private readonly layer: SVGGElement, private readonly state: CanvasState, private readonly snap: AnnotationSnapService, private readonly store: FactoryAnnotationStore, private readonly project: ProjectSessionService, private readonly commands: FactoryAnnotationCommandFactory, private readonly onStatus: (message: string) => void, private readonly finishTool: () => void) { viewport.addEventListener('pointerdown', this.pointerDown, true); viewport.addEventListener('pointermove', this.pointerMove, true); document.addEventListener('keydown', this.keyDown); }
  public dispose(): void { this.viewport.removeEventListener('pointerdown', this.pointerDown, true); this.viewport.removeEventListener('pointermove', this.pointerMove, true); document.removeEventListener('keydown', this.keyDown); this.layer.replaceChildren(); }
  public cancel(report = true): void { this.points = []; this.elbows = []; this.pointer = null; this.layer.replaceChildren(); if (report) this.onStatus('Annotation placement cancelled'); }
  public toolChanged(): void { this.cancel(false); if (this.annotationTool()) this.onStatus(this.prompt()); }
  private annotationTool(): boolean { return ['dimension-horizontal', 'dimension-vertical', 'dimension-aligned', 'coordinate-marker', 'text-note', 'leader'].includes(this.state.tool); }
  private prompt(): string { if (String(this.state.tool).startsWith('dimension-')) return this.points.length === 0 ? 'Dimension: select first anchor' : this.points.length === 1 ? 'Dimension: select second anchor' : 'Dimension: place dimension line'; if (this.state.tool === 'coordinate-marker') return this.points.length ? 'Coordinate: place label' : 'Coordinate: select anchor'; if (this.state.tool === 'text-note') return 'Text Note: select position'; return this.points.length ? 'Leader: click text position, or Shift-click an elbow' : 'Leader: select anchor'; }
  private readonly pointerDown = (event: PointerEvent): void => { if (!this.annotationTool() || event.button !== 0) return; const snap = this.resolve(event); this.pointer = snap.point; if (this.state.tool === 'text-note') this.createText(snap.point); else if (this.state.tool === 'coordinate-marker') { if (!this.points.length) this.points.push(snap); else this.createCoordinate(this.points[0], snap.point); } else if (this.state.tool === 'leader') { if (!this.points.length) this.points.push(snap); else if (event.shiftKey) this.elbows.push(snap.point); else this.createLeader(this.points[0], snap.point); } else { this.points.push(snap); if (this.points.length === 3) this.createDimension(this.points[0], this.points[1], snap.point); } this.render(); this.onStatus(this.annotationTool() ? this.prompt() : 'Select tool active'); event.preventDefault(); event.stopPropagation(); };
  private readonly pointerMove = (event: PointerEvent): void => { if (!this.annotationTool()) return; this.pointer = this.resolve(event).point; this.render(); };
  private readonly keyDown = (event: KeyboardEvent): void => { if (!this.annotationTool()) return; if (event.key === 'Escape') { event.preventDefault(); this.cancel(); this.finishTool(); } else if (event.key === 'Backspace' && this.state.tool === 'leader' && this.elbows.length) { event.preventDefault(); this.elbows.pop(); this.render(); } };
  private resolve(event: PointerEvent): SnapPoint { const bounds = this.viewport.getBoundingClientRect(); const world = screenToWorld({ x: event.clientX - bounds.left, y: event.clientY - bounds.top }, this.state); const value = this.snap.resolve(world, this.state.zoom, event.altKey); return { point: value.point, anchor: value.anchor }; }
  private createDimension(start: SnapPoint, end: SnapPoint, placement: Point): void { const kind = this.kind(); const value = dimensionValue(kind, start.point, end.point); if (value <= 1e-9) { this.onStatus('Zero-length dimensions cannot be created'); this.points = []; return; } const offset = kind === 'Horizontal' ? placement.y - start.point.y : kind === 'Vertical' ? placement.x - start.point.x : this.alignedOffset(start.point, end.point, placement); const settings = this.project.getSettings(); const item: LinearDimensionAnnotation = { ...this.base(), annotationType: 'linearDimension', dimensionKind: kind, startAnchor: start.anchor, endAnchor: end.anchor, offset, textPosition: .5, textOverride: '', prefix: '', suffix: '', showUnit: true, precisionOverride: null, layer: settings.defaultDimensionLayer }; this.commit(item, `${kind} dimension created`); }
  private createCoordinate(anchor: SnapPoint, label: Point): void { const item: CoordinateAnnotation = { ...this.base(), annotationType: 'coordinate', anchor: anchor.anchor, labelOffset: { x: label.x - anchor.point.x, y: label.y - anchor.point.y }, showX: true, showY: true, prefix: '', suffix: '', precisionOverride: null, layer: 'Coordinates' }; this.commit(item, 'Coordinate marker created'); }
  private createText(point: Point): void { const text = window.prompt('Text note'); if (!text?.trim()) { this.onStatus('Empty text note cancelled'); return; } const settings = this.project.getSettings(); const item: TextAnnotation = { ...this.base(), annotationType: 'text', worldPosition: { ...point }, text, textSize: settings.annotationTextSize, textAlign: 'left', rotationDegrees: 0, backgroundEnabled: true, borderEnabled: true, layer: 'Notes' }; this.commit(item, 'Note created'); }
  private createLeader(anchor: SnapPoint, textPosition: Point): void { const text = window.prompt('Leader text'); if (!text?.trim()) { this.onStatus('Empty leader cancelled'); return; } const settings = this.project.getSettings(); const elbows = this.elbows.length ? this.elbows : [{ x: textPosition.x, y: anchor.point.y }]; const item: LeaderAnnotation = { ...this.base(), annotationType: 'leader', anchor: anchor.anchor, elbowPoints: elbows.map((point) => ({ ...point })), textPosition: { ...textPosition }, text, textSize: settings.annotationTextSize, arrowStyle: 'open', layer: 'Notes' }; this.commit(item, 'Leader created'); }
  private commit(item: FactoryAnnotation, label: string): void { if (this.commands.insert(item, `${label}: ${item.id}`)) this.onStatus(`${label}: ${item.id}`); this.cancel(false); this.finishTool(); }
  private base(): Omit<FactoryAnnotation, 'annotationType'> & { annotationType?: never } { return { id: this.store.nextId(), layoutId: DEFAULT_FACTORY_LAYOUT_ID, visible: true, locked: false, layer: 'General', note: '', createdUtc: new Date().toISOString() } as never; }
  private kind(): LinearDimensionKind { return this.state.tool === 'dimension-horizontal' ? 'Horizontal' : this.state.tool === 'dimension-vertical' ? 'Vertical' : 'Aligned'; }
  private alignedOffset(start: Point, end: Point, placement: Point): number { const length = Math.hypot(end.x - start.x, end.y - start.y); return length ? ((placement.x - start.x) * -(end.y - start.y) + (placement.y - start.y) * (end.x - start.x)) / length : 0; }
  private render(): void { this.layer.replaceChildren(); if (!this.pointer || !this.points.length) return; const polyline = svg('polyline'); polyline.classList.add('factory-annotation-preview'); const values = [this.points[0].point, ...this.elbows, this.pointer]; if (String(this.state.tool).startsWith('dimension-') && this.points.length >= 2) { const geometry = linearDimensionGeometry(this.kind(), this.points[0].point, this.points[1].point, this.kind() === 'Horizontal' ? this.pointer.y - this.points[0].point.y : this.kind() === 'Vertical' ? this.pointer.x - this.points[0].point.x : this.alignedOffset(this.points[0].point, this.points[1].point, this.pointer)); if (geometry) values.splice(0, values.length, geometry.dimensionStart, geometry.dimensionEnd); } polyline.setAttribute('points', values.map((point) => `${point.x},${point.y}`).join(' ')); this.layer.append(polyline); }
}
