import type { CanvasState } from '../../../models/canvas/CanvasState';
import type { FactoryAnnotation } from '../../../models/factory/FactoryAnnotation';
import type { SelectionController } from '../../../models/selection/Selection';
import type { FactoryAnnotationStore } from '../../../services/FactoryAnnotationStore';
import type { ProjectSessionService } from '../../../services/project/ProjectSessionService';
import type { AnnotationAnchorResolver } from '../../../services/annotations/AnnotationAnchorResolver';
import { formatDimension } from '../../../services/annotations/DimensionFormatter';
import { dimensionValue, linearDimensionGeometry } from '../../../services/annotations/LinearDimensionGeometry';
import { convertLength, formatLengthNumber, lengthUnitSymbol } from '../../../services/units/LengthUnitService';
import type { GeometryPoint } from '../../../services/geometry/FactoryFootprintGeometry';

const NS = 'http://www.w3.org/2000/svg'; const svg = <K extends keyof SVGElementTagNameMap>(tag: K): SVGElementTagNameMap[K] => document.createElementNS(NS, tag);
export interface AnnotationLayerVisibility { readonly annotations: boolean; readonly Dimensions: boolean; readonly Coordinates: boolean; readonly Notes: boolean; readonly General: boolean; }
export class FactoryAnnotationRenderer {
  private visibility: AnnotationLayerVisibility = { annotations: true, Dimensions: true, Coordinates: true, Notes: true, General: true };
  private readonly unsubscribe: (() => void)[];
  public constructor(private readonly layer: SVGGElement, private readonly store: FactoryAnnotationStore, private readonly resolver: AnnotationAnchorResolver, private readonly project: ProjectSessionService, private readonly selection: SelectionController, private readonly state: CanvasState) { this.unsubscribe = [store.subscribe(() => this.render()), selection.subscribe(() => this.render()), project.subscribe(() => this.render())]; this.render(); }
  public dispose(): void { this.unsubscribe.forEach((fn) => fn()); this.layer.replaceChildren(); }
  public getVisibility(): AnnotationLayerVisibility { return { ...this.visibility }; }
  public setVisibility(patch: Partial<AnnotationLayerVisibility>): void { this.visibility = { ...this.visibility, ...patch }; this.render(); }
  public viewportChanged(): void { this.render(); }
  public getVisiblePoints(): GeometryPoint[] { const points: GeometryPoint[] = []; for (const item of this.visibleAnnotations()) points.push(...this.geometryPoints(item)); return points; }
  private visibleAnnotations(): readonly FactoryAnnotation[] { return this.visibility.annotations ? this.store.getAnnotations().filter((item) => item.visible && this.visibility[item.layer]) : []; }
  private render(): void {
    this.layer.replaceChildren(); const defs = svg('defs'); defs.append(this.arrow('factory-annotation-arrow-start', true), this.arrow('factory-annotation-arrow-end', false), this.arrow('factory-leader-arrow', false)); this.layer.append(defs);
    for (const annotation of this.visibleAnnotations()) { const group = svg('g'); group.classList.add('factory-annotation', `factory-annotation--${annotation.annotationType}`); group.classList.toggle('factory-annotation--selected', this.selection.contains({ kind: 'factoryAnnotation', id: annotation.id })); group.classList.toggle('factory-annotation--locked', annotation.locked); group.dataset.factoryAnnotationId = annotation.id; group.setAttribute('role', 'button'); group.setAttribute('tabindex', '0'); group.setAttribute('aria-label', this.accessibleText(annotation)); const title = svg('title'); title.textContent = this.accessibleText(annotation); group.append(title); this.renderAnnotation(group, annotation); const choose = (event: Event): void => { const pointer = event as PointerEvent; const ref = { kind: 'factoryAnnotation' as const, id: annotation.id }; if (pointer.ctrlKey || pointer.metaKey) this.selection.toggle(ref); else if (pointer.shiftKey) this.selection.add(ref); else this.selection.select(ref); event.stopPropagation(); }; group.addEventListener('pointerdown', choose); group.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); choose(event); } }); this.layer.append(group); }
  }
  private renderAnnotation(group: SVGGElement, annotation: FactoryAnnotation): void {
    if (annotation.annotationType === 'linearDimension') { const start = this.resolver.resolve(annotation.startAnchor, annotation.layoutId).point; const end = this.resolver.resolve(annotation.endAnchor, annotation.layoutId).point; if (!start || !end) return this.error(group, start ?? end ?? { x: 0, y: 0 }); const settings = this.project.getSettings(); const value = dimensionValue(annotation.dimensionKind, start, end); const text = formatDimension(value, annotation, settings); const font = 12 * settings.dimensionTextScale / this.state.zoom; const geometry = linearDimensionGeometry(annotation.dimensionKind, start, end, annotation.offset, annotation.textPosition, text.length * font * 0.62); if (!geometry) return this.error(group, start); const line = (a: GeometryPoint, b: GeometryPoint, cls: string): SVGLineElement => { const value = svg('line'); value.classList.add(cls); value.setAttribute('x1', String(a.x)); value.setAttribute('y1', String(a.y)); value.setAttribute('x2', String(b.x)); value.setAttribute('y2', String(b.y)); return value; }; group.append(line(...geometry.extensionStart, 'factory-dimension__extension'), line(...geometry.extensionEnd, 'factory-dimension__extension')); const dimensionLine = line(geometry.dimensionStart, geometry.dimensionEnd, 'factory-dimension__line'); dimensionLine.setAttribute('marker-start', 'url(#factory-annotation-arrow-start)'); dimensionLine.setAttribute('marker-end', 'url(#factory-annotation-arrow-end)'); group.append(dimensionLine); const textGroup = svg('g'); textGroup.setAttribute('transform', `translate(${geometry.textPoint.x} ${geometry.textPoint.y}) rotate(${geometry.textRotation})`); const background = svg('rect'); const width = text.length * font * .62 + 10 / this.state.zoom; background.setAttribute('x', String(-width / 2)); background.setAttribute('y', String(-font * .72)); background.setAttribute('width', String(width)); background.setAttribute('height', String(font * 1.35)); background.setAttribute('rx', String(3 / this.state.zoom)); background.classList.add('factory-annotation__text-background'); const label = svg('text'); label.setAttribute('text-anchor', 'middle'); label.setAttribute('dominant-baseline', 'central'); label.setAttribute('font-size', String(font)); label.classList.add('factory-annotation__text'); label.textContent = text; textGroup.append(background, label); group.append(textGroup); if (geometry.outsideArrows) group.classList.add('factory-dimension--short'); }
    else if (annotation.annotationType === 'coordinate') { const point = this.resolver.resolve(annotation.anchor, annotation.layoutId).point; if (!point) return this.error(group, { x: 0, y: 0 }); const settings = this.project.getSettings(); const precision = annotation.precisionOverride ?? settings.units.displayPrecision; const x = formatLengthNumber(convertLength(point.x, settings.units.modelLengthUnit, settings.units.displayLengthUnit), precision, settings.units.showTrailingZeros); const y = formatLengthNumber(convertLength(point.y, settings.units.modelLengthUnit, settings.units.displayLengthUnit), precision, settings.units.showTrailingZeros); const parts = [annotation.showX ? `X ${x}` : '', annotation.showY ? `Y ${y}` : ''].filter(Boolean); const text = [annotation.prefix, parts.join('  '), annotation.suffix, lengthUnitSymbol(settings.units.displayLengthUnit)].filter(Boolean).join(' '); const label = { x: point.x + annotation.labelOffset.x, y: point.y + annotation.labelOffset.y }; this.renderLeaderLine(group, point, label, false); this.renderText(group, label, text, 12 / this.state.zoom, 'left', true); const marker = svg('circle'); marker.classList.add('factory-coordinate__marker'); marker.setAttribute('cx', String(point.x)); marker.setAttribute('cy', String(point.y)); marker.setAttribute('r', String(4 / this.state.zoom)); group.append(marker); }
    else if (annotation.annotationType === 'text') this.renderMultilineText(group, annotation.worldPosition, annotation.text, annotation.textSize / this.state.zoom, annotation.textAlign, annotation.rotationDegrees, annotation.backgroundEnabled, annotation.borderEnabled);
    else { const anchor = this.resolver.resolve(annotation.anchor, annotation.layoutId).point; if (!anchor) return this.error(group, { x: 0, y: 0 }); const points = [anchor, ...annotation.elbowPoints, annotation.textPosition]; const path = svg('polyline'); path.classList.add('factory-leader__line'); path.setAttribute('points', points.map((point) => `${point.x},${point.y}`).join(' ')); if (annotation.arrowStyle !== 'none') path.setAttribute('marker-start', 'url(#factory-leader-arrow)'); group.append(path); this.renderMultilineText(group, annotation.textPosition, annotation.text, annotation.textSize / this.state.zoom, 'left', 0, true, true); }
    if (annotation.locked) { const points = this.geometryPoints(annotation); const point = points.at(-1); if (point) { const lock = svg('text'); lock.classList.add('factory-annotation__lock'); lock.setAttribute('x', String(point.x + 8 / this.state.zoom)); lock.setAttribute('y', String(point.y - 8 / this.state.zoom)); lock.setAttribute('font-size', String(11 / this.state.zoom)); lock.textContent = 'LOCKED'; group.append(lock); } }
  }
  private renderLeaderLine(group: SVGGElement, start: GeometryPoint, end: GeometryPoint, arrow: boolean): void { const line = svg('polyline'); line.classList.add('factory-leader__line'); line.setAttribute('points', `${start.x},${start.y} ${end.x},${start.y} ${end.x},${end.y}`); if (arrow) line.setAttribute('marker-start', 'url(#factory-leader-arrow)'); group.append(line); }
  private renderText(group: SVGGElement, point: GeometryPoint, text: string, font: number, align: 'left' | 'centre' | 'right', backgroundEnabled: boolean): void { this.renderMultilineText(group, point, text, font, align, 0, backgroundEnabled, backgroundEnabled); }
  private renderMultilineText(group: SVGGElement, point: GeometryPoint, text: string, font: number, align: 'left' | 'centre' | 'right', rotation: number, backgroundEnabled: boolean, borderEnabled: boolean): void { const lines = text.split(/\r?\n/); const width = Math.max(1, ...lines.map((line) => line.length)) * font * .62 + 12 / this.state.zoom; const height = Math.max(1, lines.length) * font * 1.25 + 8 / this.state.zoom; const x = align === 'left' ? 0 : align === 'right' ? -width : -width / 2; const node = svg('g'); node.setAttribute('transform', `translate(${point.x} ${point.y}) rotate(${rotation})`); if (backgroundEnabled || borderEnabled) { const background = svg('rect'); background.classList.add('factory-annotation__text-background'); if (!backgroundEnabled) background.setAttribute('fill', 'none'); if (!borderEnabled) background.setAttribute('stroke', 'none'); background.setAttribute('x', String(x)); background.setAttribute('y', String(-font)); background.setAttribute('width', String(width)); background.setAttribute('height', String(height)); background.setAttribute('rx', String(3 / this.state.zoom)); node.append(background); } const label = svg('text'); label.classList.add('factory-annotation__text'); label.setAttribute('font-size', String(font)); label.setAttribute('text-anchor', align === 'centre' ? 'middle' : align === 'right' ? 'end' : 'start'); lines.forEach((line, index) => { const span = svg('tspan'); span.setAttribute('x', '0'); span.setAttribute('dy', index === 0 ? '0' : String(font * 1.25)); span.textContent = line; label.append(span); }); node.append(label); group.append(node); }
  private geometryPoints(annotation: FactoryAnnotation): GeometryPoint[] {
    if (annotation.annotationType === 'text') return [annotation.worldPosition, ...this.textExtentPoints(annotation.worldPosition, annotation.text, annotation.textSize, annotation.textAlign)];
    if (annotation.annotationType === 'coordinate') { const anchor = this.resolver.resolve(annotation.anchor, annotation.layoutId).point; if (!anchor) return []; const label = { x: anchor.x + annotation.labelOffset.x, y: anchor.y + annotation.labelOffset.y }; const settings = this.project.getSettings(); const precision = annotation.precisionOverride ?? settings.units.displayPrecision; const sample = `${annotation.prefix} X ${formatLengthNumber(convertLength(anchor.x, settings.units.modelLengthUnit, settings.units.displayLengthUnit), precision, settings.units.showTrailingZeros)}  Y ${formatLengthNumber(convertLength(anchor.y, settings.units.modelLengthUnit, settings.units.displayLengthUnit), precision, settings.units.showTrailingZeros)} ${annotation.suffix} ${lengthUnitSymbol(settings.units.displayLengthUnit)}`; return [anchor, label, ...this.textExtentPoints(label, sample, 12, 'left')]; }
    if (annotation.annotationType === 'leader') { const anchor = this.resolver.resolve(annotation.anchor, annotation.layoutId).point; return anchor ? [anchor, ...annotation.elbowPoints, annotation.textPosition, ...this.textExtentPoints(annotation.textPosition, annotation.text, annotation.textSize, 'left')] : []; }
    const start = this.resolver.resolve(annotation.startAnchor, annotation.layoutId).point; const end = this.resolver.resolve(annotation.endAnchor, annotation.layoutId).point; if (!start || !end) return []; const settings = this.project.getSettings(); const text = formatDimension(dimensionValue(annotation.dimensionKind, start, end), annotation, settings); const geometry = linearDimensionGeometry(annotation.dimensionKind, start, end, annotation.offset, annotation.textPosition); return geometry ? [start, end, geometry.dimensionStart, geometry.dimensionEnd, geometry.textPoint, ...this.textExtentPoints(geometry.textPoint, text, 12 * settings.dimensionTextScale, 'centre')] : [start, end];
  }
  private textExtentPoints(point: GeometryPoint, text: string, screenFontSize: number, align: 'left' | 'centre' | 'right'): GeometryPoint[] { const lines = text.split(/\r?\n/); const width = (Math.max(1, ...lines.map((line) => line.length)) * screenFontSize * .62 + 16) / this.state.zoom; const height = (Math.max(1, lines.length) * screenFontSize * 1.25 + 12) / this.state.zoom; const left = align === 'left' ? point.x : align === 'right' ? point.x - width : point.x - width / 2; return [{ x: left, y: point.y - height }, { x: left + width, y: point.y + height * .25 }]; }
  private accessibleText(annotation: FactoryAnnotation): string { if (annotation.annotationType === 'text') return `${annotation.id}, text note, ${annotation.text}${annotation.locked ? ', locked' : ''}`; if (annotation.annotationType === 'leader') return `${annotation.id}, leader, ${annotation.text}${annotation.locked ? ', locked' : ''}`; if (annotation.annotationType === 'coordinate') return `${annotation.id}, coordinate marker${annotation.locked ? ', locked' : ''}`; const start = this.resolver.resolve(annotation.startAnchor, annotation.layoutId).point; const end = this.resolver.resolve(annotation.endAnchor, annotation.layoutId).point; const value = start && end ? formatDimension(dimensionValue(annotation.dimensionKind, start, end), annotation, this.project.getSettings()) : 'invalid reference'; return `${annotation.id}, ${annotation.dimensionKind} dimension, ${value}${annotation.locked ? ', locked' : ''}`; }
  private error(group: SVGGElement, point: GeometryPoint): void { const marker = svg('text'); marker.classList.add('factory-annotation__error'); marker.setAttribute('x', String(point.x)); marker.setAttribute('y', String(point.y)); marker.textContent = '\u26a0'; group.append(marker); }
  private arrow(id: string, start: boolean): SVGMarkerElement { const marker = svg('marker'); marker.id = id; marker.setAttribute('viewBox', '0 0 10 10'); marker.setAttribute('refX', start ? '2' : '8'); marker.setAttribute('refY', '5'); marker.setAttribute('markerWidth', '7'); marker.setAttribute('markerHeight', '7'); marker.setAttribute('markerUnits', 'strokeWidth'); marker.setAttribute('orient', start ? 'auto-start-reverse' : 'auto'); const path = svg('path'); path.setAttribute('d', start ? 'M 10 0 L 0 5 L 10 10' : 'M 0 0 L 10 5 L 0 10'); path.classList.add('factory-annotation__arrow'); marker.append(path); return marker; }
}
