import type { CanvasState } from '../../../models/canvas/CanvasState';
import type { AnnotationAnchor, LinearDimensionAnnotation, LinearDimensionKind } from '../../../models/factory/FactoryAnnotation';
import { DEFAULT_FACTORY_LAYOUT_ID } from '../../../models/workspace/Workspace';
import type { ProjectSessionService } from '../../../services/project/ProjectSessionService';
import type { FactoryAnnotationStore } from '../../../services/FactoryAnnotationStore';
import type { FactoryAnnotationCommandFactory } from '../../../services/history/FactoryAnnotationCommandFactory';
import type { AnnotationSnapService } from '../../../services/annotations/AnnotationSnapService';
import { defaultDimensionOffset, measurementValues } from '../../../services/annotations/LinearDimensionGeometry';
import { formatLength } from '../../../services/units/LengthUnitService';
import { screenToWorld, type Point } from '../canvas/ViewportTransform';

const NS = 'http://www.w3.org/2000/svg'; const svg = <K extends keyof SVGElementTagNameMap>(tag: K): SVGElementTagNameMap[K] => document.createElementNS(NS, tag);
export interface TemporaryMeasurement { readonly start: Point; readonly end: Point; readonly startAnchor: AnnotationAnchor; readonly endAnchor: AnnotationAnchor; }

export class TemporaryMeasurementController {
  private start: { point: Point; anchor: AnnotationAnchor } | null = null; private preview: { point: Point; anchor: AnnotationAnchor } | null = null; private completed: TemporaryMeasurement | null = null;
  public constructor(private readonly viewport: HTMLElement, private readonly layer: SVGGElement, private readonly state: CanvasState, private readonly snap: AnnotationSnapService, private readonly project: ProjectSessionService, private readonly store: FactoryAnnotationStore, private readonly commands: FactoryAnnotationCommandFactory, private readonly onStatus: (message: string) => void) { viewport.addEventListener('pointerdown', this.pointerDown, true); viewport.addEventListener('pointermove', this.pointerMove, true); document.addEventListener('keydown', this.keyDown); }
  public dispose(): void { this.viewport.removeEventListener('pointerdown', this.pointerDown, true); this.viewport.removeEventListener('pointermove', this.pointerMove, true); document.removeEventListener('keydown', this.keyDown); this.layer.replaceChildren(); }
  public getCompleted(): TemporaryMeasurement | null { return this.completed ? { ...this.completed, start: { ...this.completed.start }, end: { ...this.completed.end } } : null; }
  public clear(report = true): void { this.start = null; this.preview = null; this.completed = null; this.layer.replaceChildren(); if (report) this.onStatus('Temporary measurement cleared'); }
  public toolChanged(): void { if (this.state.tool !== 'measure') this.clear(false); else { this.start = null; this.preview = null; this.completed = null; this.render(); this.onStatus('Measure: select first point'); } }
  public createDimension(kind: LinearDimensionKind): LinearDimensionAnnotation | null { const value = this.completed; if (!value) { this.onStatus('Complete a measurement first'); return null; } const settings = this.project.getSettings(); const annotation: LinearDimensionAnnotation = { id: this.store.nextId(), layoutId: DEFAULT_FACTORY_LAYOUT_ID, annotationType: 'linearDimension', dimensionKind: kind, startAnchor: value.startAnchor, endAnchor: value.endAnchor, offset: defaultDimensionOffset(kind, value.start, value.end, settings.defaultDimensionOffset), textPosition: .5, textOverride: '', prefix: '', suffix: '', showUnit: true, precisionOverride: null, visible: true, locked: false, layer: settings.defaultDimensionLayer, note: '', createdUtc: new Date().toISOString() }; if (!this.commands.insert(annotation, `Create ${kind.toLowerCase()} dimension ${annotation.id}`)) return null; this.clear(false); this.onStatus(`${kind} dimension created: ${annotation.id}`); return annotation; }
  private readonly pointerDown = (event: PointerEvent): void => { if (this.state.tool !== 'measure' || event.button !== 0) return; const point = this.resolve(event); if (!this.start || this.completed) { this.start = point; this.preview = point; this.completed = null; this.onStatus('Measure: select second point'); } else { this.preview = point; this.completed = { start: { ...this.start.point }, end: { ...point.point }, startAnchor: this.start.anchor, endAnchor: point.anchor }; this.reportMeasurement(this.completed); } this.render(); event.preventDefault(); event.stopPropagation(); };
  private readonly pointerMove = (event: PointerEvent): void => { if (this.state.tool !== 'measure' || !this.start || this.completed) return; this.preview = this.resolve(event); this.render(); };
  private readonly keyDown = (event: KeyboardEvent): void => { if (this.state.tool !== 'measure' || event.key !== 'Escape') return; event.preventDefault(); this.clear(); };
  private resolve(event: PointerEvent): { point: Point; anchor: AnnotationAnchor } { const bounds = this.viewport.getBoundingClientRect(); let world = screenToWorld({ x: event.clientX - bounds.left, y: event.clientY - bounds.top }, this.state); const result = this.snap.resolve(world, this.state.zoom, event.altKey); world = result.point; if (event.shiftKey && this.start) { const dx = Math.abs(world.x - this.start.point.x); const dy = Math.abs(world.y - this.start.point.y); world = dx >= dy ? { x: world.x, y: this.start.point.y } : { x: this.start.point.x, y: world.y }; return { point: world, anchor: { kind: 'free', point: { ...world } } }; } return { point: result.point, anchor: result.anchor }; }
  private reportMeasurement(value: TemporaryMeasurement): void { const measured = measurementValues(value.start, value.end); const settings = this.project.getSettings(); const length = (number: number): string => formatLength(number, { modelUnit: settings.units.modelLengthUnit, displayUnit: settings.units.displayLengthUnit, precision: settings.units.displayPrecision, showTrailingZeros: settings.units.showTrailingZeros }); this.onStatus(`Distance ${length(measured.aligned)} · ΔX ${length(measured.horizontal)} · ΔY ${length(measured.vertical)} · ${measured.angleDegrees.toFixed(1)}°`); }
  private render(): void { this.layer.replaceChildren(); if (!this.start || !this.preview) return; const start = this.start.point; const end = this.preview.point; const measured = measurementValues(start, end); const settings = this.project.getSettings(); const length = (value: number): string => formatLength(value, { modelUnit: settings.units.modelLengthUnit, displayUnit: settings.units.displayLengthUnit, precision: settings.units.displayPrecision, showTrailingZeros: settings.units.showTrailingZeros }); const line = svg('line'); line.classList.add('temporary-measurement__line'); line.setAttribute('x1', String(start.x)); line.setAttribute('y1', String(start.y)); line.setAttribute('x2', String(end.x)); line.setAttribute('y2', String(end.y)); const horizontal = svg('line'); horizontal.classList.add('temporary-measurement__component'); horizontal.setAttribute('x1', String(start.x)); horizontal.setAttribute('y1', String(start.y)); horizontal.setAttribute('x2', String(end.x)); horizontal.setAttribute('y2', String(start.y)); const vertical = svg('line'); vertical.classList.add('temporary-measurement__component'); vertical.setAttribute('x1', String(end.x)); vertical.setAttribute('y1', String(start.y)); vertical.setAttribute('x2', String(end.x)); vertical.setAttribute('y2', String(end.y)); const text = svg('text'); text.classList.add('temporary-measurement__text'); text.setAttribute('x', String((start.x + end.x) / 2)); text.setAttribute('y', String((start.y + end.y) / 2 - 14 / this.state.zoom)); text.setAttribute('font-size', String(12 / this.state.zoom)); text.setAttribute('text-anchor', 'middle'); text.textContent = `${length(measured.aligned)}  ΔX ${length(measured.horizontal)}  ΔY ${length(measured.vertical)}  ∠ ${measured.angleDegrees.toFixed(1)}°`; const coordinates = svg('text'); coordinates.classList.add('temporary-measurement__coordinates'); coordinates.setAttribute('x', String((start.x + end.x) / 2)); coordinates.setAttribute('y', String((start.y + end.y) / 2 + 7 / this.state.zoom)); coordinates.setAttribute('font-size', String(10 / this.state.zoom)); coordinates.setAttribute('text-anchor', 'middle'); coordinates.textContent = `(${start.x.toFixed(1)}, ${start.y.toFixed(1)}) → (${end.x.toFixed(1)}, ${end.y.toFixed(1)})`; const startMarker = svg('circle'); startMarker.classList.add('temporary-measurement__point'); startMarker.setAttribute('cx', String(start.x)); startMarker.setAttribute('cy', String(start.y)); startMarker.setAttribute('r', String(4 / this.state.zoom)); const endMarker = svg('circle'); endMarker.classList.add('temporary-measurement__point'); endMarker.setAttribute('cx', String(end.x)); endMarker.setAttribute('cy', String(end.y)); endMarker.setAttribute('r', String(4 / this.state.zoom)); this.layer.append(horizontal, vertical, line, startMarker, endMarker, text, coordinates); }
}
