import type { CanvasState } from '../../../models/canvas/CanvasState';
import type { OperationStore } from '../../../services/OperationStore';
import { operationPositionFromPointer } from '../../../services/OperationPlacement';
import type { SnapService } from '../../../services/SnapService';
import { screenToWorld, type Point } from '../canvas/ViewportTransform';
import type { CommandFactory } from '../../../services/history/CommandFactory';
import type { SelectionController } from '../../../models/selection/Selection';
import type { AlignmentGuideController } from '../canvas/AlignmentGuideController';

interface ActiveDrag { readonly pointerId: number; readonly operationId: string; readonly offset: Point; readonly original: Point; readonly originals: readonly { readonly id: string; readonly point: Point }[]; pending: Point | null; frame: number; }
export class OperationInteractionController {
  private active: ActiveDrag | null = null;
  public constructor(private readonly viewport: HTMLElement, private readonly state: CanvasState, private readonly store: OperationStore, private readonly snap: SnapService, private readonly onStatus: (message: string) => void, private readonly commands: CommandFactory, private readonly selection: SelectionController, private readonly guides: AlignmentGuideController) {
    viewport.addEventListener('pointerdown', this.pointerDown); viewport.addEventListener('pointermove', this.pointerMove); viewport.addEventListener('pointerup', this.pointerUp); viewport.addEventListener('pointercancel', this.pointerCancel); viewport.addEventListener('lostpointercapture', this.lostCapture); document.addEventListener('keydown', this.keyDown);
  }
  public deleteSelection(): void { const selected = this.store.getSelectedOperation(); const result = selected ? this.commands.deleteOperation(selected.id) : 'none'; this.onStatus(result === 'deleted' ? 'Operation deleted' : result === 'locked' ? 'Operation is locked' : 'No operation selected'); }
  public cancelActiveDrag(): void { this.finish(false); }
  public dispose(): void { this.cancelActiveDrag(); this.viewport.removeEventListener('pointerdown', this.pointerDown); this.viewport.removeEventListener('pointermove', this.pointerMove); this.viewport.removeEventListener('pointerup', this.pointerUp); this.viewport.removeEventListener('pointercancel', this.pointerCancel); this.viewport.removeEventListener('lostpointercapture', this.lostCapture); document.removeEventListener('keydown', this.keyDown); }
  private local(event: PointerEvent): Point { const bounds = this.viewport.getBoundingClientRect(); return { x: event.clientX - bounds.left, y: event.clientY - bounds.top }; }
  private readonly pointerDown = (event: PointerEvent): void => {
    if (event.button !== 0 || this.state.tool !== 'select') return; const target = event.target instanceof Element ? event.target.closest<SVGGElement>('[data-operation-id]') : null; const id = target?.dataset.operationId; if (!id) return;
    event.preventDefault(); event.stopImmediatePropagation(); this.viewport.focus({ preventScroll: true }); const ref = { kind: 'operation' as const, id }; if (event.ctrlKey || event.metaKey) { const selected = this.selection.contains(ref); this.selection.toggle(ref); if (selected) { this.onStatus('Operation removed from selection'); return; } } else if (event.shiftKey) this.selection.add(ref); else if (this.selection.contains(ref)) this.selection.set(this.selection.getState().items, ref); else this.selection.select(ref); const operation = this.store.getOperation(id); if (!operation) return;
    if (operation.locked) { this.onStatus('Operation is locked'); return; } const world = screenToWorld(this.local(event), this.state);
    this.active = { pointerId: event.pointerId, operationId: id, offset: { x: world.x - operation.worldX, y: world.y - operation.worldY }, original: { x: operation.worldX, y: operation.worldY }, originals: this.selection.getState().items.filter((item) => item.kind === 'operation').map((item) => this.store.getOperation(item.id)).filter((item): item is NonNullable<typeof item> => Boolean(item && !item.locked)).map((item) => ({ id: item.id, point: { x: item.worldX, y: item.worldY } })), pending: null, frame: 0 };
    this.viewport.setPointerCapture(event.pointerId); this.guides.begin('operation', this.active.originals.map((item) => item.id)); target.classList.add('placed-operation--moving'); this.onStatus('Moving operation');
  };
  private readonly pointerMove = (event: PointerEvent): void => { if (!this.active || event.pointerId !== this.active.pointerId) return; event.preventDefault(); event.stopImmediatePropagation(); const world = screenToWorld(this.local(event), this.state); const raw = operationPositionFromPointer(world, this.active.offset); const guide = this.guides.resolve(raw.x - this.active.original.x, raw.y - this.active.original.y, this.snap.enabled, event.altKey); const dx = !event.altKey && this.snap.enabled && !guide.matchedX ? this.snap.snapValue(this.active.original.x + guide.dx) - this.active.original.x : guide.dx; const dy = !event.altKey && this.snap.enabled && !guide.matchedY ? this.snap.snapValue(this.active.original.y + guide.dy) - this.active.original.y : guide.dy; this.active.pending = { x: this.active.original.x + dx, y: this.active.original.y + dy }; if (!this.active.frame) this.active.frame = requestAnimationFrame(this.flush); };
  private readonly pointerUp = (event: PointerEvent): void => { if (this.active?.pointerId === event.pointerId) { event.stopImmediatePropagation(); this.finish(true); } };
  private readonly pointerCancel = (event: PointerEvent): void => { if (this.active?.pointerId === event.pointerId) this.finish(false); };
  private readonly lostCapture = (event: PointerEvent): void => { if (this.active?.pointerId === event.pointerId) this.finish(false); };
  private readonly keyDown = (event: KeyboardEvent): void => { if (event.key === 'Escape' && this.active) { event.preventDefault(); this.finish(false); } else if ((event.key === 'Enter' || event.key === ' ') && event.target instanceof Element) { const id = event.target.closest<SVGGElement>('[data-operation-id]')?.dataset.operationId; if (id) { event.preventDefault(); this.store.selectOperation(id); } } };
  private readonly flush = (): void => { if (!this.active) return; this.active.frame = 0; const pending = this.active.pending; this.active.pending = null; if (pending) { const dx = pending.x - this.active.original.x; const dy = pending.y - this.active.original.y; for (const item of this.active.originals) this.store.moveOperation(item.id, item.point.x + dx, item.point.y + dy); } };
  private finish(commit: boolean): void { const active = this.active; if (!active) return; if (active.frame) cancelAnimationFrame(active.frame); if (commit && active.pending) { const dx = active.pending.x - active.original.x; const dy = active.pending.y - active.original.y; for (const item of active.originals) this.store.moveOperation(item.id, item.point.x + dx, item.point.y + dy); } if (!commit) for (const item of active.originals) this.store.moveOperation(item.id, item.point.x, item.point.y); const final = this.store.getOperation(active.operationId); const changed = Boolean(commit && final && (final.worldX !== active.original.x || final.worldY !== active.original.y)); if (changed && final) this.commands.commitOperationGroupMove(active.originals.map((item) => ({ id: item.id, before: item.point, after: { x: this.store.getOperation(item.id)?.worldX ?? item.point.x, y: this.store.getOperation(item.id)?.worldY ?? item.point.y } }))); this.active = null; this.guides.clear(); this.viewport.querySelector(`[data-operation-id="${active.operationId}"]`)?.classList.remove('placed-operation--moving'); if (this.viewport.hasPointerCapture(active.pointerId)) this.viewport.releasePointerCapture(active.pointerId); this.onStatus(commit ? changed ? `${active.originals.length} operation${active.originals.length === 1 ? '' : 's'} moved` : 'Operation position unchanged' : 'Operation move cancelled'); }
}
