import { revealConnection } from '../../core/events/connectionEvents';
import { revealOperation } from '../../core/events/operationEvents';
import { revealResource } from '../../core/events/resourceEvents';
import { reportStatus } from '../../core/events/uiEvents';
import type { SelectionController, SelectionItem } from '../../models/selection/Selection';
import type { ConnectionStore } from '../../services/ConnectionStore';
import { validateProcessConnections } from '../../services/ConnectionValidation';
import type { FactoryStructureStore } from '../../services/FactoryStructureStore';
import { validateFactoryStructure } from '../../services/FactoryStructureValidation';
import type { OperationStore } from '../../services/OperationStore';
import type { ProjectSessionService } from '../../services/project/ProjectSessionService';
import type { ResourceStore } from '../../services/ResourceStore';
import { validateResources } from '../../services/ResourceValidation';
import type { WorkspaceStore } from '../../services/WorkspaceStore';
import { actionButton, element } from '../../ui/dom';
import type { CommandFactory } from '../../services/history/CommandFactory';
import type { FactoryRouteStore } from '../../services/FactoryRouteStore';
import { validateFactoryRoutes } from '../../services/FactoryRouteValidation';
import { factoryRouteDistance } from '../../services/geometry/FactoryRouteGeometry';
import { revealFactoryRoute } from '../../core/events/factoryRouteEvents';

export interface ProjectExplorerController { readonly element: HTMLElement; dispose(): void; }

export function createProjectExplorer(operationsStore: OperationStore, connectionsStore: ConnectionStore, resourcesStore: ResourceStore, structureStore: FactoryStructureStore, routeStore: FactoryRouteStore, workspaceStore: WorkspaceStore, project: ProjectSessionService, selection: SelectionController, commands: CommandFactory): ProjectExplorerController {
  const explorer = element('section', 'panel-section project-explorer'); explorer.append(element('h2', 'panel-heading', 'Project Explorer')); const tree = element('nav', 'project-tree'); tree.setAttribute('aria-label', 'Project explorer'); const list = element('ul');
  const root = element('li', 'project-tree__root'); const rootButton = actionButton('Project', 'tree-item tree-item--label project-root-button'); rootButton.addEventListener('click', () => selection.select({ kind: 'project', id: project.getMetadata().id })); root.append(rootButton);
  const process = element('li'); const processDetails = element('details', 'process-tree'); processDetails.open = true; const processSummary = element('summary'); const operationHeading = element('h3', 'process-group-heading'); const operations = element('ol', 'process-operation-list'); const connectionHeading = element('h3', 'process-group-heading'); const connections = element('ul', 'process-connection-list'); const normalize = actionButton('Normalize Sequence', 'normalize-sequence'); processDetails.append(processSummary, operationHeading, operations, connectionHeading, connections, normalize); process.append(processDetails);
  const layout = element('li'); const layoutDetails = element('details', 'process-tree'); layoutDetails.open = true; const layoutSummary = element('summary'); const boundaryHeading = element('h3', 'process-group-heading'); const boundaries = element('ul', 'process-connection-list'); const resourceHeading = element('h3', 'process-group-heading'); const resources = element('ol', 'process-operation-list resource-instance-list'); const wallHeading = element('h3', 'process-group-heading'); const walls = element('ul', 'process-connection-list'); const areaHeading = element('h3', 'process-group-heading'); const areas = element('ul', 'process-connection-list'); const aisleHeading = element('h3', 'process-group-heading'); const aisles = element('ul', 'process-connection-list'); const routeHeading = element('h3', 'process-group-heading'); const routes = element('ul', 'process-connection-list'); layoutDetails.append(layoutSummary, boundaryHeading, boundaries, resourceHeading, resources, wallHeading, walls, areaHeading, areas, aisleHeading, aisles, routeHeading, routes); layout.append(layoutDetails); list.append(root, process, layout); tree.append(list); explorer.append(tree);
  normalize.addEventListener('click', () => reportStatus(commands.normalizeOperationSequences() ? 'Operation sequence normalized' : 'Operation sequence already normalized'));
  const selectFromExplorer = (event: MouseEvent, item: SelectionItem): void => { workspaceStore.activate(['resource', 'boundary', 'wall', 'area', 'aisle', 'factoryRoute'].includes(item.kind) ? 'factoryLayout' : 'processFlow'); if (event.ctrlKey || event.metaKey) selection.toggle(item); else if (event.shiftKey) selection.add(item); else selection.select(item); };
  const itemButton = (label: string, item: SelectionItem, reveal?: () => void): HTMLButtonElement => { const button = actionButton(label, 'process-connection-entry'); button.classList.toggle('process-connection-entry--selected', selection.contains(item)); button.addEventListener('click', (event) => { selectFromExplorer(event, item); reveal?.(); }); return button; };
  const appendEntry = (container: HTMLElement, button: HTMLButtonElement): void => { const entry = element('li'); entry.append(button); container.append(entry); };
  const render = (): void => {
    const projectState = project.getState(); rootButton.textContent = `▾ ${projectState.metadata.name}${projectState.dirty ? ' *' : ''} (${projectState.metadata.id}) — ${operationsStore.getOperationCount()} ops, ${connectionsStore.getConnectionCount()} links, ${resourcesStore.getResourceCount()} resources`; rootButton.classList.toggle('project-root-button--selected', selection.getSelection().kind === 'project');
    const sortedOperations = operationsStore.sortedOperations(); const sortedConnections = connectionsStore.sortedConnections(); const processHealth = validateProcessConnections(sortedOperations, sortedConnections); processSummary.textContent = `Process Flow — ${sortedOperations.length} operations, ${sortedConnections.length} connections${processHealth.errors ? ' ⛔' : processHealth.warnings ? ' ⚠' : ''}`; operationHeading.textContent = `Operations (${sortedOperations.length})`; connectionHeading.textContent = `Connections (${sortedConnections.length})`; operations.replaceChildren(); connections.replaceChildren();
    for (const operation of sortedOperations) appendEntry(operations, itemButton(`OP ${operation.sequence} ${operation.name}`, { kind: 'operation', id: operation.id }, () => revealOperation(operation.id))); if (!sortedOperations.length) operations.append(element('li', 'process-operation-list__empty', 'No operations placed'));
    for (const connection of sortedConnections) { const source = operationsStore.getOperation(connection.sourceOperationId); const target = operationsStore.getOperation(connection.targetOperationId); appendEntry(connections, itemButton(`${connection.id} — OP ${source?.sequence ?? '?'} → OP ${target?.sequence ?? '?'}`, { kind: 'connection', id: connection.id }, () => revealConnection(connection.id))); } if (!sortedConnections.length) connections.append(element('li', 'process-operation-list__empty', 'No process connections'));
    const instances = [...resourcesStore.getPlacedResources()].sort((left, right) => left.id.localeCompare(right.id)); const resourceHealth = validateResources(instances, resourcesStore.getTemplates(), (id) => operationsStore.getAssignmentCount(id)); const structureHealth = validateFactoryStructure(instances, structureStore); const routeHealth = validateFactoryRoutes({ resources: instances, structure: structureStore, routes: routeStore }); layoutSummary.textContent = `Factory Layout — ${instances.length} resources, ${structureStore.getWalls().length} walls, ${structureStore.getAreas().length} areas, ${structureStore.getAisles().length} aisles, ${routeStore.getCount()} routes`; boundaries.replaceChildren(); resources.replaceChildren(); walls.replaceChildren(); areas.replaceChildren(); aisles.replaceChildren(); routes.replaceChildren();
    const boundaryItems = structureStore.getBoundaries(); boundaryHeading.textContent = `Boundary (${boundaryItems.length})`; for (const boundary of boundaryItems) appendEntry(boundaries, itemButton(`${boundary.name}${structureHealth.issues.some((issue) => issue.entityId === boundary.id) ? ' ⚠' : ''}`, { kind: 'boundary', id: boundary.id })); if (!boundaryItems.length) boundaries.append(element('li', 'process-operation-list__empty', 'No factory boundary'));
    resourceHeading.textContent = `Physical Resources (${instances.length})`; for (const resource of instances) { const issues = resourceHealth.issues.filter((issue) => issue.resourceId === resource.id || issue.relatedResourceIds?.includes(resource.id)); const marker = issues.some((issue) => issue.severity === 'error') ? ' ⛔' : issues.length ? ' ⚠' : ''; appendEntry(resources, itemButton(`${resource.id} — ${resource.name} · ${resource.width}×${resource.depth} @ ${resource.rotationDegrees}°${marker}`, { kind: 'resource', id: resource.id }, () => revealResource(resource.id))); } if (!instances.length) resources.append(element('li', 'process-operation-list__empty', 'No physical resources placed'));
    const addStructures = <T extends { readonly id: string; readonly name: string }>(items: readonly T[], container: HTMLElement, kind: 'wall' | 'area' | 'aisle', detail: (item: T) => string): void => { for (const item of items) appendEntry(container, itemButton(`${item.id} — ${item.name} · ${detail(item)}`, { kind, id: item.id })); if (!items.length) container.append(element('li', 'process-operation-list__empty', `No ${kind}s`)); };
    const wallItems = structureStore.getWalls(); wallHeading.textContent = `Walls (${wallItems.length})`; addStructures(wallItems, walls, 'wall', (item) => item.wallType); const areaItems = structureStore.getAreas(); areaHeading.textContent = `Areas (${areaItems.length})`; addStructures(areaItems, areas, 'area', (item) => item.areaType); const aisleItems = structureStore.getAisles(); aisleHeading.textContent = `Aisles (${aisleItems.length})`; addStructures(aisleItems, aisles, 'aisle', (item) => `${item.aisleType} · ${item.width} wide`); const routeItems = [...routeStore.getRoutes()].sort((left, right) => left.id.localeCompare(right.id)); routeHeading.textContent = `Factory Routes (${routeItems.length})`; const resolver = { getResource: (id: string) => resourcesStore.getResource(id), getArea: (id: string) => structureStore.getArea(id) }; for (const route of routeItems) { const routeIssues = routeHealth.issues.filter((issue) => issue.routeId === route.id); const marker = routeIssues.some((issue) => issue.severity === 'error') ? ' ⛔' : routeIssues.length ? ' ⚠' : ''; appendEntry(routes, itemButton(`${route.id} — ${route.name} · ${route.routeType} · ${route.direction} · ${factoryRouteDistance(route, resolver).toFixed(0)}${marker}`, { kind: 'factoryRoute', id: route.id }, () => revealFactoryRoute(route.id))); } if (!routeItems.length) routes.append(element('li', 'process-operation-list__empty', 'No Factory Routes'));
  };
  const unsubscribers = [operationsStore.subscribe(render), connectionsStore.subscribe(render), resourcesStore.subscribe(render), structureStore.subscribe(render), routeStore.subscribe(render), workspaceStore.subscribe(render), project.subscribe(render), selection.subscribe(render)]; render(); return { element: explorer, dispose: () => unsubscribers.forEach((unsubscribe) => unsubscribe()) };
}
