import { TIMING_CATEGORIES } from '../../core/constants/operationTemplates';
import { revealConnection } from '../../core/events/connectionEvents';
import { revealOperation } from '../../core/events/operationEvents';
import { revealResource } from '../../core/events/resourceEvents';
import { reportStatus } from '../../core/events/uiEvents';
import type { ConnectionType, ProcessConnection } from '../../models/connections/ProcessConnection';
import type { OperationInstance } from '../../models/operations/OperationInstance';
import type { OperationType } from '../../models/operations/OperationTemplate';
import type { SelectionController } from '../../models/selection/Selection';
import type { ConnectionStore } from '../../services/ConnectionStore';
import { validateProcessConnections } from '../../services/ConnectionValidation';
import { MIN_OPERATION_HEIGHT, MIN_OPERATION_WIDTH, type OperationStore } from '../../services/OperationStore';
import { validateOperations } from '../../services/OperationValidation';
import { routeBendCount, routeLength } from '../../services/OrthogonalRouter';
import { MIN_RESOURCE_DEPTH, MIN_RESOURCE_WIDTH, normalizeAngle, type ResourceStore } from '../../services/ResourceStore';
import { CLEARANCE_CATEGORIES, type ClearanceCategory, type ResourceClearance } from '../../models/resources/ResourceClearance';
import { issueIdsForResource, validateFactoryLayout } from '../../services/FactoryLayoutValidation';
import { validateResources } from '../../services/ResourceValidation';
import type { WorkspaceStore } from '../../services/WorkspaceStore';
import type { ProjectSessionService } from '../../services/project/ProjectSessionService';
import { actionButton, element } from '../../ui/dom';
import type { CommandFactory } from '../../services/history/CommandFactory';
import type { ApplicationClipboardService } from '../../services/editing/ApplicationClipboardService';
import type { GeometrySelectionService } from '../../services/geometry/GeometrySelectionService';
import type { GeometryEditingService, GeometryCommand } from '../../services/geometry/GeometryEditingService';
import { aggregateBounds } from '../../services/geometry/GeometryBounds';
import { PROJECT_SCHEMA_VERSION } from '../../models/project/ProjectDocument';
import type { FactoryStructureStore } from '../../services/FactoryStructureStore';
import { validateFactoryStructure } from '../../services/FactoryStructureValidation';
import { FACTORY_WALL_TYPES } from '../../models/factory/FactoryWall';
import { FACTORY_AREA_TYPES, RESOURCE_PLACEMENT_POLICIES } from '../../models/factory/FactoryArea';
import { FACTORY_AISLE_DIRECTIONS, FACTORY_AISLE_TYPES } from '../../models/factory/FactoryAisle';
import { polygonArea, polylineLength, wallLength } from '../../services/geometry/FactoryStructureGeometry';
import type { FactoryRouteStore } from '../../services/FactoryRouteStore';
import type { FactoryRouteCommandFactory } from '../../services/history/FactoryRouteCommandFactory';
import { FACTORY_ROUTE_DIRECTIONS, FACTORY_ROUTE_TYPES, type FactoryRoute, type FactoryRouteDirection, type FactoryRouteType } from '../../models/factory/FactoryRoute';
import { estimatedTravelTimeSeconds, factoryRouteDistance, resolveFactoryRoutePolyline } from '../../services/geometry/FactoryRouteGeometry';
import { routeValidationIssues, validateFactoryRoutes } from '../../services/FactoryRouteValidation';
import { revealFactoryRoute } from '../../core/events/factoryRouteEvents';

export interface RightSidebarController { readonly element: HTMLElement; dispose(): void; }

function section(title: string, content: HTMLElement): HTMLDetailsElement { const details = element('details', 'inspector-section'); details.open = true; details.append(element('summary', '', title), content); return details; }
function field(labelText: string, control: HTMLElement): HTMLLabelElement { const label = element('label', 'property-field'); label.append(element('span', '', labelText), control); return label; }
function input(type: 'text' | 'number', step = '1', minimum?: number): HTMLInputElement { const control = element('input', 'property-input'); control.type = type; if (type === 'number') control.step = step; if (minimum !== undefined) control.min = String(minimum); return control; }
function output(value: string): HTMLOutputElement { return element('output', 'property-output', value); }
function option(label: string, value = label): HTMLOptionElement { const node = element('option', '', label); node.value = value; return node; }
function checkbox(label: string): HTMLInputElement { const node = element('input', 'property-checkbox'); node.type = 'checkbox'; node.setAttribute('aria-label', label); return node; }
function toggle(labelText: string, control: HTMLInputElement): HTMLLabelElement { const label = element('label', 'property-toggle'); label.append(control, element('span', '', labelText)); return label; }
function summaryRow(container: HTMLElement, label: string, value: string): void { container.append(element('span', '', label), element('strong', '', value)); }

interface ValidationListEntry {
  readonly severity: 'error' | 'warning';
  readonly location: string;
  readonly message: string;
  readonly navigate: () => void;
}

export function createRightSidebar(resources: ResourceStore, operations: OperationStore, connections: ConnectionStore, structure: FactoryStructureStore, routes: FactoryRouteStore, workspaces: WorkspaceStore, selection: SelectionController, requestDelete: (resourceId: string) => void, project: ProjectSessionService, commands: CommandFactory, routeCommands: FactoryRouteCommandFactory, editing: ApplicationClipboardService, geometrySelection: GeometrySelectionService, geometryEditing: GeometryEditingService): RightSidebarController {
  const sidebar = element('aside', 'sidebar sidebar--right'); sidebar.setAttribute('aria-label', 'Inspector panels');
  const properties = element('div', 'properties-content'); const summary = element('div', 'summary-grid'); const validation = element('div', 'validation-summary');
  sidebar.append(section('Validation Issues', validation), section('Properties', properties), section('Selection Summary', summary));
  const bindNumber = (control: HTMLInputElement, commit: (value: number) => boolean, minimum: number, integer = false): void => { let committed = Number(control.value); const run = (): void => { const value = Number(control.value); const valid = control.value.trim() !== '' && Number.isFinite(value) && value >= minimum && (!integer || Number.isInteger(value)); const accepted = valid && (Object.is(value, committed) || commit(value)); if (accepted) committed = value; control.setAttribute('aria-invalid', String(!accepted)); }; control.addEventListener('change', run); control.addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); run(); } }); };
  const bindText = (control: HTMLInputElement, commit: (value: string) => boolean): void => { let committed = control.value.trim(); const run = (): void => { const value = control.value.trim(); const accepted = value === committed || commit(value); if (accepted) committed = value; control.setAttribute('aria-invalid', String(!accepted)); }; control.addEventListener('change', run); control.addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); run(); } }); };

  const renderResource = (): void => {
    const resource = resources.getSelectedResource(); if (!resource) return;
    const form = element('form', 'properties-form resource-instance-properties'); form.addEventListener('submit', (event) => event.preventDefault());
    const name = input('text'); name.value = resource.name; bindText(name, (value) => commands.updateResource(resource.id, { name: value }));
    const x = input('number'); x.value = String(resource.worldX); bindNumber(x, (value) => commands.updateResource(resource.id, { worldX: value }), Number.NEGATIVE_INFINITY);
    const y = input('number'); y.value = String(resource.worldY); bindNumber(y, (value) => commands.updateResource(resource.id, { worldY: value }), Number.NEGATIVE_INFINITY);
    const width = input('number', '5', MIN_RESOURCE_WIDTH); width.value = String(resource.width); bindNumber(width, (value) => commands.updateResource(resource.id, { width: value }), MIN_RESOURCE_WIDTH);
    const depth = input('number', '5', MIN_RESOURCE_DEPTH); depth.value = String(resource.depth); bindNumber(depth, (value) => commands.updateResource(resource.id, { depth: value }), MIN_RESOURCE_DEPTH);
    const rotation = input('number', '5'); rotation.value = String(resource.rotationDegrees); bindNumber(rotation, (value) => commands.updateResource(resource.id, { rotationDegrees: value }), Number.NEGATIVE_INFINITY);
    const rotationActions = element('div', 'resource-property-actions');
    for (const [label, delta] of [['Rotate left 90°', -90], ['Rotate right 90°', 90], ['Reset 0°', -resource.rotationDegrees]] as const) { const button = actionButton(label, 'secondary-button'); button.disabled = resource.locked; button.addEventListener('click', () => commands.updateResource(resource.id, { rotationDegrees: normalizeAngle(resource.rotationDegrees + delta) }, `${label} ${resource.id}`)); rotationActions.append(button); }
    const capacity = input('number', '1', 1); capacity.value = String(resource.capacity); bindNumber(capacity, (value) => commands.updateResource(resource.id, { capacity: value }), 1, true); x.disabled = resource.locked; y.disabled = resource.locked; width.disabled = resource.locked; depth.disabled = resource.locked; rotation.disabled = resource.locked;
    const active = checkbox('Active'); active.checked = resource.active; active.addEventListener('change', () => commands.updateResource(resource.id, { active: active.checked })); const visible = checkbox('Visible'); visible.checked = resource.visible; visible.addEventListener('change', () => commands.updateResource(resource.id, { visible: visible.checked })); const locked = checkbox('Locked'); locked.checked = resource.locked; locked.addEventListener('change', () => commands.updateResource(resource.id, { locked: locked.checked })); const toggles = element('div', 'property-toggles'); toggles.append(toggle('Active', active), toggle('Visible', visible), toggle('Locked', locked));
    const help = element('p', 'property-help', 'For additional machinery capacity, normally add another physical resource instance instead of increasing capacity.'); const actions = element('div', 'resource-property-actions'); const duplicate = actionButton('Duplicate Resource', 'secondary-button'); duplicate.setAttribute('aria-label', 'Duplicate selected physical resource'); duplicate.addEventListener('click', () => { const copy = commands.duplicateResource(resource.id); reportStatus(copy ? `Resource duplicated: ${copy.id}` : 'Resource could not be duplicated'); }); const remove = actionButton('Delete Resource', 'secondary-button resource-delete-button'); remove.addEventListener('click', () => requestDelete(resource.id)); actions.append(duplicate, remove);
    const clearance = element('fieldset', 'clearance-properties'); clearance.append(element('legend', '', 'Clearance envelope'));
    const clearanceEnabled = checkbox('Clearance enabled'); clearanceEnabled.checked = resource.clearance.enabled; clearanceEnabled.disabled = resource.locked;
    const updateClearance = (patch: Partial<ResourceClearance>, description: string): boolean => commands.updateResource(resource.id, { clearance: { ...resource.clearance, ...patch } }, description);
    clearanceEnabled.addEventListener('change', () => updateClearance({ enabled: clearanceEnabled.checked }, `${clearanceEnabled.checked ? 'Enable' : 'Disable'} clearance ${resource.id}`));
    clearance.append(toggle('Enabled', clearanceEnabled));
    for (const [label, key] of [['Left', 'left'], ['Right', 'right'], ['Top', 'top'], ['Bottom', 'bottom']] as const) { const control = input('number', '5', 0); control.value = String(resource.clearance[key]); control.disabled = resource.locked; bindNumber(control, (value) => updateClearance({ [key]: value }, `Set ${key} clearance ${resource.id}`), 0); clearance.append(field(label, control)); }
    const category = element('select', 'property-input'); CLEARANCE_CATEGORIES.forEach((value) => category.append(option(value[0].toUpperCase() + value.slice(1), value))); category.value = resource.clearance.category; category.disabled = resource.locked; category.addEventListener('change', () => updateClearance({ category: category.value as ClearanceCategory }, `Set clearance category ${resource.id}`)); clearance.append(field('Category', category));
    const clearanceNote = input('text'); clearanceNote.value = resource.clearance.note; clearanceNote.disabled = resource.locked; bindText(clearanceNote, (value) => updateClearance({ note: value }, `Set clearance note ${resource.id}`)); clearance.append(field('Note', clearanceNote));
    const equal = input('number', '5', 0); equal.placeholder = 'Equal distance'; equal.disabled = resource.locked; const clearanceActions = element('div', 'resource-property-actions'); const applyEqual = actionButton('Apply equal', 'secondary-button'); applyEqual.disabled = resource.locked; applyEqual.addEventListener('click', () => { const value = Number(equal.value); if (Number.isFinite(value) && value >= 0) updateClearance({ enabled: true, left: value, right: value, top: value, bottom: value }, `Set equal clearance ${resource.id}`); }); const clear = actionButton('Clear', 'secondary-button'); clear.disabled = resource.locked; clear.addEventListener('click', () => updateClearance({ enabled: false, left: 0, right: 0, top: 0, bottom: 0 }, `Clear clearance ${resource.id}`)); clearanceActions.append(equal, applyEqual, clear); for (const value of [250, 500, 1000]) { const preset = actionButton(`${value} mm`, 'secondary-button'); preset.disabled = resource.locked; preset.addEventListener('click', () => updateClearance({ enabled: true, left: value, right: value, top: value, bottom: value }, `Apply ${value} mm clearance preset ${resource.id}`)); clearanceActions.append(preset); } clearance.append(clearanceActions);
    const layoutSummary = validateFactoryLayout(resources.getPlacedResources()); const related = layoutSummary.issues.filter((issue) => issue.resourceIds.includes(resource.id)); const relationships = element('div', 'resource-layout-issues'); relationships.append(element('strong', '', 'Layout relationships')); if (related.length) for (const issue of related) relationships.append(element('p', `validation-${issue.severity}`, issue.message)); else relationships.append(element('p', 'property-help', 'No footprint or clearance overlaps.'));
    form.append(field('Resource ID', output(resource.id)), field('Template ID', output(resource.templateId)), field('Name', name), field('Resource type', output(resource.resourceType)), field('X centre', x), field('Y centre', y), field('Physical width', width), field('Physical depth', depth), field('Rotation (degrees)', rotation), rotationActions, field('Capacity', capacity), field('Assigned operations', output(String(operations.getAssignmentCount(resource.id)))), toggles, clearance, relationships, help, actions); properties.replaceChildren(form);
  };

  const renderOperation = (): void => {
    const operation = operations.getSelectedOperation(); if (!operation) return;
    const form = element('form', 'properties-form operation-properties'); form.addEventListener('submit', (event) => event.preventDefault()); const name = input('text'); name.value = operation.name; bindText(name, (value) => commands.updateOperation(operation.id, { name: value }));
    const type = element('select', 'property-input'); [...new Set(operations.getTemplates().map((template) => template.operationType))].forEach((value) => type.append(option(value))); type.value = operation.operationType; type.addEventListener('change', () => commands.updateOperation(operation.id, { operationType: type.value as OperationType }));
    const timing = element('select', 'property-input'); TIMING_CATEGORIES.forEach((value) => timing.append(option(value))); timing.value = operation.timingCategory; timing.addEventListener('change', () => commands.updateOperation(operation.id, { timingCategory: timing.value as OperationInstance['timingCategory'] }));
    const cycle = input('number', '0.001', 0.001); cycle.value = String(operation.cycleTimeSeconds); bindNumber(cycle, (value) => commands.updateOperation(operation.id, { cycleTimeSeconds: value }), 0.001); const sequence = input('number', '1', 1); sequence.value = String(operation.sequence); bindNumber(sequence, (value) => commands.updateOperation(operation.id, { sequence: value }), 1, true);
    const assignment = element('select', 'property-input'); assignment.append(option('Unassigned', '')); for (const resource of resources.getAssignableResources()) assignment.append(option(`${resource.id} — ${resource.name}`, resource.id)); assignment.value = operation.assignedResourceId && resources.getResource(operation.assignedResourceId)?.active ? operation.assignedResourceId : ''; assignment.addEventListener('change', () => { const resource = assignment.value ? resources.getResource(assignment.value) : undefined; if (assignment.value && !resource?.active) { reportStatus('Inactive resource cannot be assigned'); return; } commands.updateOperation(operation.id, { assignedResourceId: assignment.value || null }); reportStatus(assignment.value ? `Operation assigned to ${assignment.value}` : 'Operation unassigned'); });
    const assigned = operation.assignedResourceId ? resources.getResource(operation.assignedResourceId) : undefined; const assignedDetails = output(assigned ? `${assigned.id} — ${assigned.name} — ${assigned.resourceType} — ${assigned.active ? 'Active' : 'Inactive'} — Factory Layout` : 'Unassigned'); const locate = actionButton('Locate in Factory Layout', 'secondary-button'); locate.disabled = !assigned; locate.addEventListener('click', () => { if (!assigned) return; workspaces.activate('factoryLayout'); resources.selectResource(assigned.id); revealResource(assigned.id); reportStatus('Assigned resource located in Factory Layout'); });
    const notes = element('textarea', 'property-input property-textarea'); notes.value = operation.notes; notes.rows = 3; notes.addEventListener('change', () => commands.updateOperation(operation.id, { notes: notes.value }));
    const x = input('number'); x.value = String(operation.worldX); bindNumber(x, (value) => commands.updateOperation(operation.id, { worldX: value }), Number.NEGATIVE_INFINITY); const y = input('number'); y.value = String(operation.worldY); bindNumber(y, (value) => commands.updateOperation(operation.id, { worldY: value }), Number.NEGATIVE_INFINITY); const width = input('number', '5', MIN_OPERATION_WIDTH); width.value = String(operation.width); bindNumber(width, (value) => commands.updateOperation(operation.id, { width: value }), MIN_OPERATION_WIDTH); const height = input('number', '5', MIN_OPERATION_HEIGHT); height.value = String(operation.height); bindNumber(height, (value) => commands.updateOperation(operation.id, { height: value }), MIN_OPERATION_HEIGHT); x.disabled = operation.locked; y.disabled = operation.locked;
    const locked = checkbox('Locked'); locked.checked = operation.locked; locked.addEventListener('change', () => commands.updateOperation(operation.id, { locked: locked.checked })); const visible = checkbox('Visible'); visible.checked = operation.visible; visible.addEventListener('change', () => commands.updateOperation(operation.id, { visible: visible.checked })); const toggles = element('div', 'property-toggles'); toggles.append(toggle('Locked', locked), toggle('Visible', visible));
    form.append(field('Operation name', name), field('Operation type', type), field('Timing category', timing), field('Cycle time (seconds)', cycle), field('Sequence', sequence), field('Assigned Resource', assignment), field('Assigned physical resource', assignedDetails), locate, field('Notes', notes), field('X position', x), field('Y position', y), field('Width', width), field('Height', height), toggles); properties.replaceChildren(form);
  };

  const renderConnection = (connection: ProcessConnection): void => {
    const form = element('form', 'properties-form connection-properties'); form.addEventListener('submit', (event) => event.preventDefault()); const sourceOperation = operations.getOperation(connection.sourceOperationId); const targetOperation = operations.getOperation(connection.targetOperationId);
    const type = element('select', 'property-input'); (['Standard', 'Rework', 'Alternate', 'Information'] as const).forEach((value) => type.append(option(value))); type.value = connection.connectionType; type.addEventListener('change', () => reportStatus(commands.updateConnection(connection.id, { connectionType: type.value as ConnectionType }) ? 'Connection type updated' : 'Duplicate Standard connection not permitted'));
    const label = input('text'); label.maxLength = 120; label.value = connection.label; bindText(label, (value) => commands.updateConnection(connection.id, { label: value }));
    const locked = checkbox('Locked'); locked.checked = connection.locked; locked.addEventListener('change', () => { commands.updateConnection(connection.id, { locked: locked.checked }); reportStatus(`Connection ${locked.checked ? 'locked' : 'unlocked'}`); }); const visible = checkbox('Visible'); visible.checked = connection.visible; visible.addEventListener('change', () => { commands.updateConnection(connection.id, { visible: visible.checked }); reportStatus(`Connection ${visible.checked ? 'shown' : 'hidden'}`); }); const toggles = element('div', 'property-toggles'); toggles.append(toggle('Locked', locked), toggle('Visible', visible));
    const actions = element('div', 'connection-property-actions'); const reverse = actionButton('Reverse Direction', 'secondary-button'); const remove = actionButton('Delete Connection', 'secondary-button connection-delete-button'); reverse.addEventListener('click', () => { const result = commands.reverseConnection(connection.id); reportStatus(result === 'updated' ? 'Connection reversed' : result === 'duplicate' ? 'Cannot reverse: duplicate Standard connection' : result === 'locked' ? 'Connection is locked' : 'Connection not found'); }); remove.addEventListener('click', () => { const result = commands.deleteConnection(connection.id); reportStatus(result === 'deleted' ? 'Connection deleted' : result === 'locked' ? 'Connection is locked' : 'Connection not found'); }); actions.append(reverse, remove);
    form.append(field('Connection ID', output(connection.id)), field('Source operation', output(sourceOperation ? `OP ${sourceOperation.sequence} — ${sourceOperation.name}` : connection.sourceOperationId)), field('Target operation', output(targetOperation ? `OP ${targetOperation.sequence} — ${targetOperation.name}` : connection.targetOperationId)), field('Connection type', type), field('Label', label), field('Source anchor', output(`${connection.sourceAnchor.side} @ ${connection.sourceAnchor.offset.toFixed(3)}`)), field('Target anchor', output(`${connection.targetAnchor.side} @ ${connection.targetAnchor.offset.toFixed(3)}`)), field('Route status', output(connection.routeStatus === 'clear' ? 'Clear route' : 'Fallback routing warning')), field('Route length', output(`${routeLength(connection.routePoints).toFixed(1)} units`)), field('Bend count', output(String(routeBendCount(connection.routePoints)))), toggles, actions); properties.replaceChildren(form);
  };

  const renderFactoryRoute = (route: FactoryRoute): void => {
    const resolver = { getResource: (id: string) => resources.getResource(id), getArea: (id: string) => structure.getArea(id) };
    const routeHealth = validateFactoryRoutes({ resources: resources.getPlacedResources(), structure, routes });
    const issues = routeValidationIssues(route.id, routeHealth);
    const form = element('form', 'properties-form factory-route-properties'); form.addEventListener('submit', (event) => event.preventDefault());
    const name = input('text'); name.value = route.name; name.disabled = route.locked; bindText(name, (value) => routeCommands.updateRoute(route.id, { name: value }));
    const type = element('select', 'property-input'); FACTORY_ROUTE_TYPES.forEach((value) => type.append(option(value))); type.value = route.routeType; type.disabled = route.locked; type.addEventListener('change', () => routeCommands.updateRoute(route.id, { routeType: type.value as FactoryRouteType }));
    const direction = element('select', 'property-input'); FACTORY_ROUTE_DIRECTIONS.forEach((value) => direction.append(option(value))); direction.value = route.direction; direction.disabled = route.locked; direction.addEventListener('change', () => routeCommands.updateRoute(route.id, { direction: direction.value as FactoryRouteDirection }));
    const speed = input('number', '0.1', 0); speed.value = route.nominalSpeed === null ? '' : String(route.nominalSpeed); speed.placeholder = 'Not set'; speed.disabled = route.locked; speed.addEventListener('change', () => { const value = speed.value.trim() === '' ? null : Number(speed.value); const accepted = value === null || Number.isFinite(value) && value > 0; speed.setAttribute('aria-invalid', String(!accepted)); if (accepted) routeCommands.updateRoute(route.id, { nominalSpeed: value }, `Set route speed ${route.id}`); });
    const enabled = checkbox('Enabled'); enabled.checked = route.enabled; enabled.disabled = route.locked; enabled.addEventListener('change', () => routeCommands.updateRoute(route.id, { enabled: enabled.checked }));
    const visible = checkbox('Visible'); visible.checked = route.visible; visible.disabled = route.locked; visible.addEventListener('change', () => routeCommands.updateRoute(route.id, { visible: visible.checked }));
    const locked = checkbox('Locked'); locked.checked = route.locked; locked.addEventListener('change', () => routeCommands.updateRoute(route.id, { locked: locked.checked }));
    const toggles = element('div', 'property-toggles'); toggles.append(toggle('Enabled', enabled), toggle('Visible', visible), toggle('Locked', locked));
    const note = element('textarea', 'property-input property-textarea'); note.rows = 3; note.value = route.note; note.disabled = route.locked; note.addEventListener('change', () => routeCommands.updateRoute(route.id, { note: note.value }));
    const endpointText = (endpoint: FactoryRoute['source']): string => endpoint.kind === 'free' ? `Free @ ${endpoint.point.x.toFixed(1)}, ${endpoint.point.y.toFixed(1)}` : `${endpoint.kind === 'resource' ? endpoint.resourceId : endpoint.areaId} — ${endpoint.anchorSide} @ ${endpoint.anchorOffset.toFixed(3)}`;
    const distance = factoryRouteDistance(route, resolver); const travelTime = estimatedTravelTimeSeconds(route, resolver);
    const actions = element('div', 'connection-property-actions'); const reverse = actionButton('Reverse Route', 'secondary-button'); reverse.disabled = route.locked; reverse.addEventListener('click', () => reportStatus(routeCommands.reverseRoute(route.id) ? 'Factory route reversed' : 'Route could not be reversed'));
    const insert = actionButton('Insert Waypoint', 'secondary-button'); insert.disabled = route.locked; insert.addEventListener('click', () => { const points = resolveFactoryRoutePolyline(route, resolver); if (points.length < 2) return; const index = Math.max(0, Math.floor((points.length - 1) / 2)); const start = points[index]; const end = points[index + 1]; const waypoint = { x: (start.x + end.x) / 2, y: (start.y + end.y) / 2 }; reportStatus(routeCommands.updateRoute(route.id, { waypoints: [...route.waypoints, waypoint] }, `Insert waypoint ${route.id}`) ? 'Waypoint inserted' : 'Waypoint could not be inserted'); });
    const remove = actionButton('Delete Route', 'secondary-button connection-delete-button'); remove.disabled = route.locked; remove.addEventListener('click', () => reportStatus(routeCommands.deleteRoute(route.id) ? 'Factory route deleted' : 'Route could not be deleted'));
    actions.append(reverse, insert, remove);
    const issuePanel = element('div', 'resource-layout-issues'); issuePanel.append(element('strong', '', 'Route validation')); if (issues.length) for (const issue of issues) issuePanel.append(element('p', `validation-${issue.severity}`, issue.message)); else issuePanel.append(element('p', 'property-help', 'No route validation issues.'));
    form.append(field('Route ID', output(route.id)), field('Layout ID', output(route.layoutId)), field('Name', name), field('Route type', type), field('Direction', direction), field('Source', output(endpointText(route.source))), field('Target', output(endpointText(route.target))), field('Waypoint count', output(String(route.waypoints.length))), field('Calculated distance', output(`${distance.toFixed(project.getSettings().displayPrecision)} project units`)), field('Nominal speed', speed), field('Estimated travel time', output(travelTime === null ? 'Set a nominal speed' : `${travelTime.toFixed(project.getSettings().displayPrecision)} s`)), toggles, field('Note', note), issuePanel, actions); properties.replaceChildren(form);
  };

  const renderFactoryStructure = (kind: 'boundary' | 'wall' | 'area' | 'aisle', id: string): void => {
    const form = element('form', 'properties-form factory-structure-properties'); form.addEventListener('submit', (event) => event.preventDefault());
    const actions = element('div', 'resource-property-actions'); const remove = actionButton(`Delete ${kind}`, 'secondary-button resource-delete-button'); remove.addEventListener('click', () => reportStatus(commands.deleteFactoryStructure(kind, id) ? `${kind} deleted` : `${kind} is locked or missing`)); actions.append(remove);
    if (kind === 'boundary') { const item = structure.getBoundary(id); if (!item) return; const name = input('text'); name.value = item.name; bindText(name, (value) => commands.updateBoundary(id, { name: value })); const visible = checkbox('Visible'); visible.checked = item.visible; visible.addEventListener('change', () => commands.updateBoundary(id, { visible: visible.checked })); const fill = checkbox('Fill visible'); fill.checked = item.fillVisible; fill.addEventListener('change', () => commands.updateBoundary(id, { fillVisible: fill.checked })); const locked = checkbox('Locked'); locked.checked = item.locked; locked.addEventListener('change', () => commands.updateBoundary(id, { locked: locked.checked })); const note = element('textarea', 'property-input property-textarea'); note.value = item.note; note.addEventListener('change', () => commands.updateBoundary(id, { note: note.value })); const xs = item.points.map((point) => point.x); const ys = item.points.map((point) => point.y); form.append(field('Boundary ID', output(id)), field('Name', name), field('Vertex count', output(String(item.points.length))), field('Calculated area', output(`${Math.abs(polygonArea(item.points)).toFixed(1)} mm²`)), field('Overall extents', output(`${(Math.max(...xs) - Math.min(...xs)).toFixed(1)} × ${(Math.max(...ys) - Math.min(...ys)).toFixed(1)}`)), toggle('Visible', visible), toggle('Floor fill visible', fill), toggle('Locked', locked), field('Note', note), actions); }
    if (kind === 'wall') { const item = structure.getWall(id); if (!item) return; const name = input('text'); name.value = item.name; bindText(name, (value) => commands.updateWall(id, { name: value })); const type = element('select', 'property-input'); FACTORY_WALL_TYPES.forEach((value) => type.append(option(value))); type.value = item.wallType; type.addEventListener('change', () => commands.updateWall(id, { wallType: type.value as typeof item.wallType })); const coordinate = (label: string, value: number, key: 'start' | 'end', axis: 'x' | 'y'): HTMLLabelElement => { const control = input('number'); control.value = String(value); control.disabled = item.locked; bindNumber(control, (next) => commands.updateWall(id, { [key]: { ...item[key], [axis]: next } }), Number.NEGATIVE_INFINITY); return field(label, control); }; const thickness = input('number', '5', 1); thickness.value = String(item.thickness); thickness.disabled = item.locked; bindNumber(thickness, (value) => commands.updateWall(id, { thickness: value }), 1); const visible = checkbox('Visible'); visible.checked = item.visible; visible.addEventListener('change', () => commands.updateWall(id, { visible: visible.checked })); const locked = checkbox('Locked'); locked.checked = item.locked; locked.addEventListener('change', () => commands.updateWall(id, { locked: locked.checked })); const note = element('textarea', 'property-input property-textarea'); note.value = item.note; note.addEventListener('change', () => commands.updateWall(id, { note: note.value })); form.append(field('Wall ID', output(id)), field('Name', name), field('Wall type', type), coordinate('Start X', item.start.x, 'start', 'x'), coordinate('Start Y', item.start.y, 'start', 'y'), coordinate('End X', item.end.x, 'end', 'x'), coordinate('End Y', item.end.y, 'end', 'y'), field('Length', output(wallLength(item).toFixed(1))), field('Thickness', thickness), toggle('Visible', visible), toggle('Locked', locked), field('Note', note), actions); }
    if (kind === 'area') { const item = structure.getArea(id); if (!item) return; const name = input('text'); name.value = item.name; bindText(name, (value) => commands.updateArea(id, { name: value })); const type = element('select', 'property-input'); FACTORY_AREA_TYPES.forEach((value) => type.append(option(value))); type.value = item.areaType; type.addEventListener('change', () => commands.updateArea(id, { areaType: type.value as typeof item.areaType })); const policy = element('select', 'property-input'); RESOURCE_PLACEMENT_POLICIES.forEach((value) => policy.append(option(value))); policy.value = item.resourcePlacementPolicy; policy.addEventListener('change', () => commands.updateArea(id, { resourcePlacementPolicy: policy.value as typeof item.resourcePlacementPolicy })); const numeric = (label: string, value: number, key: 'worldX' | 'worldY' | 'width' | 'depth' | 'rotationDegrees', minimum: number): HTMLLabelElement => { const control = input('number', key === 'rotationDegrees' ? '5' : key === 'worldX' || key === 'worldY' ? '1' : '5', minimum); control.value = String(value); control.disabled = item.locked; bindNumber(control, (next) => commands.updateArea(id, { [key]: next }), minimum); return field(label, control); }; const visible = checkbox('Visible'); visible.checked = item.visible; visible.addEventListener('change', () => commands.updateArea(id, { visible: visible.checked })); const fill = checkbox('Fill visible'); fill.checked = item.fillVisible; fill.addEventListener('change', () => commands.updateArea(id, { fillVisible: fill.checked })); const locked = checkbox('Locked'); locked.checked = item.locked; locked.addEventListener('change', () => commands.updateArea(id, { locked: locked.checked })); const note = element('textarea', 'property-input property-textarea'); note.value = item.note; note.addEventListener('change', () => commands.updateArea(id, { note: note.value })); form.append(field('Area ID', output(id)), field('Name', name), field('Area type', type), field('Resource placement policy', policy), numeric('X centre', item.worldX, 'worldX', Number.NEGATIVE_INFINITY), numeric('Y centre', item.worldY, 'worldY', Number.NEGATIVE_INFINITY), numeric('Width', item.width, 'width', 1), numeric('Depth', item.depth, 'depth', 1), numeric('Rotation', item.rotationDegrees, 'rotationDegrees', Number.NEGATIVE_INFINITY), toggle('Visible', visible), toggle('Fill visible', fill), toggle('Locked', locked), field('Note', note), actions); }
    if (kind === 'aisle') { const item = structure.getAisle(id); if (!item) return; const name = input('text'); name.value = item.name; bindText(name, (value) => commands.updateAisle(id, { name: value })); const type = element('select', 'property-input'); FACTORY_AISLE_TYPES.forEach((value) => type.append(option(value))); type.value = item.aisleType; type.addEventListener('change', () => commands.updateAisle(id, { aisleType: type.value as typeof item.aisleType })); const direction = element('select', 'property-input'); FACTORY_AISLE_DIRECTIONS.forEach((value) => direction.append(option(value))); direction.value = item.direction; direction.addEventListener('change', () => commands.updateAisle(id, { direction: direction.value as typeof item.direction })); const width = input('number', '5', 1); width.value = String(item.width); width.disabled = item.locked; bindNumber(width, (value) => commands.updateAisle(id, { width: value }), 1); const visible = checkbox('Visible'); visible.checked = item.visible; visible.addEventListener('change', () => commands.updateAisle(id, { visible: visible.checked })); const locked = checkbox('Locked'); locked.checked = item.locked; locked.addEventListener('change', () => commands.updateAisle(id, { locked: locked.checked })); const note = element('textarea', 'property-input property-textarea'); note.value = item.note; note.addEventListener('change', () => commands.updateAisle(id, { note: note.value })); form.append(field('Aisle ID', output(id)), field('Name', name), field('Aisle type', type), field('Direction', direction), field('Width', width), field('Point count', output(String(item.points.length))), field('Centreline length', output(polylineLength(item.points).toFixed(1))), field('Nominal corridor area', output((polylineLength(item.points) * item.width).toFixed(1))), toggle('Visible', visible), toggle('Locked', locked), field('Note', note), actions); }
    properties.replaceChildren(form);
  };

  const renderProject = (): void => {
    const state = project.getState(); const metadata = state.metadata; const form = element('form', 'properties-form project-properties'); form.addEventListener('submit', (event) => event.preventDefault());
    const name = input('text'); name.value = metadata.name; bindText(name, (value) => value ? commands.updateProjectMetadata({ name: value }) : false);
    const description = element('textarea', 'property-input property-textarea'); description.rows = 4; description.value = metadata.description; description.addEventListener('change', () => commands.updateProjectMetadata({ description: description.value.trim() }));
    const author = input('text'); author.value = metadata.author; bindText(author, (value) => commands.updateProjectMetadata({ author: value }));
    const company = input('text'); company.value = metadata.company; bindText(company, (value) => commands.updateProjectMetadata({ company: value }));
    const gridInterval = input('number', '1', 1); gridInterval.value = String(state.settings.gridBaseInterval); bindNumber(gridInterval, (value) => commands.updateProjectSettings({ gridBaseInterval: value }), 1);
    const routingClearance = input('number', '1', 0); routingClearance.value = String(state.settings.routingClearance); bindNumber(routingClearance, (value) => commands.updateProjectSettings({ routingClearance: value }), 0);
    const displayPrecision = input('number', '1', 0); displayPrecision.max = '6'; displayPrecision.value = String(state.settings.displayPrecision); bindNumber(displayPrecision, (value) => value <= 6 && commands.updateProjectSettings({ displayPrecision: value }), 0, true);
    form.append(field('Project name', name), field('Description', description), field('Author', author), field('Company', company), field('Grid base interval', gridInterval), field('Routing clearance', routingClearance), field('Display precision', displayPrecision), field('Unit system', output(state.settings.unitSystem)), field('Project ID', output(metadata.id)), field('Created UTC', output(metadata.createdUtc)), field('Modified UTC', output(metadata.modifiedUtc)), field('Schema version', output(PROJECT_SCHEMA_VERSION)), field('File', output(state.fileName ?? 'Not saved'))); properties.replaceChildren(form);
  };

  const render = (): void => {
    const selected = selection.getSelection(); const selectionState = selection.getState(); const workspace = workspaces.getActive(); const resource = resources.getSelectedResource(); const operation = operations.getSelectedOperation(); const connection = connections.getSelectedConnection(); const factoryRoute = selected.kind === 'factoryRoute' ? routes.getRoute(selected.id) : undefined;
    if (selectionState.items.length > 1) { const counts = { resources: selectionState.items.filter((item) => item.kind === 'resource').length, operations: selectionState.items.filter((item) => item.kind === 'operation').length, connections: selectionState.items.filter((item) => item.kind === 'connection').length }; const geometric = geometrySelection.getSelection(); const panel = element('div', 'multi-selection-properties'); panel.append(element('h3', '', `${selectionState.items.length} items selected`), element('p', '', `${counts.resources} resources · ${counts.operations} operations · ${counts.connections} connections · ${geometric.lockedCount} locked`)); const actions = element('div', 'multi-selection-actions'); const add = (label: string, run: () => { readonly message: string }, disabled = false): void => { const button = actionButton(label, 'secondary-button'); button.disabled = disabled; button.addEventListener('click', () => reportStatus(run().message)); actions.append(button); }; add('Copy', () => editing.copy()); add('Cut', () => editing.cut((message) => window.confirm(message))); add('Duplicate', () => editing.duplicate()); add('Delete', () => editing.deleteSelection((message) => window.confirm(message))); const arrangements: readonly [string, GeometryCommand][] = [['Align Left', 'align-left'], ['Align Top', 'align-top'], ['Distribute X', 'distribute-x'], ['Distribute Y', 'distribute-y'], ['Equal Gaps X', 'equal-gaps-x'], ['Equal Gaps Y', 'equal-gaps-y'], ['Match Width', 'match-width'], ['Match Height', 'match-height'], ['Match Size', 'match-size']]; for (const [label, command] of arrangements) add(label, () => geometryEditing.run(command), !geometryEditing.isAvailable(command)); panel.append(actions); properties.replaceChildren(panel); }
    else if (selected.kind === 'project') renderProject(); else if (workspace === 'factoryLayout' && selected.kind === 'resource' && resource) renderResource(); else if (workspace === 'factoryLayout' && selected.kind === 'factoryRoute' && factoryRoute) renderFactoryRoute(factoryRoute); else if (workspace === 'factoryLayout' && (selected.kind === 'boundary' || selected.kind === 'wall' || selected.kind === 'area' || selected.kind === 'aisle')) renderFactoryStructure(selected.kind, selected.id); else if (workspace === 'processFlow' && selected.kind === 'operation' && operation) renderOperation(); else if (workspace === 'processFlow' && selected.kind === 'connection' && connection) renderConnection(connection); else properties.replaceChildren(element('div', 'empty-inspector', `No ${workspace === 'processFlow' ? 'operation or connection' : 'physical resource, structure, or route'} selected`));
    summary.replaceChildren();
    if (selectionState.items.length > 1) { const geometric = geometrySelection.getSelection(); const bounds = aggregateBounds(geometric.nodes); summaryRow(summary, 'Selected items', String(selectionState.items.length)); summaryRow(summary, 'Eligible', String(geometric.nodes.length)); summaryRow(summary, 'Movable', String(geometric.unlocked.length)); summaryRow(summary, 'Locked', String(geometric.lockedCount)); summaryRow(summary, 'Ignored', String(geometric.ignoredCount)); summaryRow(summary, 'Primary', selectionState.primary?.id ?? 'None'); summaryRow(summary, 'Workspace', workspace === 'processFlow' ? 'Process Flow' : 'Factory Layout'); if (bounds) { summaryRow(summary, 'Aggregate X', bounds.left.toFixed(1)); summaryRow(summary, 'Aggregate Y', bounds.top.toFixed(1)); summaryRow(summary, 'Aggregate width', bounds.width.toFixed(1)); summaryRow(summary, 'Aggregate height', bounds.height.toFixed(1)); } }
    else if (selected.kind === 'project') { const state = project.getState(); summaryRow(summary, 'Object type', 'Project'); summaryRow(summary, 'ID', state.metadata.id); summaryRow(summary, 'Status', state.dirty ? 'Unsaved changes' : 'Saved'); summaryRow(summary, 'Operations', String(operations.getOperationCount())); summaryRow(summary, 'Connections', String(connections.getConnectionCount())); summaryRow(summary, 'Resources', String(resources.getResourceCount())); summaryRow(summary, 'Factory routes', String(routes.getCount())); }
    else if (workspace === 'factoryLayout' && factoryRoute) { const routeHealth = validateFactoryRoutes({ resources: resources.getPlacedResources(), structure, routes }); const resolver = { getResource: (id: string) => resources.getResource(id), getArea: (id: string) => structure.getArea(id) }; summaryRow(summary, 'Object type', 'Factory Route'); summaryRow(summary, 'ID', factoryRoute.id); summaryRow(summary, 'Type', factoryRoute.routeType); summaryRow(summary, 'Direction', factoryRoute.direction); summaryRow(summary, 'Distance', factoryRouteDistance(factoryRoute, resolver).toFixed(project.getSettings().displayPrecision)); summaryRow(summary, 'Waypoints', String(factoryRoute.waypoints.length)); summaryRow(summary, 'Route issues', String(routeValidationIssues(factoryRoute.id, routeHealth).length)); }
    else if (workspace === 'factoryLayout' && resource) { const layout = validateFactoryLayout(resources.getPlacedResources()); summaryRow(summary, 'Object type', 'Physical Resource'); summaryRow(summary, 'ID', resource.id); summaryRow(summary, 'Dimensions', `${resource.width} × ${resource.depth}`); summaryRow(summary, 'Rotation', `${resource.rotationDegrees}°`); summaryRow(summary, 'Active', resource.active ? 'Yes' : 'No'); summaryRow(summary, 'Assignments', String(operations.getAssignmentCount(resource.id))); summaryRow(summary, 'Related resources', issueIdsForResource(layout, resource.id).join(', ') || 'None'); summaryRow(summary, 'Layout resources', String(layout.total)); summaryRow(summary, 'Active resources', String(layout.active)); summaryRow(summary, 'Footprint area', `${layout.footprintArea.toFixed(project.getSettings().displayPrecision)} mm²`); summaryRow(summary, 'Clearance enabled', String(layout.clearanceEnabled)); summaryRow(summary, 'Layout issues', String(layout.issues.length)); }
    else if (workspace === 'processFlow' && operation) { summaryRow(summary, 'Object type', 'Operation'); summaryRow(summary, 'ID', operation.id); summaryRow(summary, 'Sequence', `OP ${operation.sequence}`); summaryRow(summary, 'Resource', operation.assignedResourceId ?? 'Unassigned'); }
    else if (workspace === 'processFlow' && connection) { const source = operations.getOperation(connection.sourceOperationId); const target = operations.getOperation(connection.targetOperationId); summaryRow(summary, 'Object type', 'Connection'); summaryRow(summary, 'ID', connection.id); summaryRow(summary, 'Type', connection.connectionType); summaryRow(summary, 'Source', `${source?.id ?? connection.sourceOperationId} — ${source?.name ?? 'Missing'}`); summaryRow(summary, 'Target', `${target?.id ?? connection.targetOperationId} — ${target?.name ?? 'Missing'}`); summaryRow(summary, 'Route length', routeLength(connection.routePoints).toFixed(1)); summaryRow(summary, 'Bends', String(routeBendCount(connection.routePoints))); }
    else if (workspace === 'factoryLayout') { const layout = validateFactoryLayout(resources.getPlacedResources()); const factory = validateFactoryStructure(resources.getPlacedResources(), structure); const routeSummary = validateFactoryRoutes({ resources: resources.getPlacedResources(), structure, routes }); summaryRow(summary, 'Boundary area', `${factory.boundaryArea.toFixed(project.getSettings().displayPrecision)} mm²`); summaryRow(summary, 'Boundary extents', `${factory.boundaryWidth.toFixed(1)} × ${factory.boundaryDepth.toFixed(1)}`); summaryRow(summary, 'Resources', String(layout.total)); summaryRow(summary, 'Active', String(layout.active)); summaryRow(summary, 'Footprint area', `${layout.footprintArea.toFixed(project.getSettings().displayPrecision)} mm²`); summaryRow(summary, 'Nominal footprint ratio', factory.boundaryArea > 0 ? `${(layout.footprintArea / factory.boundaryArea * 100).toFixed(1)}%` : 'No boundary'); summaryRow(summary, 'Walls / total length', `${factory.wallCount} / ${factory.totalWallLength.toFixed(1)}`); summaryRow(summary, 'Areas', String(factory.areaCount)); summaryRow(summary, 'Aisles / total length', `${factory.aisleCount} / ${factory.totalAisleLength.toFixed(1)}`); summaryRow(summary, 'Factory routes / enabled', `${routeSummary.total} / ${routeSummary.enabled}`); summaryRow(summary, 'Route distance', Object.values(routeSummary.distanceByType).reduce((sum, value) => sum + value, 0).toFixed(project.getSettings().displayPrecision)); summaryRow(summary, 'Routes with speed', String(routeSummary.withNominalSpeed)); summaryRow(summary, 'Clearance enabled', String(layout.clearanceEnabled)); summaryRow(summary, 'Structure issues', String(factory.issues.length)); summaryRow(summary, 'Route issues', String(routeSummary.issues.length)); }
    else summaryRow(summary, 'Selected items', '0');
    const operationHealth = validateOperations(operations.getOperations(), (id) => resources.getResource(id), (id) => Boolean(resources.getTemplate(id))); const resourceHealth = validateResources(resources.getPlacedResources(), resources.getTemplates(), (id) => operations.getAssignmentCount(id)); const connectionHealth = validateProcessConnections(operations.getOperations(), connections.getConnections()); const structureHealth = validateFactoryStructure(resources.getPlacedResources(), structure); const routeHealth = validateFactoryRoutes({ resources: resources.getPlacedResources(), structure, routes }); const errors = operationHealth.errors + resourceHealth.errors + connectionHealth.errors + routeHealth.errors + structureHealth.issues.filter((issue) => issue.severity === 'error').length; const warnings = operationHealth.warnings + resourceHealth.warnings + connectionHealth.warnings + routeHealth.warnings + structureHealth.issues.filter((issue) => issue.severity === 'warning').length;
    validation.replaceChildren(element('div', errors ? 'validation-error' : warnings ? 'validation-warning' : 'validation-healthy', errors ? '● Project has errors' : warnings ? '● Review warnings' : '● Project healthy')); const metrics = element('div', 'validation-metrics'); metrics.append(element('span', '', `${errors} Errors`), element('span', '', `${warnings} Warnings`)); validation.append(metrics);
    const issueEntries: ValidationListEntry[] = [];
    for (const entry of operationHealth.issues) {
      const affected = operations.getOperation(entry.operationId); const location = affected ? `OP ${affected.sequence} — ${affected.name}` : `Operation ${entry.operationId}`;
      issueEntries.push({ severity: entry.severity, location, message: entry.message, navigate: () => { workspaces.activate('processFlow'); operations.selectOperation(entry.operationId); revealOperation(entry.operationId); reportStatus(`Showing validation issue at ${location}`); } });
    }
    for (const entry of resourceHealth.issues) {
      const affected = resources.getResource(entry.resourceId); const location = affected ? `${affected.id} — ${affected.name}` : `Resource ${entry.resourceId}`;
      issueEntries.push({ severity: entry.severity, location, message: entry.message, navigate: () => { workspaces.activate('factoryLayout'); resources.selectResource(entry.resourceId); revealResource(entry.resourceId); reportStatus(`Showing validation issue at ${location}`); } });
    }
    for (const entry of connectionHealth.issues) {
      if (entry.connectionId) {
        const location = `Connection ${entry.connectionId}`;
        issueEntries.push({ severity: entry.severity, location, message: entry.message, navigate: () => { workspaces.activate('processFlow'); connections.selectConnection(entry.connectionId!); revealConnection(entry.connectionId!); reportStatus(`Showing validation issue at ${location}`); } });
      } else if (entry.operationId) {
        const affected = operations.getOperation(entry.operationId); const location = affected ? `OP ${affected.sequence} — ${affected.name}` : `Operation ${entry.operationId}`;
        issueEntries.push({ severity: entry.severity, location, message: entry.message, navigate: () => { workspaces.activate('processFlow'); operations.selectOperation(entry.operationId!); revealOperation(entry.operationId!); reportStatus(`Showing validation issue at ${location}`); } });
      } else {
        issueEntries.push({ severity: entry.severity, location: 'Process Flow', message: entry.message, navigate: () => { workspaces.activate('processFlow'); reportStatus('Showing Process Flow validation issue'); } });
      }
    }
    for (const entry of structureHealth.issues) { const location = `${entry.entityKind} ${entry.entityId}`; issueEntries.push({ severity: entry.severity, location, message: entry.message, navigate: () => { workspaces.activate('factoryLayout'); if (entry.entityKind === 'resource') resources.selectResource(entry.entityId); else selection.select({ kind: entry.entityKind, id: entry.entityId }); reportStatus(`Showing validation issue at ${location}`); } }); }
    for (const entry of routeHealth.issues) { const location = `Factory route ${entry.routeId}`; issueEntries.push({ severity: entry.severity, location, message: entry.message, navigate: () => { workspaces.activate('factoryLayout'); selection.select({ kind: 'factoryRoute', id: entry.routeId }); revealFactoryRoute(entry.routeId); reportStatus(`Showing validation issue at ${location}`); } }); }
    issueEntries.sort((left, right) => left.severity === right.severity ? left.location.localeCompare(right.location) || left.message.localeCompare(right.message) : left.severity === 'error' ? -1 : 1);
    if (issueEntries.length) {
      validation.append(element('div', 'validation-list-heading', `${issueEntries.length} issue${issueEntries.length === 1 ? '' : 's'} — select one to locate it`));
      const list = element('ul', 'validation-issues');
      for (const entry of issueEntries) {
        const item = element('li', `validation-issue validation-issue--${entry.severity}`); const button = actionButton(`${entry.location}: ${entry.message}`, 'validation-issue__button');
        button.replaceChildren(element('span', 'validation-issue__icon', entry.severity === 'error' ? '⛔' : '⚠'), element('strong', 'validation-issue__location', entry.location), element('span', 'validation-issue__message', entry.message));
        button.setAttribute('aria-label', `${entry.severity === 'error' ? 'Error' : 'Warning'} at ${entry.location}: ${entry.message}. Select to locate.`); button.addEventListener('click', entry.navigate); item.append(button); list.append(item);
      }
      validation.append(list);
    }
  };
  const unsubscribers = [resources.subscribe(render), operations.subscribe(render), connections.subscribe(render), structure.subscribe(render), routes.subscribe(render), workspaces.subscribe(render), selection.subscribe(render), project.subscribe(render)]; render();
  return { element: sidebar, dispose: () => unsubscribers.forEach((unsubscribe) => unsubscribe()) };
}
