import type { CanvasState } from '../../../models/canvas/CanvasState';
import { MIN_OPERATION_HEIGHT, MIN_OPERATION_WIDTH, type OperationStore } from '../../../services/OperationStore';
import { MIN_RESOURCE_HEIGHT, MIN_RESOURCE_WIDTH, type ResourceStore } from '../../../services/ResourceStore';
import type { SnapService } from '../../../services/SnapService';
import { boundsOf, geometryValue, sameGeometry, type GeometrySnapshot, type GeometryValue } from '../../../services/geometry/GeometryBounds';
import { calculateResizeGeometry, type ResizeHandle } from '../../../services/geometry/ResizeGeometry';
import type { GeometrySelectionService } from '../../../services/geometry/GeometrySelectionService';
import type { GeometryCommandFactory } from '../../../services/history/GeometryCommandFactory';
import { screenToWorld, type Point } from './ViewportTransform';
import type { AlignmentGuideController } from './AlignmentGuideController';

interface ActiveResize { readonly pointerId: number; readonly handle: ResizeHandle; readonly node: GeometrySnapshot; readonly original: GeometryValue; pending: GeometryValue | null; frame: number; }
export class ResizeInteractionController {
  private active: ActiveResize | null = null;
  public constructor(private readonly viewport: HTMLElement, private readonly state: CanvasState, private readonly selected: GeometrySelectionService, private readonly operations: OperationStore, private readonly resources: ResourceStore, private readonly snap: SnapService, private readonly commands: GeometryCommandFactory, private readonly guides: AlignmentGuideController, private readonly onStatus: (message: string) => void) { viewport.addEventListener('pointerdown', this.pointerDown); viewport.addEventListener('pointermove', this.pointerMove); viewport.addEventListener('pointerup', this.pointerUp); viewport.addEventListener('pointercancel', this.pointerCancel); viewport.addEventListener('lostpointercapture', this.lostCapture); document.addEventListener('keydown', this.keyDown); }
  public cancel(): void { this.finish(false); }
  public dispose(): void { this.cancel(); this.viewport.removeEventListener('pointerdown', this.pointerDown); this.viewport.removeEventListener('pointermove', this.pointerMove); this.viewport.removeEventListener('pointerup', this.pointerUp); this.viewport.removeEventListener('pointercancel', this.pointerCancel); this.viewport.removeEventListener('lostpointercapture', this.lostCapture); document.removeEventListener('keydown', this.keyDown); }
  private readonly local = (event: PointerEvent): Point => { const bounds = this.viewport.getBoundingClientRect(); return { x: event.clientX - bounds.left, y: event.clientY - bounds.top }; };
  private readonly pointerDown = (event: PointerEvent): void => { if (event.button !== 0 || this.state.tool !== 'select') return; const target = event.target instanceof Element ? event.target.closest<SVGGElement>('[data-resize-handle]') : null; const handle = target?.dataset.resizeHandle as ResizeHandle | undefined; const selection = this.selected.getSelection(); const node = selection.nodes.length === 1 ? selection.nodes[0] : null; if (!handle || !node || node.locked || !node.visible) return; event.preventDefault(); event.stopImmediatePropagation(); this.active = { pointerId: event.pointerId, handle, node, original: geometryValue(node), pending: null, frame: 0 }; this.guides.begin(node.kind, [node.id]); this.viewport.setPointerCapture(event.pointerId); this.onStatus(`Resizing ${node.kind === 'operation' ? `OP-${String(this.operations.getOperation(node.id)?.sequence ?? node.id).padStart(4, '0')}` : node.id}`); };
  private readonly pointerMove = (event: PointerEvent): void => { if (!this.active || event.pointerId !== this.active.pointerId) return; event.preventDefault(); event.stopImmediatePropagation(); this.active.pending = this.calculate(this.active, screenToWorld(this.local(event), this.state), event.altKey, event.shiftKey); if (!this.active.frame) this.active.frame = requestAnimationFrame(this.flush); };
  private readonly pointerUp = (event: PointerEvent): void => { if (this.active?.pointerId === event.pointerId) { event.preventDefault(); event.stopImmediatePropagation(); this.finish(true); } };
  private readonly pointerCancel = (event: PointerEvent): void => { if (this.active?.pointerId === event.pointerId) this.finish(false); };
  private readonly lostCapture = (event: PointerEvent): void => { if (this.active?.pointerId === event.pointerId) this.finish(false); };
  private readonly keyDown = (event: KeyboardEvent): void => { if (event.key === 'Escape' && this.active) { event.preventDefault(); event.stopImmediatePropagation(); this.finish(false); } };
  private readonly flush = (): void => { if (!this.active) return; this.active.frame = 0; const pending = this.active.pending; this.active.pending = null; if (pending) this.apply(this.active.node, pending); };
  private finish(commit: boolean): void { const active = this.active; if (!active) return; if (active.frame) cancelAnimationFrame(active.frame); if (commit && active.pending) this.apply(active.node, active.pending); if (!commit) this.apply(active.node, active.original); const current = this.read(active.node) ?? active.original; const changed = commit && !sameGeometry(active.original, current); if (changed) { const label = active.node.kind === 'operation' ? `operation OP-${String(this.operations.getOperation(active.node.id)?.sequence ?? active.node.id).padStart(4, '0')}` : `resource ${active.node.id}`; this.commands.commit(`Resize ${label}`, [{ id: active.node.id, kind: active.node.kind, before: active.original, after: current }]); } this.active = null; this.guides.clear(); if (this.viewport.hasPointerCapture(active.pointerId)) this.viewport.releasePointerCapture(active.pointerId); this.onStatus(commit ? changed ? `Resized ${active.node.id}` : 'Size unchanged' : 'Resize cancelled'); }
  private calculate(active: ActiveResize, pointer: Point, bypass: boolean, preserveAspect: boolean): GeometryValue { const minimums = { width: active.node.kind === 'operation' ? MIN_OPERATION_WIDTH : MIN_RESOURCE_WIDTH, height: active.node.kind === 'operation' ? MIN_OPERATION_HEIGHT : MIN_RESOURCE_HEIGHT }; const raw = calculateResizeGeometry(active.original, active.handle, pointer, minimums, preserveAspect); const guide = this.guides.resolveBounds(boundsOf(raw), bypass); const moving = { x: pointer.x, y: pointer.y }; if (!bypass) { moving.x = this.snap.enabled && guide.matchedX && (active.handle.includes('left') || active.handle.includes('right')) ? pointer.x + guide.dx : this.snap.enabled ? this.snap.snapValue(pointer.x) : pointer.x; moving.y = this.snap.enabled && guide.matchedY && (active.handle.includes('top') || active.handle.includes('bottom')) ? pointer.y + guide.dy : this.snap.enabled ? this.snap.snapValue(pointer.y) : pointer.y; } return calculateResizeGeometry(active.original, active.handle, moving, minimums, preserveAspect); }
  private apply(node: GeometrySnapshot, value: GeometryValue): boolean { return node.kind === 'operation' ? this.operations.updateOperation(node.id, { worldX: value.x, worldY: value.y, width: value.width, height: value.height }) : this.resources.updateResource(node.id, { worldX: value.x, worldY: value.y, width: value.width, height: value.height }); }
  private read(node: GeometrySnapshot): GeometryValue | null { const value = node.kind === 'operation' ? this.operations.getOperation(node.id) : this.resources.getResource(node.id); return value ? { x: value.worldX, y: value.worldY, width: value.width, height: value.height } : null; }
}
